### ISSUE TITLE
💡 [需求] 希望出一个能把Hyperos图标改成CNMIOS图标的

### ISSUE THREAD

**Issue by xiaomajy** [ReChronoRain/HyperCeiler#102]
### 需求内容

把设备图标变成cnmios

### 实现思路&截图

![Screenshot_2023-11-28-22-06-10-298_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/88231018/d26f83b0-04a9-40de-a73d-5b67474d3e59)

### 简单例子

把这里图标变成cnmios

**Comment by HChenX** [comment]
？
