### ISSUE TITLE
🐛 [BUG] <disable automatic closing of Mi Share doesn't work sometimes>

### ISSUE THREAD

**Issue by Vader77Darth** [ReChronoRain/HyperCeiler#1031]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

#570 says it all. I don't know why it was closed as it is still broken on my Xiaomi Pad 5

### 模块日志

check #570

### 复现步骤

```bash
1. 前往 'read #570'
2. 点击 '....'

....
出现问
```

### 问题截图

See #570

### HyperCeiler 设备信息

See #570

**Comment by Sevtinge** [comment]
pad5系统和自带小米互传版本太老 不再维护
有需要就去用新小米互传

**Comment by Vader77Darth** [comment]
Thanks for clarifying.
