### ISSUE TITLE
💡 [需求] <相机增加解锁街拍模式>

### ISSUE THREAD

**Issue by junguoqianshan** [ReChronoRain/HyperCeiler#104]
### 需求内容

希望在相机里解锁街拍模式的功能。

### 实现思路&截图

有模块可以实现此功能，但是在安卓14上不再有效。https://github.com/GSWXXN/UnlockMIUICameraSnap

### 简单例子

如图，这是解锁街拍模式后的界面。
![b0fa58d0c4b97ac3caa56fad19f7b293](https://github.com/ReChronoRain/HyperCeiler/assets/94796625/1ac1b698-2cff-4cc8-a8dc-a50a03f86f23)
![Uploading f256a70923eda1248c88fd80a6ea73e6.jpeg…]()

**Comment by Sevtinge** [comment]
查看「设置-锁屏-急速相机」![Screenshot_2023-12-26-16-16-51-518_com.android.settings-edit.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/89193494/b9eab101-c38e-4352-99a6-72a439e30574)

**Comment by junguoqianshan** [comment]
![Screenshot_2024-01-28-11-49-19-301_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/94796625/e49af4cd-2ef4-4469-92f8-c665592cdb52)
检查后发现界面没有立刻选项
