### ISSUE TITLE
💡 [需求] 状态栏图标左侧显示

### ISSUE THREAD

**Issue by zym013579** [ReChronoRain/HyperCeiler#105]
### 需求内容

Cemiuiler原有功能：系统界面-状态栏-状态栏图标右侧显示
在HyperOS上，这些图标都被丢到右边去了，让本就不富裕的空间雪上加霜（有时候还把网速给挤没了

或者可以改成选项，分别为默认，居左和居右三个选项

### 实现思路&截图

Cemiuiler已经有类似的功能，只是在HyperOS上发生了一些变化（MIUI默认图标居左，HyperOS默认图标居右）

### 简单例子

https://github.com/ReChronoRain/HyperCeiler/blob/main/app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/statusbar/icon/all/StatusBarIconPositionAdjust.java

**Comment by mu7220** [comment]
![image](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/56843290-5ab5-4b57-acb8-13e3ee9d99cb)
综上所述，HyperOS 不打算支持这个功能了
