### ISSUE TITLE
🐛 [BUG] 打开手电筒后，系统界面重启

### ISSUE THREAD

**Issue by Rqazwsx** [ReChronoRain/HyperCeiler#1051]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

桌面下滑打开手电筒，手机黑屏，系统桌面重启。

### 模块日志

[LSPosed_2024-12-17T21_27_06.688594.zip](https://github.com/user-attachments/files/18166224/LSPosed_2024-12-17T21_27_06.688594.zip)

### 复现步骤

```bash
1. 从桌面顶部下滑，打开控制中心
2. 点击手电筒，闪光灯亮一下后立马熄灭，同时手机黑屏，系统界面重启
```

### 问题截图

![Screenshot_2024-12-17-21-27-19-940_com fankes apperrorstracking](https://github.com/user-attachments/assets/44a83a3e-0c07-498b-aa48-88d35194b363)
![Screenshot_2024-12-17-21-27-21-670_com fankes apperrorstracking](https://github.com/user-attachments/assets/d94c2bf9-ae01-47ba-8085-bd18c2196c79)

### HyperCeiler 设备信息

![Screenshot_2024-12-17-21-37-49-265_com sevtinge hyperceiler](https://github.com/user-attachments/assets/de70f931-6fcd-48a6-b1d6-43c0d26a6e65)

**Comment by MoGuangYu** [comment]
我跟你一模一样，请问解决了吗？
