### ISSUE TITLE
🐛 [BUG] 清理分享/打开方式/文本上下文菜单 已选应用无法显示应用列表

### ISSUE THREAD

**Issue by ChenXiaoming233** [ReChronoRain/HyperCeiler#1060]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

清理分享/打开方式/文本上下文菜单 已选应用无法显示应用列表，显示为空白（奇怪好好的怎么自己坏掉了（）

### 模块日志

[LSPosed_2024-12-21T01_22_23.478886.zip](https://github.com/user-attachments/files/18213855/LSPosed_2024-12-21T01_22_23.478886.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-12-21-01-57-01-389_com sevtinge hyperceiler](https://github.com/user-attachments/assets/0a5592de-eda6-4552-a277-e6d0ad9053db)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-12-21-01-40-09-082_com sevtinge hyperceiler](https://github.com/user-attachments/assets/304545b6-788e-440a-8dc8-42f66a6da98b)

**Comment by Sevtinge** [comment]
12fbc68e5705c43fe1565637dea1ea0382c584b6
