### ISSUE TITLE
移植米客的自动亮度范围以及网速单行

### ISSUE THREAD

**Issue by 511xy** [ReChronoRain/HyperCeiler#111]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

移植米客的自动亮度范围，还有一个状态栏网速单行

### 相关描述&截图

![Screenshot_2023-12-02-10-21-52-713_name monwf customiuizer](https://github.com/ReChronoRain/HyperCeiler/assets/50691422/a5d982ef-ca35-49ba-b26a-0dda8d55033b)

**Comment by HChenX** [comment]
搁置
