### ISSUE TITLE
🐛 [BUG] <问题标题>，控制中心的圆角矩形磁贴，部分显示有问题

### ISSUE THREAD

**Issue by Jiran233** [ReChronoRain/HyperCeiler#120]
### 问题描述

控制中心的圆角矩形磁贴，部分显示有问题
比如打开手电筒会变回园形，关闭之后还是圆形
打开游戏之后有一些是不能点击使用的也是圆形
未完全关闭的蓝牙不单是圆形，也显示有问题

### 模块日志

[Uploading LSPosed_2023-12-02T20_42_39.337533.zip…]()
[Uploading LSPosed_2023-12-02T20_42_42.735580.zip…]()

### 复现步骤

```bash
去模块里面把那个控制中心的圆角矩形磁贴打开
然后打开关闭蓝牙，打开关闭手电筒
```

### 问题截图

![图片注释](图片链接)

### 机型

Redmi K60 Pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

版本：2.3.132_20231202_1169e 4 f 5

**Comment by HChenX** [comment]
再试试新ci

**Comment by Jiran233** [comment]
> 再试试新ci

现在应该只有打开手电筒会变成圆的了其他应该都正常了
