### ISSUE TITLE
🐛 [BUG] <问题标题>，数据显示当中的只有音量百分比是正常的，那个亮度百分比没有作用

### ISSUE THREAD

**Issue by Jiran233** [ReChronoRain/HyperCeiler#121]
### 问题描述

在系统界面，其他里面的数据显示当中的音量和那个声音显示百分比，只有音量的声效了，亮度那个不生效

### 模块日志

[Uploading LSPosed_2023-12-02T20_48_02.019149.zip…]()

### 复现步骤

```bash
在系统界面，其他里面打开数据显示当中的亮度显示百分比
然后这个亮度无论怎么拖动都没办法显示百分比
```

### 问题截图

![图片注释](图片链接)

### 机型

Redmi K60 Pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

版本：2.3.132_20231202_1169e 4 f 5

**Comment by HChenX** [comment]
已知，搁置

**Comment by z1298808165** [comment]
> 已知，搁置

好的，幸苦了🌹
