### ISSUE TITLE
双排移动网络图标缩放不生效

### ISSUE THREAD

**Issue by Blueoxean** [ReChronoRain/HyperCeiler#129]
### 问题描述

hyperosA14双排移动网络图标缩放不生效
附lsp详细日志一份

### 模块日志

[LSPosed_2023-12-04T23_04_34.157757.zip](https://github.com/ReChronoRain/HyperCeiler/files/13547863/LSPosed_2023-12-04T23_04_34.157757.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

k60u

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231204 | beta

**Comment by mu7220** [comment]
已在最新版修复
