### ISSUE TITLE
移动网络类型图标单独显示默认显示在左侧且无法修改

### ISSUE THREAD

**Issue by Blueoxean** [ReChronoRain/HyperCeiler#130]
### 问题描述

无论是否勾选显示在信号左侧，始终都保持在信号左侧，无法将其更改到信号右侧，附lsp日志和截图

### 模块日志

[LSPosed_2023-12-04T23_15_19.963934.zip](https://github.com/ReChronoRain/HyperCeiler/files/13547965/LSPosed_2023-12-04T23_15_19.963934.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-12-04-23-15-43-962_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/a293c261-fcd7-4532-b0c1-3c94ad8c224b)

### 机型

k60u

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231204 | beta

**Comment by mu7220** [comment]
已在最新版修复
