### ISSUE TITLE
🐛 [BUG] <8.6.1手机管家禁用体检优化无效>

### ISSUE THREAD

**Issue by Benetsu** [ReChronoRain/HyperCeiler#135]
### 问题描述

从8.6.1版本开始禁用体检优化无效

### 模块日志

。。。

### 复现步骤

```bash
1. 前往 '手机管家'
2. 点击 '禁用体检优化'
```

### 问题截图

![图片注释](图片链接)

### 机型

Xiaomi MIX4

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133-20231205

**Comment by mu7220** [comment]
之后遇到此问题的解决方案：
清除手机管家数据→重新优化手机管家

原理：手机管家已缓存分数，需要清理才能正常显示

**Comment by unknowntokyo** [comment]
按上面方法处理了 还是不行
