### ISSUE TITLE
🐛 [BUG] <双排移动网络图标显示异常>

### ISSUE THREAD

**Issue by NuclearCola** [ReChronoRain/HyperCeiler#142]
### 问题描述

双排移动网络图标显示异常

### 模块日志

[LSPosed_2023-12-09T12_05_32.902591(1).zip](https://github.com/ReChronoRain/HyperCeiler/files/13622629/LSPosed_2023-12-09T12_05_32.902591.1.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![Screenshot_2023-12-09-11-57-18-594_com sevtinge c](https://github.com/ReChronoRain/HyperCeiler/assets/153342660/4991c3b9-e356-4d19-a51e-f925846d6b54)

### 机型

小米12Spro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

1.3.130_20231101

**Comment by HChenX** [comment]
已知，搁置

**Comment by YunnrEX** [comment]
这个把默认改成跟随主题就行了，我是这样好的

**Comment by Baymax52** [comment]
同样，开启隐藏屏幕缺口好像能解决，但是屏幕缺口也有bug
