### ISSUE TITLE
🐛 [BUG] 恢复模块配置时卡死

### ISSUE THREAD

**Issue by zeyudada** [ReChronoRain/HyperCeiler#145]
### 问题描述

在hyperceiler恢复cemiuiler导出的配置时直接卡死，长时间无响应
导出配置文件的版本是1.2.129_20231027

### 模块日志

[Cemiuiler_settings_backup_2023-12-06-22_31_18.json](https://github.com/ReChronoRain/HyperCeiler/files/13624520/Cemiuiler_settings_backup_2023-12-06-22_31_18.json)
卡死了，DEBUG等级下根本没有日志

### 复现步骤

```bash
1. 前往 '设置'
2. 点击 '恢复模块配置'，选择文件后卡死

....
出现问题
```

### 问题截图

以下是视频

https://github.com/ReChronoRain/HyperCeiler/assets/64437653/e911a361-0bb0-407c-946e-e22fc859329f

### 机型

红米 K60

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

2.3.132_20231204

**Comment by HChenX** [comment]
换个cemiuiler版本到处配置
