### ISSUE TITLE
锁屏显示秒数、隐藏负一屏无效

### ISSUE THREAD

**Issue by cibimo** [ReChronoRain/HyperCeiler#146]
### 问题描述

锁屏显示秒数、隐藏负一屏无效

### 模块日志

无崩溃，下方显示充电详情有效

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

12su

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

1.0.23.12.4 DEV

**Comment by mu7220** [comment]
锁屏显秒新版已移除，不另写
隐藏等修

**Comment by cibimo** [comment]
希望之后还是能支持一下锁屏显秒，研究半天只能用其他主题实现

**Comment by HChenX** [comment]
负一屏不是有开关吗

**Comment by mu7220** [comment]
后者已修复
