### ISSUE TITLE
状态栏 sim2 信号无法隐藏

### ISSUE THREAD

**Issue by lockpanda** [ReChronoRain/HyperCeiler#148]
### 问题描述

修改状态栏 图标 不起作用  sim2图标不能修改[

### 模块日志

[LSPosed_2023-12-10T11_17_06.006926.zip](https://github.com/ReChronoRain/HyperCeiler/files/13626284/LSPosed_2023-12-10T11_17_06.006926.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

xiaomi13

### MIUI/HyperOS 版本

MIUI14, Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231209

**Comment by mu7220** [comment]
已在最新版修复
