### ISSUE TITLE
💡 [需求] 息屏通知光效动画循环播放次数或时间

### ISSUE THREAD

**Issue by AUdkkk** [ReChronoRain/HyperCeiler#149]
### 需求内容

系统默认通知光效星光来通知只播放一次，有时候很难察觉到，希望来通知时动画可以循环播放一定的次数，或者在一段时间内如5分钟10分钟这样循环播放，这样能更容易知道有消息来了，望采纳谢谢！

### 简单例子

原设置了通知光效，模块里可以设置循环次数或者在一定时间内循环播放光效

**Comment by HChenX** [comment]
6
