### ISSUE TITLE
🐛 [BUG] <硬件指示器无效）

### ISSUE THREAD

**Issue by YunnrEX** [ReChronoRain/HyperCeiler#152]
### 问题描述

hyperos状态栏硬件指示器无效

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

k70p

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

最新版

**Comment by mu7220** [comment]
罚你重看更新日志
