### ISSUE TITLE
💡 [需求] 录音机解锁 应用通话录音 设置

### ISSUE THREAD

**Issue by OcrSu** [ReChronoRain/HyperCeiler#154]
### 需求内容

录音机解锁应用内录音设置。
部分机型没有这个设置开关。

### 实现思路&截图

![ba2ffa73548e74813c30e5c0f39952af](https://github.com/ReChronoRain/HyperCeiler/assets/75876201/28e7f99f-136a-479a-a015-d869021b73a1)

### 简单例子

在微信/QQ等软件内使用语音通话可以自动录音

**Comment by HChenX** [comment]
这个可能要系统适配，不搞

**Comment by OcrSu** [comment]
> 这个可能要系统适配，不搞

我的机型是Note12T Pro，我从Note12 Pro极速版的包里面提取出来的录音助手可以直接安装到我的手机上，而且测试没有bug。
这样的适配方式，确实集成在HyperCeiler 上面不是很妥当。
仅分享适配方法，并没有其他意图。
