### ISSUE TITLE
🐛 [BUG] <兼容模式导致桌面图标上移>

### ISSUE THREAD

**Issue by shugo-chara** [ReChronoRain/HyperCeiler#155]
### 问题描述

开启状态栏里的兼容模式后，桌面图标出现上移。

### 模块日志

[LSPosed_2023-12-11T20_18_53.333255.zip](https://github.com/ReChronoRain/HyperCeiler/files/13634687/LSPosed_2023-12-11T20_18_53.333255.zip)

### 复现步骤

```bash
开启状态栏里的兼容模式后，桌面图标出现上移。
取消后恢复。
```

### 问题截图

![图片注释](图片链接)
![IMG_20231211_202305](https://github.com/ReChronoRain/HyperCeiler/assets/20610965/76008ca4-afef-41f1-8881-b91cb00a83e5)

### 机型

mix fold 3

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231208_2ecf58a 0

**Comment by HChenX** [comment]
我觉得这不是bug
