### ISSUE TITLE
2×2小部件任然与文件夹大小不一

### ISSUE THREAD

**Issue by Blueoxean** [ReChronoRain/HyperCeiler#158]
### 问题描述

hyperceiler最新ci任然未能修复

![IMG_20231212_164256](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/76dd7b90-aa8b-455f-b51e-6783960a85f4)

`初以为是提供方法失效，便自行用该方法修改了一遍桌面，结果发现该方法任然生效，桌面版本为7749，澎湃最新桌面

![IMG_20231212_163947](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/0f9af434-12e5-436e-b062-f7d3d609aab8)

现重新提供方法望开发者能于百忙之中抽闲修复

![Screenshot_2023-12-12-16-53-50-714_bin mt plus](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/acaa327a-7691-4f44-94e2-5b59ea3e061e)
![IMG_20231212_165536](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/e228ff43-b973-4984-aef6-be362bb50a7c)
![IMG_20231212_165510](https://github.com/ReChronoRain/HyperCeiler/assets/131772631/39da9bd1-1af6-410a-8c18-ca8988e3ec12)

### 模块日志

如上

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

k60u

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133 202 31211(133)_beta

**Comment by HChenX** [comment]
可能类型转换不对回头换一下

**Comment by HChenX** [comment]
已经调整

**Comment by HChenX** [comment]
可以用吱一声

**Comment by Blueoxean** [comment]
> 可以用吱一声

刚刚测试了还是不行😭

**Comment by HChenX** [comment]
> > 可以用吱一声
> 
> 刚刚测试了还是不行😭

再试试新的

**Comment by Blueoxean** [comment]
> > > 可以用吱一声
> > 
> > 刚刚测试了还是不行😭
> 
> 再试试新的

okok👌新版成功了，感谢！🥰
