### ISSUE TITLE
🐛 [BUG] <状态栏隐藏无sim卡图标失效>

### ISSUE THREAD

**Issue by wqifan** [ReChronoRain/HyperCeiler#160]
### 问题描述

![Screenshot_2023-12-11-00-06-55-526_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/13233290/a92f2d8c-2f81-419f-8622-cedf1f5e9873)

### 模块日志

![Screenshot_2023-12-11-00-11-22-552_com android shell](https://github.com/ReChronoRain/HyperCeiler/assets/13233290/72c3d623-da22-47fd-bd99-2600e5191c24)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

xiaomi11u

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231211

**Comment by mu7220** [comment]
2.3.137 开始 HyperOS 应该能正常隐藏了
