### ISSUE TITLE
🐛 [BUG] <锁屏界面功能开关失效>

### ISSUE THREAD

**Issue by unknowntokyo** [ReChronoRain/HyperCeiler#165]
### 问题描述

锁屏界面下的几个功能开关失效（隐藏相机、负一屏、隐藏屏幕底部解锁提示、禁用长按进入解锁编辑等）。

### 模块日志

[LSPosed_2023-12-13T16_53_46.870859.zip](https://github.com/ReChronoRain/HyperCeiler/files/13658509/LSPosed_2023-12-13T16_53_46.870859.zip)

### 复现步骤

```bash
打开开关不生效
```

### 问题截图

![Screenshot_2023-12-13-17-00-22-311_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/24322657/c2695222-1908-48d6-a99f-68f986a99642)

### 机型

小米14pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

HyperCeiler_2.3.134_20231213_428916b8(134)_canary

**Comment by mu7220** [comment]
已在最新版本全部修复完毕
