### ISSUE TITLE
🐛 [BUG] <系统界面-状态栏-图标-移动网络图标类型>

### ISSUE THREAD

**Issue by NaCl-0323** [ReChronoRain/HyperCeiler#168]
### 问题描述

移动网络类型图标单独显示开启后，未打开隐藏移动网络活动指示器，网络指示器会消失
![Screenshot_2023-12-14-17-11-15-746_org telegram messenger](https://github.com/ReChronoRain/HyperCeiler/assets/52035277/812cffab-b43a-4d3b-abff-b8ca26d292f5)

### 模块日志

无

### 复现步骤

```bash
1. 前往 '系统界面-状态栏-图标-移动网络图标类型'
2. 点击 '移动网络图标单独显示'
状态栏网络指示器一瞬间后消失，已排除其他图标过多占用字符串位
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

Xiaomi 13 Pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231214_13440bcf

**Comment by mu7220** [comment]
已在最新版修复
