### ISSUE TITLE
💡 [需求] 屏蔽放误触

### ISSUE THREAD

**Issue by huoyan1231** [ReChronoRain/HyperCeiler#170]
### 需求内容

关闭miui自带的左下角/右下角防误触

### 简单例子

解决由于防误触导致的左下角/右下角触控不灵敏

**Comment by Sevtinge** [comment]
![Screenshot_2023-12-26-16-09-56-057_com.miui.securityadd.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/89193494/c4f22b76-0a5d-4b72-b941-bb36a2ca4c40)

您可能在找：
