### ISSUE TITLE
🐛 [BUG] 声音与触感闪退

### ISSUE THREAD

**Issue by EternalTimes** [ReChronoRain/HyperCeiler#172]
### 问题描述

勾选设置后，进入声音与触感闪退

### 模块日志

[LSPosed_2023-12-15T12_12_16.585498.zip](https://github.com/ReChronoRain/HyperCeiler/files/13680918/LSPosed_2023-12-15T12_12_16.585498.zip)

### 复现步骤

```bash
1. 前往 '设置'
2. 点击 '声音与震动'

出现问题：设置闪退
```

### 问题截图

![图片注释](图片链接)

### 机型

Xiaomi 13

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231215_cbf74341

**Comment by 125Justin** [comment]
一样声音与触感闪退，模块作用域取消勾选设置后可正常进入。
![Screenshot_2023-12-18-04-16-07-399_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/72070863/5784ea12-24b8-4f54-a5e0-f1daf4ebaeec)
[LSPosed_2023-12-18T04_08_49.923710.zip](https://github.com/ReChronoRain/HyperCeiler/files/13697663/LSPosed_2023-12-18T04_08_49.923710.zip)

**Comment by Ianzb** [comment]
我这边也是，机型k60

**Comment by Sevtinge** [comment]
在最新canary中验证更改
