### ISSUE TITLE
💡 [需求] 解锁 HyperOS 互联 root 限制

### ISSUE THREAD

**Issue by TomyJan** [ReChronoRain/HyperCeiler#173]
### 需求内容

今天刚推小米平板的 HyperOS 开发版, 升级后尝试连接, 如下报错

![image](https://github.com/ReChronoRain/HyperCeiler/assets/67973160/acd3a78e-fe29-4ced-9332-4ba00d58ab4b)

希望能找到办法解除限制

(如果开发大大没有设备调试可以远程我, TG 同名

### 简单例子

emm

**Comment by HChenX** [comment]
自己隐藏root

**Comment by HChenX** [comment]
尝试最新的ci版本

**Comment by TomyJan** [comment]
> 尝试最新的ci版本

之前我是通过冻结 trust service 解决的, 试了下模块现在确实有用了, 感谢
