### ISSUE TITLE
🐛 [BUG] <双击空白处锁屏没有效果>

### ISSUE THREAD

**Issue by BruceWayne0522** [ReChronoRain/HyperCeiler#177]
### 问题描述

双击空白处锁屏没有用，其他正常，不知道是不是红米k50澎湃os与澎湃西米露可能不太适配

### 模块日志

0

### 复现步骤

```bash
1. 前往 '锁屏'
2. 点击 '双击空白处锁屏'

....
出现问题:无效果
```

### 问题截图

![图片注释](图片链接)

### 机型

红米K50

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133-20231211

**Comment by charles7580** [comment]
是的，同样的情况。

机型
小米13

MIUI/HyperOS 版本
Xiaomi HyperOS 1.0.23.12.18.DEV

Android 版本
Android 14

HyperCeiler 版本
2.3.135_20231231 | beta

**Comment by HChenX** [comment]
无日志

**Comment by oznll** [comment]
一样的问题，哎，因为这个退回到miui11养老了，什么时候修复什么时候用澎拜

**Comment by oznll** [comment]
破案了，它那个双击空白处锁屏是没用的，要在“导航”→“手势”→“双击”那里设置，是没问题的，小米10u澎湃os可用。
