### ISSUE TITLE
🐛 [BUG] <耳机图标隐藏无效>

### ISSUE THREAD

**Issue by ZYong9908** [ReChronoRain/HyperCeiler#188]
### 问题描述

系统界面->状态栏->图标->状态图标->耳机
设为始终隐藏，连接蓝牙耳机，重启系统界面生效，断掉耳机重连后图标又出现

### 模块日志

无

### 复现步骤

```bash
1. 前往 '系统界面->状态栏->图标->状态图标->耳机'
2. 点击 '始终隐藏'
系统界面->状态栏->图标->状态图标->耳机
设为始终隐藏，连接蓝牙耳机，重启系统界面生效，断掉耳机重连后图标又出现
```

### 问题截图

![图片注释](图片链接)

### 机型

readmi k60

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231211|beta

**Comment by mu7220** [comment]
经过长期测试，隐藏耳机图标这个官方自己本身写的有问题，可能没办法完全隐藏
等后续看看能不能整
