### ISSUE TITLE
🐛 [BUG] <真九宫格启动bug>

### ISSUE THREAD

**Issue by junguoqianshan** [ReChronoRain/HyperCeiler#190]
### 问题描述

打开真九宫格功能后，点击大文件夹第九个APP图标不启动第九个APP而是打开文件夹

### 模块日志

[LSPosed_2023-12-18T10_31_11.837997.zip](https://github.com/ReChronoRain/HyperCeiler/files/13698932/LSPosed_2023-12-18T10_31_11.837997.zip)

### 复现步骤

```bash
1. 前往 桌面
2. 点击 大文件夹第九个APP图标

....
出现问题
```

### 问题截图

![录屏](

Uploading Screenrecorder-2023-12-18-10-24-32-112_0_COMPRESSED.mp4…

)

### 机型

Xiaomi14

### MIUI/HyperOS 版本

其它

### Android 版本

Android 14

### HyperCeiler 版本

1.0.23.12.13.DEV

**Comment by junguoqianshan** [comment]
![Video_20231218_103838_119](https://github.com/ReChronoRain/HyperCeiler/assets/94796625/2f3a8b31-bf7c-45e0-a878-fc8c527b8761)

**Comment by junguoqianshan** [comment]
![Uploading Video_20231218_103838_119.gif…]()

**Comment by HChenX** [comment]
建议关闭功能，或者更换桌面版本
