### ISSUE TITLE
🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by 754950416** [ReChronoRain/HyperCeiler#191]
### 问题描述

抽屉模式，开模糊，在抽屉里面冷启动会100%重启桌面。关闭模糊则正常

### 模块日志

[1702870883747LSPosed_2023-12-18T11_40_19.135059.zip](https://github.com/ReChronoRain/HyperCeiler/files/13699233/1702870883747LSPosed_2023-12-18T11_40_19.135059.zip)

### 复现步骤

```bash
抽屉模式，开模糊，在抽屉里面冷启动会直接退出软件回到桌面，100%重启桌面。
```

### 问题截图

![图片注释](图片链接)

https://github.com/ReChronoRain/HyperCeiler/assets/144997882/95f3635f-66ea-42f1-86fa-c4000d0f35fb

### 机型

小米14

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231216_ae9bc63a

**Comment by Sevtinge** [comment]
使用「系统模糊」而非「原生模糊」

**Comment by 754950416** [comment]
![e7a4da257dc2f95e5f2c5f22253f680](https://github.com/ReChronoRain/HyperCeiler/assets/144997882/851a6521-fc24-43b6-a8f2-62877f1e3515)
1.  系统模糊和原生模糊只在dock的选项里找到可以设置的
2. 我没有开dock这个设置
3. 后来试了下即使在这里设为系统模糊，问题也还是存在
