### ISSUE TITLE
隐藏手势提示线导致输入法下面的快捷工具按钮位置偏下

### ISSUE THREAD

**Issue by luchuanbaker** [ReChronoRain/HyperCeiler#193]
### 问题描述

隐藏手势提示线后，全面屏键盘优化的多功能键盘功能键位置偏下，偏下以后功能键的位置其实是和全面屏手势提示线的识别区域重叠，导致功能键点击的识别率会降低。
系统默认隐藏手势线是正常的，但是就不能直接左右滑动切换app了。
下面发对照图
![IMG_20231218_214556](https://github.com/ReChronoRain/HyperCeiler/assets/6761331/9814f52d-e552-4785-881f-06998e2e619d)
![IMG_20231218_214437](https://github.com/ReChronoRain/HyperCeiler/assets/6761331/8f8639e7-51e0-4cff-8f2f-324e58e613c0)

### 模块日志

软件没有崩溃。

### 复现步骤

```bash
打开西米露，系统界面，导航栏，打开“隐藏手势提示线”，根据提示重启“系统界面”和“系统桌面”，随便找一个输入框，点击弹出输入法（确保没有关闭MIUI默认打开的全面屏键盘优化）。
```

### 问题截图

![图片注释](图片链接)
![IMG_20231218_214556](https://github.com/ReChronoRain/HyperCeiler/assets/6761331/7f15385d-8bb2-404d-98c7-b2d811bae54c)
![IMG_20231218_214437](https://github.com/ReChronoRain/HyperCeiler/assets/6761331/36d1498e-9d12-4180-97ed-0d7e60d9640f)

### 机型

红米note11tpro

### MIUI/HyperOS 版本

MIUI13

### Android 版本

Android 12

### HyperCeiler 版本

1.3.130_20231101

**Comment by Sevtinge** [comment]
这个问题得去问Google和小米了，我不负责给小米擦屁股
