### ISSUE TITLE
🐛 [BUG] 解锁大音量模式无效果

### ISSUE THREAD

**Issue by huoyan1231** [ReChronoRain/HyperCeiler#194]
### 问题描述

开启后无实际效果

### 模块日志

[LSPosed_2023-12-19T05_49_57.326094.zip](https://github.com/ReChronoRain/HyperCeiler/files/13708871/LSPosed_2023-12-19T05_49_57.326094.zip)

### 机型

k60

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231218

**Comment by mu7220** [comment]
正常，解锁只是UI层级，功能可用需要底层支持
到目前也就只有 note13 系列支持这个功能
