### ISSUE TITLE
🐛 [BUG] <抽屉模式，双击桌面>

### ISSUE THREAD

**Issue by 754950416** [ReChronoRain/HyperCeiler#200]
### 问题描述

抽屉模式，双击桌面设为锁屏，在页面指示器下方双击，无效；也就是图片的红色区域

### 模块日志

[LSPosed_2023-12-20T14_16_19.218602.zip](https://github.com/ReChronoRain/HyperCeiler/files/13723718/LSPosed_2023-12-20T14_16_19.218602.zip)

### 复现步骤

```bash
1. 抽屉模式
2. 双击桌面设为锁屏
3. 在页面指示器下方双击，无效；也就是图片的红色区域
```

### 问题截图

![1703052792984](https://github.com/ReChronoRain/HyperCeiler/assets/144997882/d08e84d8-11cf-4b3b-b9e4-114d191bbc61)

### 机型

小米14

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231220_f6a8c8f1

**Comment by Sevtinge** [comment]
这里的动作区域为dock栏
