### ISSUE TITLE
🐛 [BUG] 音量调节界面画面错位

### ISSUE THREAD

**Issue by Ptilopsis01** [ReChronoRain/HyperCeiler#205]
### 问题描述

音量调节界面的画面出现错位，不过不能完全确定是hyper自身的问题还是模块的问题

### 模块日志

[LSPosed_2023-12-23T00_33_09.898597.zip](https://github.com/ReChronoRain/HyperCeiler/files/13754332/LSPosed_2023-12-23T00_33_09.898597.zip)

### 复现步骤

```bash
1. 侧键调节音量
2. 点击右侧三点展开分别调节的界面

....
出现问题
```

### 问题截图

![屏幕截图 2023-12-09 181954](https://github.com/ReChronoRain/HyperCeiler/assets/93318731/7c5ae7c6-98d3-4b37-be2f-6499bf8f0703)

### 机型

Xiaomi 12S

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231211 beta

**Comment by Sevtinge** [comment]
使用「设置-声音与触感-更多声音设置-通知音量控制」![Screenshot_2023-12-26-16-20-03-860_com.android.settings-edit.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/89193494/f906064b-865a-4b7d-b2a3-c437099d3d99)

**Comment by Sevtinge** [comment]
后续会屏蔽此功能
