### ISSUE TITLE
🐛 [BUG] <通知与控制中心的磁贴开关无法生效>

### ISSUE THREAD

**Issue by yyk725** [ReChronoRain/HyperCeiler#210]
### 问题描述

系统界面-通知与控制中心-磁贴中，gms开关、5g开关、阳光模式三项功能均无法正常工作（已添加和未添加的快捷开关中都无法找到这些开关）。这三项功能在同手机同系统的Cemiuiler1.3.130中均正常工作

### 模块日志

[LSPosed_2023-12-24T19_14_13.013886.zip](https://github.com/ReChronoRain/HyperCeiler/files/13761578/LSPosed_2023-12-24T19_14_13.013886.zip)

### 机型

Redmi K70

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231223_0a5866e7

**Comment by HChenX** [comment]
回退到 补全磁贴列表 之前，目测冲突

**Comment by yyk725** [comment]
发现问题了，因为之前一直在用米客向控制中心添加刷新率显示磁贴，但是不知道为何从cemiuiler更换到hyperceiler后，米客和hyperceiler向控制中心添加的磁贴会发生冲突(而且是hyperceiler的磁贴无法显示)😅

如果能将显示刷新率的功能整合进hyperceiler就好了
