### ISSUE TITLE
🔌 [移植] <米客的刷新频率磁贴>

### ISSUE THREAD

**Issue by yyk725** [ReChronoRain/HyperCeiler#211]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

希望可以移植米客的刷新频率磁贴功能

### 相关描述&截图

![1703429329416](https://github.com/ReChronoRain/HyperCeiler/assets/72236930/d34adc5e-f2ed-4ebd-a80c-6bd0d0f383f4)

**Comment by Sevtinge** [comment]
短期没计划做
