### ISSUE TITLE
🐛 [BUG] <重定向通知设置无法生效>

### ISSUE THREAD

**Issue by yyk725** [ReChronoRain/HyperCeiler#214]
### 问题描述

系统界面-通知与控制中心-重定向通知设置无法跳转到子频道设置，并且已排除了与其他模块的冲突

### 模块日志

[LSPosed_2023-12-25T16_18_10.957401.zip](https://github.com/ReChronoRain/HyperCeiler/files/13765043/LSPosed_2023-12-25T16_18_10.957401.zip)

### 复现步骤

```bash
1. 在hyperceiler打开 '重定向通知设置'
2. 打开通知中心，随意长按某条通知并点击 '更多设置'
```

### 问题截图

https://github.com/ReChronoRain/HyperCeiler/assets/72236930/88f264b2-d6d1-441a-8a7b-1437758dce15

### 机型

Redmi K70

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.134_20231225_353a12c6

**Comment by mu7220** [comment]
已在新版修复
