### ISSUE TITLE
🐛 [BUG] 打开”安全模式“里的“系统界面”，飞鸽传书（6.1.200622）就打不开了

### ISSUE THREAD

**Issue by 695975525** [ReChronoRain/HyperCeiler#216]
### 问题描述

打开”安全模式“里的“系统界面”，飞鸽传书（6.1.200622）就打不开了，卡在启动页面，还有自己公司的一个app也是一个现象

### 模块日志

没找到日志

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

k40

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133-20231211

**Comment by Sevtinge** [comment]
安全模式里的作用域开启后将不会在对应作用域hook，目测为第三方app开发不规范所致

**Comment by 695975525** [comment]
曲线救国，先在模块里开启安全模式，打开里面所有选项再重启手机，开机之后老app都能运行了，然后再到hyperceiler模块里关闭安全模式里的选项，重启所有作用域就OK了，但是下次重启要一样的操作，不然还是一样打不开app了，应该是适配的问题。再次感谢大佬..

**Comment by 695975525** [comment]
我应该是描述错问题了，模块开启手机重启后，飞鸽传书等一些老app就不能正常打开了，必须把安全模式里的选项打开再重启手机，这些APP才能正常打开；
目前的方法就是先把安全模式打开再重启手机，这时候这些老APP就都能打开了，再进入模块设置里关闭安全模式，重启作用域，这样APP和模块都能正常运行了，问题就是不开安全模式重启手机后，这些老APP又会打不开

**Comment by Sevtinge** [comment]
确定是开发不规范导致的了，建议敦促一下那边的开发者
