### ISSUE TITLE
🐛 [BUG] 启用隐藏手势提示线后，横屏二次确认失效

### ISSUE THREAD

**Issue by 0XPYEX0** [ReChronoRain/HyperCeiler#221]
### 问题描述

如题
我觉得要不直接甩俩个视频比较直观

https://github.com/ReChronoRain/HyperCeiler/assets/50171612/75995b4c-ce13-4faa-ac81-4e2ed790fa68
↑这是尚未启用功能

https://github.com/ReChronoRain/HyperCeiler/assets/50171612/6a28f8c1-e558-4aa7-b8bf-2732039d721d
↑这是启用功能后
(分段是因为重启应用域后录屏就录不到了)

带来的影响大概是玩游戏误触划到桌面()

### 模块日志

[LSPosed_2023-12-26T23_49_39.601604.zip](https://github.com/ReChronoRain/HyperCeiler/files/13772445/LSPosed_2023-12-26T23_49_39.601604.zip)

### 复现步骤

```bash
1. 启用“隐藏手势提示线”功能(下称隐藏)
2. 启用“手势二次滑动确认” (下称确认)
3. “确认”功能失效，无需确认就触发全面屏手势
```

### 问题截图

详见上方视频

### HyperCeiler 设备信息

![Screenshot_2023-12-26-23-51-54-544_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50171612/bcbeb6af-b39f-48d8-9e08-06a884072aac)

**Comment by 0XPYEX0** [comment]
可以参考这个repo的实现()
用了他一切正常
这一定是致敬(划掉)

https://github.com/a709560839/HideNavBar

**Comment by HChenX** [comment]
再试试？
