### ISSUE TITLE
🐛 [BUG] <USB数据线插入后弹窗、"应用信息"弹窗等弹窗无法弹出>

### ISSUE THREAD

**Issue by zhangweildlh** [ReChronoRain/HyperCeiler#233]
### 问题描述

HyperCeiler v2.3.134_20231228，小米手机Redmi Note12Turbo 官方稳定版ROM v14.0.25.0.TMRCNXM，Magisk v26.4，LSPosed v1.9.2(7024)-Zygisk；面具模块Shamiko v0.7.4(188)生效，面具使用了更改APP名称 隐藏。HyperCeiler已勾选所有需要的作用域。
【问题】HyperCeiler生效后，USB数据线插入后的弹窗、长按桌面APP图标弹出菜单中选择"应用信息"后的弹窗，都无法正常弹出。
导致，无法选择USB”传输文件“，无法查看APP的应用信息。

### 模块日志

[LSPosed_2023-12-30T18_21_23.466614.zip](https://github.com/ReChronoRain/HyperCeiler/files/13797810/LSPosed_2023-12-30T18_21_23.466614.zip)
[LSPosed_2023-12-30T18_21_32.721187.zip](https://github.com/ReChronoRain/HyperCeiler/files/13797811/LSPosed_2023-12-30T18_21_32.721187.zip)

### 复现步骤

```bash
1. 插入USB数据线，无任何弹窗(原本应弹出“USB用于”的弹窗)
2. 长按任一APP图标，在弹出菜单中选择"应用信息"，无任何弹窗(原本应弹出“APP信息”的弹窗)
```

### 问题截图

[https://tiebapic.baidu.com/tieba/pic/item/78310a55b319ebc4a215e2aec426cffc1e171693.jpg?tbpicau=2024-01-01-05_74f42d11f5301282486bedff3647337b](url)
[https://tiebapic.baidu.com/tieba/pic/item/faedab64034f78f0f8660ec43f310a55b3191c93.jpg?tbpicau=2024-01-01-05_85c94a39f497ed2e55e42ea7076c5e48](url)

### HyperCeiler 设备信息

[https://tiebapic.baidu.com/tieba/pic/item/aec379310a55b319ff94164205a98226cffc1793.jpg?tbpicau=2024-01-01-05_975ac22129dfbae97b17273f5acab0b0](url)

调试信息
Debug Info by HyperCeiler

VersionName = 2.3.134 20231228
VersionCode = 134
Bui1 dTime = (UTC+0:00)2023-12-28
14:21:26
BuildType = beta 
GitHash =
83c5426d1fd5d22e87ef094748478a0c905f7cdc
Debug = false
ApplicationId = com.sevtinge.hyperceiler

Device = marble
Model = 23049RAD8C
Brand = Redmi
Manufacture = Xiaomi
Board = marble
Soc = taro
FingerPrint = Redmi/marble/marble:13/
TKQ1.221114.001/V14.0.25.0.TMRCNXM:user/
release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = 094c8da955bd0529
Seria.1 = 208b0638

AndroidVersion = 33
MiuiVersion = 14.0
HyperosVersion = 0.0
SystemVersion = V14.0.25.0.TMRCNXM
Builder = builder
RomAuthor = 
Base0s = 
Host = pangu-build-component-system-3850
18-12xws-txxcg-9x3bp
BuildDate = Wed Oct 11 02:28:32 UTC 2023

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:2
8:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF
:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true

**Comment by zhangweildlh** [comment]
[Uploading LSPosed_2023-12-30T18_21_32.721187.zip…]()

**Comment by zhangweildlh** [comment]
[Uploading LSPosed_2023-12-30T18_21_23.466614.zip…]()

**Comment by HChenX** [comment]
卸载重装hypercelier
