### ISSUE TITLE
🐛 [BUG] <Telegram、QQ 选中输入框内文字会闪退>

### ISSUE THREAD

**Issue by System-Warning** [ReChronoRain/HyperCeiler#235]
### 问题描述

选中Telegram、QQ的输入框的内容会闪退。
目前只发现这俩个软件有异常，微信，chrome等软件正常。
确定是模块导致的，不改变其他任何设置，在LSposed中禁用模块，重启，恢复正常。

### 模块日志

- LSPosed管理器 - 日志：[LSPosed_2024-01-01T03_18_19.437639.zip](https://github.com/ReChronoRain/HyperCeiler/files/13802081/LSPosed_2024-01-01T03_18_19.437639.zip)

- HyperCeiler 配置文件：[HyperCeiler_settings_backup_2024-01-01-02_53_31.json](https://github.com/ReChronoRain/HyperCeiler/files/13802087/HyperCeiler_settings_backup_2024-01-01-02_53_31.json)

### 复现步骤

```bash
1.进入Telegram或者QQ
2.在输入框输入任意内容
3.长按选中
4.闪退
```

### 问题截图

https://github.com/ReChronoRain/HyperCeiler/assets/51915931/5ee8954a-1d1f-476d-b7e2-ba150946f02d

### HyperCeiler 设备信息

![Screenshot_2024-01-01-03-23-05-202_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/51915931/a4fd9141-8e25-4996-a294-df1f9d1186e2)

**Comment by System-Warning** [comment]
将模块配置重置，重启，之后不会闪退。
应该是某个设置的问题，尝试修改了一些设置，但没有找到是哪个设置引起的。
如果您近期不打算修复这个bug，恳请您告诉我是哪个设置导致这个问题的🙏。

**Comment by HChenX** [comment]
我们不会算卦，还请自行排查，估计和剪贴板一类的东西有关
