### ISSUE TITLE
🐛 [BUG] 音量百分比背景出现问题

### ISSUE THREAD

**Issue by huoyan1231** [ReChronoRain/HyperCeiler#237]
### 问题描述

音量百分比背景错误

### 模块日志

[LSPosed_2024-01-01T17_30_18.788993.zip](https://github.com/ReChronoRain/HyperCeiler/files/13804101/LSPosed_2024-01-01T17_30_18.788993.zip)

### 复现步骤

```bash
偶发性问题
重启系统界面可以暂时恢复正常行为
```

### 问题截图

![Screenshot_2024-01-01-17-28-26-281_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/53113734/d22516de-d5db-42d4-8f7e-288c01aa73e4)

### HyperCeiler 设备信息

![Screenshot_2024-01-01-17-32-01-143_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/53113734/11622169-f253-47a9-8a3a-4f7765391042)

**Comment by Sevtinge** [comment]
重启系统界面或等待后续版本，系打包资源值问题
