### ISSUE TITLE
💡 [需求] <建议把开关样式同步为HyperOS同款>

### ISSUE THREAD

**Issue by jyfyge** [ReChronoRain/HyperCeiler#238]
### 需求内容

既然已经把底栏风格同步为HyperOS同款了，干脆把按钮也同步一下呗，感觉HyperOS的更好看

### 实现思路&截图

![IMG_20240101_213218](https://github.com/ReChronoRain/HyperCeiler/assets/86462294/f979393a-5758-42b0-b31f-be00c3b148ec)
上方为Hyperceiler目前开关风格，是MIUI时期同款
下方为HyperOS风格

### 简单例子

.

**Comment by HChenX** [comment]
等ui更新吧
