### ISSUE TITLE
🐛 [BUG] 小米云服务闪退

### ISSUE THREAD

**Issue by axelpln** [ReChronoRain/HyperCeiler#240]
### 问题描述

小米设置进入云服务闪退

### 模块日志

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 23049RAD8C
[Display]: TKQ1.221114.001 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 16544
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.miui.cloudservice
[Version Name]: 1.12.0.1.70
[Version Code]: 112000170
[Target SDK]: 33
[Min SDK]: 23
[Error Type]: JVM
[Crash Time]: 2024-01-02T15:24:54.665
[Stack Trace]:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.UnsupportedOperationException
	at b.a.engineGetCertificateChain(SourceFile:2)
	at java.security.KeyStore.getCertificateChain(KeyStore.java:1108)
	at m4.a.b(SourceFile:2)
	at m4.d$a.b(Unknown Source:4)
	at g4.b.f(SourceFile:4)
	at g4.b.e(SourceFile:2)
	at g2.f$c.a(Unknown Source:2)
	at d2.a.c(SourceFile:3)
	at h2.a.a(SourceFile:1)
	at h2.a.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

[LSPosed_2024-01-02T15_29_51.385719.zip](https://github.com/ReChronoRain/HyperCeiler/files/13807894/LSPosed_2024-01-02T15_29_51.385719.zip)

### 复现步骤

```bash
1. 前往 '设置'
2. 点击 '小米账号'
3. 点击 '云服务'
出现问题
```

### 问题截图

![Screenshot_2024-01-02-15-28-26-274_com fankes apperrorstracking](https://github.com/ReChronoRain/HyperCeiler/assets/54173955/9795a2b9-24d6-418f-ae3f-60df7ca6ed97)

### HyperCeiler 设备信息

![Screenshot_2024-01-02-15-27-36-726_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/54173955/a58c2fc5-968c-402b-86c6-78303a04fe02)

**Comment by HChenX** [comment]
我看到了其他模块对小米云进行Hook，检查其他模块

**Comment by axelpln** [comment]
> 我看到了其他模块对小米云进行Hook，检查其他模块

你好，我检查了一下我的模块列表，除了 HyperCeiler 没有模块再作用小米云服务。虽然我后面检查到隐藏应用列表对云服务开启了隐藏，但是关掉后问题依旧。

**Comment by axelpln** [comment]
> 我看到了其他模块对小米云进行Hook，检查其他模块

因为我的平板6pro之前也有这个问题（加载的模块和手机基本一致，甚至更少），但在升级到澎湃后这个问题就不再出现，所以我想是不是 HyperCeiler 逐渐放弃了对 MIUI14 的兼容？

**Comment by axelpln** [comment]
> ![image](https://private-user-images.githubusercontent.com/123531821/293722126-e1034b70-45b7-473e-accc-432b4b3e9ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTcwMzMsIm5iZiI6MTcwNDI1NjczMywicGF0aCI6Ii8xMjM1MzE4MjEvMjkzNzIyMTI2LWUxMDM0YjcwLTQ1YjctNDczZS1hY2NjLTQzMmI0YjNlOWViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNDM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGRkMWU3MDg4NTgwNGI3Y2U4MWZlMWViNGVkYjFiOWVlYTZlNGI5MzhiZmQyOTdhYmIwYmY4YWFkNWRmZjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.liVJ5acyFHL3DVY-mTQERvyODF6epkJBGw1DB8MiAqs) [ 2024-01-02T15:21:03.770 1000: 2832: 3867 I/LSPosed-Bridge ] [ INFO] 01-02 15:21:03 (PmsHookTarget33) @shouldFilterApplication: query from com.miui.cloudservice （这里） [ 2024-01-02T15:21:03.836 10143: 12350: 16297 I/LSPosed-Bridge ] Crash unexpectedly: java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$4.done(AsyncTask.java:415) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381) at java.util.concurrent.FutureTask.setException(FutureTask.java:250) at java.util.concurrent.FutureTask.run(FutureTask.java:269) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012) Caused by: java.lang.UnsupportedOperationException at b.a.engineGetCertificateChain(SourceFile:2) at java.security.KeyStore.getCertificateChain(KeyStore.java:1108) at m4.a.b(SourceFile:2) at m4.d$a.b(Unknown Source:4) at g4.b.f(SourceFile:4) at g4.b.e(SourceFile:2) at g2.f$c.a(Unknown Source:2) at d2.a.c(SourceFile:3) at h2.a.a(SourceFile:1) at h2.a.doInBackground(Unknown Source:2) at android.os.AsyncTask$3.call(AsyncTask.java:394) at java.util.concurrent.FutureTask.run(FutureTask.java:264) ... 3 more 这个日志不属于hypercelier，自己检查

你好，找到问题了，不是任何lsp模块引起的，而是safetynet-fix这个模块导致的。说来也奇怪，我用的ksu默认开启卸载模块，正常情况下不应被影响才对。只是现在没法隐藏bl状态了。
