### ISSUE TITLE
💡 手机管家取消adb安装二次确认对话框

### ISSUE THREAD

**Issue by sbmatch** [ReChronoRain/HyperCeiler#242]
### 需求内容

手机管家取消adb安装二次确认对话框

### 实现思路&截图

/data/user/0/com.miui.securitycenter/shared_prefs/remote_provider_preferences.xml  permcenter_install_intercept_enabled 的值为false 即可

### 简单例子

hook cb.a 类 t() 方法 使其返回false 即可

**Comment by HChenX** [comment]
接了
