### ISSUE TITLE
🐛 [BUG] <pad移除顶部快捷窗口按钮导致DOC栏滑动手势失效>

### ISSUE THREAD

**Issue by 2103894869** [ReChronoRain/HyperCeiler#245]
### 问题描述

如题
开启 系统框架-其他-隐藏快捷窗口按钮 选项后
DOCK栏拖动开启小窗及分屏的功能失效
![8f6417763d36fa6032f7437886348b96](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/48346f3a-c16d-48c2-8815-349161b88fc9)
![495f6c9c4537c45f21e44a5db8bcb318](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/5dba57b9-33e1-4cbb-ba78-b49f725d6cdd)
小窗贴顶边全屏和拖动分屏的功能失效
![cf84f9432a6c35b1fcbfb6515e38cc68](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/6ebf50fb-84b3-4371-a473-75db20c3cec3)
从分屏退到全屏和交换分屏的功能失效
![a1974f7e3713cd18df6814a93ce3be86](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/f0db6ab2-d96f-4eb8-bcba-a4851a3d4a9f)
![84f34dfd22c820976d3e20ac0a20d8e7](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/17d68890-278d-480b-899e-75b17b4a965b)

如果可以实现的话希望后期这项功能可以改为只移除全屏应用的快捷按钮，保留小窗和分屏的

### 模块日志

[LSPosed_2024-01-03T22_09_54.902382.zip](https://github.com/ReChronoRain/HyperCeiler/files/13819955/LSPosed_2024-01-03T22_09_54.902382.zip)

### 复现步骤

```bash
开启 系统框架-其他-隐藏快捷窗口按钮 选项
```

### 问题截图

开了之后DOCK栏拖不出来力
窗口拖动没有分屏和全屏贴靠了
![0e7cffdf1bed3c96c8502ff0596b5b7e](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/29c9f7d9-3161-4e12-9b7f-1e3c57fe251b)
![d4a5788c5f56127ba49b77764641b07b](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/c2635fec-92cd-4ce0-a9fb-0a669b8508c0)

### HyperCeiler 设备信息

![2c7922c249ccf255ddd44cb5c8342547](https://github.com/ReChronoRain/HyperCeiler/assets/74134388/d2121561-7858-4cd2-9a89-fa985f6453eb)

**Comment by mu7220** [comment]
鄙人无 Pad，所以暂时只能这样，要完善等sevtinge 上 hyperOS 了再说

**Comment by 2103894869** [comment]
行，那就等漓妈忙完hyper手机端再说
