### ISSUE TITLE
💡 [需求] 状态栏上隐藏静音通知

### ISSUE THREAD

**Issue by siilm** [ReChronoRain/HyperCeiler#246]
### 需求内容

原生设置内有一项是把静音通知从状态栏隐藏（比如scene、clash之类）打开通知栏依然可见，hyperos里即便调出原生设置打开开关也无效了，希望可以在这里实现。

### 简单例子

1

**Comment by mu7220** [comment]
现在使用 设置-显示更多通知设置项 这个功能对通知重要程度进行设置即可
目前 hyperOS 只能通过更改通知重要程度进行设置

**Comment by siilm** [comment]
正是我要的效果，感谢
