### ISSUE TITLE
🔌 [移植] <米客的“右上滑动”/“左上滑动”将当前应用转为小窗>

### ISSUE THREAD

**Issue by charles7580** [ReChronoRain/HyperCeiler#248]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

目前HyperCeiler已支持“右上滑动”“左上滑动”触发部分动作（系统桌面-手势与导航-手势），但是缺少类似米客的“将当前应用转为小窗”的动作，希望能够移植该功能。该功能将极大地提高小窗的利用率和使用效率，感谢。

### 相关描述&截图

![微信图片_20240104085630](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/e90dc343-c4d1-438a-a129-51ca007681e5)

**Comment by az525456** [comment]
还可以添加，启动快捷方式
