### ISSUE TITLE
🐛 [BUG] <系统桌面-手势与导航-通过手势触发启动应用无效>

### ISSUE THREAD

**Issue by charles7580** [ReChronoRain/HyperCeiler#249]
### 问题描述

系统桌面-手势与导航 中，在选择指定的手势后，选择“启动应用”时，无法应用所选择的应用。

### 模块日志

未报错

### 复现步骤

```bash
1. 前往 '系统桌面'
2. 点击 '手势与导航'
3. 点击任意手势
4. 点击 '启动应用'
5. 点击 '选择应用'
6. 点击 '任意应用'

无法应用
```

### 问题截图

![微信图片_20240104090357](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/38148fc6-6460-4633-b9d1-67ff411dd83f)

### HyperCeiler 设备信息

![微信图片_20240104090446](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/21d583e6-6fef-425e-9601-f0edc35dd97e)

**Comment by HChenX** [comment]
已经修复
