### ISSUE TITLE
应用录音通知💡 [需求] <标题>

### ISSUE THREAD

**Issue by haizibuhaohong** [ReChronoRain/HyperCeiler#253]
### 需求内容

可否加个开关把这应用通话录音的通知关掉？澎湃os上设置里关不掉

### 实现思路&截图

![Screenshot_2024-01-04-10-46-35-333_com tencent mm](https://github.com/ReChronoRain/HyperCeiler/assets/105098243/f8c97c53-ca99-41b4-b85b-8cefc3a781d6)
![Screenshot_2024-01-04-10-46-44-595_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/105098243/8ea732e1-404c-448e-839c-97e5b07cd6cd)

### 简单例子

举个例子

**Comment by mu7220** [comment]
![Screenshot_2024-01-04-11-42-57-469_com.sevtinge.hyperceiler-edit.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/1f3dadad-f9be-4fa7-9a81-6755ad61152b)

亲

**Comment by haizibuhaohong** [comment]
不行啊，关闭后再次应用录音后又会显示同意
![Uploading Screenshot_2024-01-04-12-22-27-602_com.android.settings.jpg…]()

**Comment by HChenX** [comment]
不写
