### ISSUE TITLE
🐛 [BUG] <勾选隐藏锁屏的'相机'和‘负一屏’后不生效>

### ISSUE THREAD

**Issue by charles7580** [ReChronoRain/HyperCeiler#254]
### 问题描述

“系统界面”的“隐藏相机”和“隐藏负一屏”功能异常

### 模块日志

[LSPosed_2024-01-04T11_21_08.629337.zip](https://github.com/ReChronoRain/HyperCeiler/files/13825330/LSPosed_2024-01-04T11_21_08.629337.zip)

### 复现步骤

```bash
1. 前往 '系统界面'
2. 点击 '锁屏'
3. 点击 '隐藏相机'
4. 点击 '隐藏负一屏'
5. 重启系统界面
6. 进入锁屏

相机和负一屏图标依然存在
```

### 问题截图

![图片注释](图片链接)
![微信图片_20240104111931](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/e6e12efa-0328-4f6c-a771-abef7c383917)
![微信图片_20240104111935](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/47792631-6b91-4215-8836-58be23e08522)

### HyperCeiler 设备信息

![图片注释](图片链接)
![微信图片_20240104090446](https://github.com/ReChronoRain/HyperCeiler/assets/25521003/6f35af83-5aff-4db9-a884-d6b1700196d8)

**Comment by charles7580** [comment]
已确认是默认主题

**Comment by mu7220** [comment]
已修复
