### ISSUE TITLE
🐛 [BUG] <问题标题>使用模块后会出现短信、日历无提示，应用商店无法打开

### ISSUE THREAD

**Issue by DavidLdf** [ReChronoRain/HyperCeiler#258]
### 问题描述

小米10MIUI14.0.3使用模块后会出现新短信不会在状态提示，收到信息只能打开短信查看；日历提醒项无法在状态栏提示，且小部件不更新今日，一直保留昨日；应用商店无法打开，清除数据也无用

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by HChenX** [comment]
不知
