### ISSUE TITLE
🐛 [BUG] <功率显示不正常>

### ISSUE THREAD

**Issue by Alpha-Qian** [ReChronoRain/HyperCeiler#259]
### 问题描述

1mA的充电功率
状态栏功耗永远是0W0mA

### 模块日志

[LSPosed_2024-01-05T12_37_01.946847.zip](https://github.com/ReChronoRain/HyperCeiler/files/13838014/LSPosed_2024-01-05T12_37_01.946847.zip)

### 复现步骤

```bash
打开锁屏充电功率显示和状态栏功耗显示
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-01-05-12-26-51-681_lockscreen](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/85bd0afa-ebd5-4d2e-a93f-76ed96f27fee)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-01-05-12-34-14-890_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/9ffcf528-01eb-4349-a0b6-ca3c2143f26d)

**Comment by mu7220** [comment]
复现不出，确定不是你自己充电设备有问题？

**Comment by Alpha-Qian** [comment]
> 复现不出，确定不是你自己充电设备有问题？

绝对不是，有时候会显示0.1ma,0.01w或0.02w，看着像是实际电流乘了个小数（0.01 ？）

**Comment by Alpha-Qian** [comment]
> 复现不出，确定不是你自己充电设备有问题？

绝对不是，有时候会显示0.1ma,0.01w或0.02w，看着像是实际电流乘了个小数（0.01 ？）
