### ISSUE TITLE
控制中心“极暗”快捷开关图标缩放不协调

### ISSUE THREAD

**Issue by jcjyids** [ReChronoRain/HyperCeiler#260]
### 问题描述

在APP内添加“极暗”开关到控制中心，显示的图标大于其他图标

同时调整了：
    状态栏：
        电池图标字体
        数据信号图标（双层）
        显示通知的app个数
        网络状态（双层上传下载）
    控制中心：
        卡片磁铁数量（多）
        圆角矩形磁贴（未修改此项问题依然）
    通知；
        显示天气

### 模块日志

附模块配置：
[HyperCeiler_settings_backup_2024-01-06-03_54_54.json](https://github.com/ReChronoRain/HyperCeiler/files/13846007/HyperCeiler_settings_backup_2024-01-06-03_54_54.json)

### 问题截图

![Screenshot_2024-01-06-01-30-40-368_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/74102874/08043e64-5fd1-42df-a7c4-d7a39160cac2)

### HyperCeiler 设备信息

![Screenshot_2024-01-06-03-44-34-547_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/74102874/12491ed8-983e-47b7-a553-affa9c94144f)

**Comment by TjXySky** [comment]
我的控制中心都不能显示极暗
