### ISSUE TITLE
🐛 [BUG] 修改电话服务后系统应用申请root权限

### ISSUE THREAD

**Issue by Alpha-Qian** [ReChronoRain/HyperCeiler#264]
### 问题描述

没有插入副卡，插入副卡后能否复现未经测试
![Screenshot_2023-12-09-07-34-15-215_io github huskydg magisk](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/deb5fb93-f619-473f-9601-2a5d521e0fb4)
![Screenshot_2024-01-05-16-53-36-826_io github huskydg magisk](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/cbe5a336-d236-4203-89ae-737afdb652b2)
![Screenshot_2024-01-05-16-54-00-899_io github huskydg magisk](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/aa9be4ce-4517-4d26-9feb-e777452824c4)

### 模块日志

[LSPosed_2024-01-05T16_55_52.715655.zip](https://github.com/ReChronoRain/HyperCeiler/files/13850114/LSPosed_2024-01-05T16_55_52.715655.zip)

### 复现步骤

```bash
打开电话服务-副卡VoLTE通话可连网
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-01-05-12-34-14-890_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/154665575/e63c2931-cdf1-453d-8a58-2b0d20369cfb)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by HChenX** [comment]
正常，请授予
