### ISSUE TITLE
🐛 [BUG] <问题标题>手机管家在自定义侧边栏后，使用游戏工具箱闪退

### ISSUE THREAD

**Issue by FlowerLing** [ReChronoRain/HyperCeiler#266]
### 问题描述

k60pro在开启侧边栏自定义，且开启游戏工具箱的情况下，游戏界面滑动唤出侧边栏会导致闪退，关闭游戏工具箱可以唤出普通侧边栏。（同学的小米14可以自定义并在游戏工具箱模式下正常唤出）

### 模块日志

![软件崩溃日志](https://github.com/ReChronoRain/HyperCeiler/assets/109277072/80830b40-ce7c-4a12-aeb5-4f73d7cfddb8)

### 复现步骤

```bash
打开侧边栏自定义，即使什么也不调
打开手机管家→游戏加速→游戏工具箱
进入游戏滑动侧边栏
手机管家崩溃

关闭游戏工具箱
进入游戏滑动侧边栏
唤出普通侧边栏
```

### 问题截图

![开启侧边栏自定义，开启游戏工具箱唤出侧边栏](https://github.com/ReChronoRain/HyperCeiler/assets/109277072/4580609c-2319-46a8-9985-582dc151fc3b)
![开启侧边栏自定义，关闭游戏工具箱唤出侧边栏](https://github.com/ReChronoRain/HyperCeiler/assets/109277072/cb92fe9f-6329-4687-b0ec-3c878f6c5857)

### HyperCeiler 设备信息

![HyperCeiler 设备信息](https://github.com/ReChronoRain/HyperCeiler/assets/109277072/5db60b44-201a-42ea-bb9a-68193c1511ac)

**Comment by mu7220** [comment]
修改背景色为深色即可(即亮度拉低)
![Screenshot_2024-02-12-22-40-19-756_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/d5cfa501-70d7-480d-b544-3febe3ee8732)
