### ISSUE TITLE
🔌 [移植] 双排状态栏

### ISSUE THREAD

**Issue by Qwerto107** [ReChronoRain/HyperCeiler#268]
### 仓库地址

https://github.com/MonwF/customiuizer/blob/dd5c596044cd49f94da842d7b28dbe38b134531e/app/src/main/java/name/monwf/customiuizer/mods/SystemUI.java#L829

### 移植内容

希望可以支持双排状态栏
第一行：左侧时间，右侧指示图标
第二行：左侧通知图标，右侧电量

### 相关描述&截图

![01](https://github.com/ReChronoRain/HyperCeiler/assets/25398342/0ec69b52-e320-4bcf-bf8a-4a0e9f12c3d9)

**Comment by HChenX** [comment]
无计划
