### ISSUE TITLE
💡 [需求] <系统语言调整为英文、天气App语言单独调整为中文时，可以查看降水图等>

### ISSUE THREAD

**Issue by CoreyLu1104** [ReChronoRain/HyperCeiler#270]
### 需求内容

系统语言调整为英文、天气App语言单独调整为中文时，可以查看降水图等。

### 实现思路&截图

可能有用的参考：https://xanderc.top/2022/07/30/debug-mi-weather

### 简单例子

之前使用MIUI14并且未升级新版天气App时，可以在系统英文、天气App中文时，查看降水图等。
更新HyperOS并且升级新版天气App之后，不可查看降水图等。
将系统切换为英文，天气App设置为中文，再切换为系统中文，也无法查看降水图等，需要清除天气App的数据。
将天气App单独设置为中文是通过爱玩机工具箱实现的。
如果可以的话，希望在系统和天气App均为英文的情况下，也可查看降水图等。

**Comment by Vstory** [comment]
看了下原贴，很别扭。界面显示英文，搞个降雨和预警信息是中文。

**Comment by HChenX** [comment]
这是小米的问题，找小米而不是我们
