### ISSUE TITLE
平板平行世界设置锁定

### ISSUE THREAD

**Issue by sunjiazhenhao** [ReChronoRain/HyperCeiler#272]
### 需求内容

建议给平板加一个平行窗口选项锁定，重启不会恢复默认设置(有些应用无法使用平行世界，重启后必须重新关掉)

### 简单例子

像电池优化白名单的锁定一样

**Comment by sothx** [comment]
平行窗口的功能本身就不会重启后恢复默认设置，大概率是你装了什么模块导致的问题
