### ISSUE TITLE
🐛 [BUG] <小米 10 P 系统框架-显示-亮度-自动亮度范围灰色不可使用>

### ISSUE THREAD

**Issue by SouiRinn** [ReChronoRain/HyperCeiler#273]
### 问题描述

机型：小米10P
版本：MIUI 14.0.4
自动亮度范围灰色不可使用，重置数据及删除重新下载均显示灰色

### 模块日志

软件正常使用

### 问题截图

![new ducument](https://github.com/ReChronoRain/HyperCeiler/assets/130357756/874d785d-606e-45ef-95d1-659c78a88142)

**Comment by HChenX** [comment]
不完善，暂不开放
