### ISSUE TITLE
🐛 [BUG] hyperceiler导致的系统应用崩溃

### ISSUE THREAD

**Issue by NiuHK** [ReChronoRain/HyperCeiler#277]
### 问题描述

一觉起来就这样了（）
先是全面屏手势-返回桌面无法使用，magisk-》lsposed-》hypercelier调试出来发现是hypercelier的问题，并且排除是模块打架

重启后锁屏页面正常，系统桌面崩溃，进入设置部分设置选项崩溃，全面屏手势完全崩溃

尝试lsposed关闭hyperceiler并重启-有效
尝试hyperceiler安全模式全部勾选并重启-无效
尝试hyperceiler重置模块设置并重启-无效
尝试hyperceiler在应用信息中清除所有数据并重启-无效

现在解决是暂时先删掉了。。。

### 模块日志

[模块日志：LSPosed_2024-01-16T09_05_36.373110.zip](https://github.com/ReChronoRain/HyperCeiler/files/13944217/LSPosed_2024-01-16T09_05_36.373110.zip)
[详细日志：Detailed_LSPosed_2024-01-16T09_05_42.447848.zip](https://github.com/ReChronoRain/HyperCeiler/files/13944222/Detailed_LSPosed_2024-01-16T09_05_42.447848.zip)

### 复现步骤

```bash
不清楚，晚上听了会网易云，早晨起来就寄了
真就一觉起来就这样了
```

### HyperCeiler 设备信息

![84e81a38167738126e7a86c4752e4c7](https://github.com/ReChronoRain/HyperCeiler/assets/129147116/3a78de20-9020-4391-b0d6-2dae2c76a560)

**Comment by NiuHK** [comment]
加一条系统桌面的崩溃日志：
296 24896 24896 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 24896 (com.miui.home), pid 24896 (com.miui.home)
01-16 09:56:34.437 24943 24943 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-16 09:56:34.437 24943 24943 F DEBUG   : Build fingerprint: 'Xiaomi/fuxi_eea/fuxi:14/UKQ1.230804.001/V816.0.1.0.UMCEUXM:user/release-keys'
01-16 09:56:34.437 24943 24943 F DEBUG   : Revision: '0'
01-16 09:56:34.437 24943 24943 F DEBUG   : ABI: 'arm64'
01-16 09:56:34.437 24943 24943 F DEBUG   : Timestamp: 2024-01-16 09:56:34.329491819+0800
01-16 09:56:34.437 24943 24943 F DEBUG   : Process uptime: 2s
01-16 09:56:34.437 24943 24943 F DEBUG   : Cmdline: com.miui.home
01-16 09:56:34.437 24943 24943 F DEBUG   : pid: 24896, tid: 24896, name: com.miui.home  >>> com.miui.home <<<
01-16 09:56:34.437 24943 24943 F DEBUG   : uid: 10166
01-16 09:56:34.437 24943 24943 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
01-16 09:56:34.437 24943 24943 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
01-16 09:56:34.437 24943 24943 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000018
01-16 09:56:34.437 24943 24943 F DEBUG   : Cause: null pointer dereference
01-16 09:56:34.437 24943 24943 F DEBUG   :     x0  0000000000000000  x1  0000000071d83d30  x2  0000000000000001  x3  000000000000000a
01-16 09:56:34.437 24943 24943 F DEBUG   :     x4  0000000000000000  x5  0000000000000017  x6  0000000000000fad  x7  0000000000000018
01-16 09:56:34.438 24943 24943 F DEBUG   :     x8  0000000012f04a04  x9  0000000000000001  x10 0000000000000000  x11 0000000000000000
01-16 09:56:34.438 24943 24943 F DEBUG   :     x12 00000071d9e15000  x13 0000007285ebd000  x14 0000007fdb37b070  x15 0000000000000000
01-16 09:56:34.438 24943 24943 F DEBUG   :     x16 0000000000000002  x17 0000000a00000002  x18 0000007286674000  x19 b4000071dce42c00
01-16 09:56:34.438 24943 24943 F DEBUG   :     x20 0000000000000000  x21 b4000071dce42cc8  x22 000000007068e1a0  x23 000000007088b400
01-16 09:56:34.438 24943 24943 F DEBUG   :     x24 0000000071d83d30  x25 0000000012f049d8  x26 0000000071d83d30  x27 0000000012f04a20
01-16 09:56:34.438 24943 24943 F DEBUG   :     x28 0000000012f04a00  x29 0000000000000fad
01-16 09:56:34.438 24943 24943 F DEBUG   :     lr  00000000722e697c  sp  0000007fdb37b060  pc  00000000722e6a28  pst 0000000080001000
01-16 09:56:34.438 24943 24943 F DEBUG   : 35 total frames
01-16 09:56:34.438 24943 24943 F DEBUG   : backtrace:
01-16 09:56:34.438 24943 24943 F DEBUG   :       #00 pc 0000000000a3ea28  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.util.Log.printlns+1240)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #01 pc 0000000000a3e204  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.util.Log.e+68)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #02 pc 00000000001d7420  /data/dalvik-cache/arm64/product@priv-app@MiuiHome@MiuiHome.apk@classes.dex (com.miui.home.launcher.DeviceConfig.loadThemeResource+768)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #03 pc 00000000001d93ac  /data/dalvik-cache/arm64/product@priv-app@MiuiHome@MiuiHome.apk@classes.dex (com.miui.home.launcher.DeviceConfig.Init+140)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #04 pc 00000000001c9e74  /data/dalvik-cache/arm64/product@priv-app@MiuiHome@MiuiHome.apk@classes.dex (com.miui.home.launcher.Application.attachBaseContext+580)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #05 pc 0000000000846710  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Application.attach+48)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #06 pc 000000000033eda4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #07 pc 0000000000511050  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1976) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #08 pc 00000000004973dc  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #09 pc 0000000000357fd8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #10 pc 0000000000253090  /system/framework/framework.jar (android.app.Instrumentation.newApplication+0)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #11 pc 0000000000374120  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.420609892041422114)+232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #12 pc 0000000000373a18  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+964) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #13 pc 0000000000355968  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #14 pc 00000000006578ac  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.LoadedApk.makeApplicationInner+1772)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #15 pc 000000000065ce80  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.LoadedApk.makeApplicationInner+48)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #16 pc 000000000071d504  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleBindApplication+4228)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #17 pc 00000000007160e0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+7920)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #18 pc 00000000009946b8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+152)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #19 pc 00000000009980c4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+1044)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #20 pc 0000000000997c14  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+916)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #21 pc 000000000072988c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+1372)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #22 pc 000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #23 pc 00000000003884dc  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1588) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #24 pc 0000000000387e98  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #25 pc 0000000000333038  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #26 pc 0000000000b63a74  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+116)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #27 pc 0000000000b6e9f4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3412)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #28 pc 000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #29 pc 00000000004e1ea8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #30 pc 000000000057b930  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156) (BuildId: 735f12f804f88d62a2cb437261076ff7)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #31 pc 00000000000e6be8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+108) (BuildId: 5e7c5464fa39339dfd77976021ab0eab)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #32 pc 00000000000f3e6c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924) (BuildId: 5e7c5464fa39339dfd77976021ab0eab)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #33 pc 00000000000026fc  /system/bin/app_process64 (main+1700) (BuildId: cf9f89ee4692eca510af99645edd2f28)
01-16 09:56:34.438 24943 24943 F DEBUG   :       #34 pc 000000000008d99c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)

**Comment by HChenX** [comment]
无效日志

**Comment by NiuHK** [comment]
哪里有有效日志呢？系统的catchlog吗

焕晨HChen ***@***.***> 于 2024年1月17日周三 上午10:28写道：

**Comment by HChenX** [comment]
尝试卸载hyperceiler重装最新ci，清理系统界面数据
