### ISSUE TITLE
🐛 [BUG] 禁用充电动画失效

### ISSUE THREAD

**Issue by ColdLemonTea** [ReChronoRain/HyperCeiler#279]
### 问题描述

系统界面-其他-充电动画样式-禁用 失效

### 模块日志

[LSPosed_2024-01-16T23_25_41.622831.zip](https://github.com/ReChronoRain/HyperCeiler/files/13952277/LSPosed_2024-01-16T23_25_41.622831.zip)

### 复现步骤

```bash
1. 前往 系统界面-其他-充电动画样式
2. 点击 禁用
3. 重启

....
锁屏充电仍然会弹出动画
```

### 问题截图

自行想象（

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-01-16-23-28-48-795_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/86247681/640a96ef-261a-4d8a-91f4-4332bf6abf18)

**Comment by mu7220** [comment]
HyperOS 取消了这个事件，暂时无法解决，搁置
