### ISSUE TITLE
💡 [需求] <标题>shortcut结束运行应用

### ISSUE THREAD

**Issue by CuSO4with5H2O** [ReChronoRain/HyperCeiler#282]
### 需求内容

就是shortcut里可以一键结束运行应用

### 简单例子

个人感觉挺实用的，非常感谢

**Comment by HChenX** [comment]
shortcut是什么

**Comment by CuSO4with5H2O** [comment]
> shortcut是什么

![Screenshot_2024-01-17-10-39-28-079_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/69387481/37483eeb-4422-42b2-8182-09d8106b2de6)
就是这

**Comment by HChenX** [comment]
后台划卡即可
