### ISSUE TITLE
💡[需求] 恢复固定应用入口

### ISSUE THREAD

**Issue by LLKawi** [ReChronoRain/HyperCeiler#283]
### 需求内容

固定应用可以被搜索到但没有入口（下图）
多任务视图内入口即便打开也找不到（？不知道是不是被阉得只剩个壳了）

### 实现思路&截图

![Screenshot_2024-01-17-19-17-10-895_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/62250232/5ec9c2d8-437a-4f03-82f3-c6104901e4ba)
![Screenshot_2024-01-17-19-23-35-650_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/62250232/a33a5850-a29d-4603-aa2d-bd91ae8f291d)

### 简单例子

1. 设置中显示入口
2. 多任务视图中显示固定应用图标

**Comment by HChenX** [comment]
已经自己实现，并反手把小米的扬了
