### ISSUE TITLE
🐛 [BUG] hyber状态栏图标个数始终为1

### ISSUE THREAD

**Issue by iaston** [ReChronoRain/HyperCeiler#288]
### 问题描述

无论如何设置状态栏图标个数，都只显示一个图标。如附件可见。

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![Screenshot_2024-01-19-06-01-57-444_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/11807657/0621e172-459d-4e3a-ab1c-73b6ea8c08a1)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by HChenX** [comment]
什么hyperceiler版本
