### ISSUE TITLE
🐛 [BUG] <优化解锁动画失效>

### ISSUE THREAD

**Issue by sky-010** [ReChronoRain/HyperCeiler#290]
### 问题描述

从os1.0.24.1.8.DEV更新到os1.0.24.1.15.DEV后，开启优化解锁动画后，主界面解锁没有os1.0.24.1.8.DEV时解锁后APP图标的多次回弹效果

### 模块日志

[ 2024-01-20T01:18:25.095    10087: 25414: 25414 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~D0l1ZBuaOHOWtqvrFs-DFA==/com.sevtinge.hyperceiler-Us8gNSsmBCOG4IaYJwu3Dw==/base.apk
[ 2024-01-20T01:18:25.105    10087: 25414: 25414 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-01-20T01:18:25.266    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home]: versionName = RELEASE-4.39.14.7750-12111906, versionCode = 439147750
[ 2024-01-20T01:18:25.267    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][LoadHostDir]: Hook Success.
[ 2024-01-20T01:18:25.276    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][HideStatusBarWhenEnterRecent]: Hook Success.
[ 2024-01-20T01:18:25.277    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][TaskViewHorizontal]: Hook Success.
[ 2024-01-20T01:18:25.277    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][TaskViewVertical]: Hook Success.
[ 2024-01-20T01:18:25.277    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][FreeformCardBackgroundColor]: Hook Success.
[ 2024-01-20T01:18:25.277    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][CardTextColor]: Hook Success.
[ 2024-01-20T01:18:25.277    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][CardTextSize]: Hook Success.
[ 2024-01-20T01:18:25.280    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][DownloadAnimation]: Hook Success.
[ 2024-01-20T01:18:25.280    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][IconTitleColor]: Hook Success.
[ 2024-01-20T01:18:25.284    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][HideNavigationBar]: Hook Success.
[ 2024-01-20T01:18:25.285    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][UserPresentAnimation]: Hook Success.
[ 2024-01-20T01:18:25.564    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][ShowAllHideApp]: Hook Success.
[ 2024-01-20T01:18:25.565    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][AllAppsBlur]: Hook Success.
[ 2024-01-20T01:18:25.567    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][AnimDurationRatio]: Hook Success.
[ 2024-01-20T01:18:25.574    10087: 25414: 25414 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.home][CloseHostDir]: Hook Success.
[ 2024-01-20T01:18:39.794    10060: 25819: 25819 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~D0l1ZBuaOHOWtqvrFs-DFA==/com.sevtinge.hyperceiler-Us8gNSsmBCOG4IaYJwu3Dw==/base.apk
[ 2024-01-20T01:18:39.808    10060: 25819: 25819 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-01-20T01:18:39.926    10060: 25819: 25819 I/LSPosed-Bridge  ] [HyperCeiler][I][com.android.externalstorage]: versionName = 14, versionCode = 34
[ 2024-01-20T01:18:39.929    10060: 25819: 25819 I/LSPosed-Bridge  ] [HyperCeiler][I][com.android.externalstorage][DisableFolderCantUse]: Hook Success.

### 复现步骤

```bash
1. 前往 '系统桌面->其他'
2. 点击 '优化解锁动画'
3. 重启系统桌面
4. 锁屏
5. 解锁
出现问题：解锁动画无变化，没有之前的主界面APP图标在解锁后多次回弹的效果
```

### 问题截图

因为锁屏，无法录制

### HyperCeiler 设备信息

![Screenshot_2024-01-20-00-51-09-093_com sevtinge h](https://github.com/ReChronoRain/HyperCeiler/assets/95175199/2a609baa-02d3-4e97-93ba-382dbf51b948)

**Comment by Horange321** [comment]
没见着报错啊。方便提供下桌面的版本吗

**Comment by sky-010** [comment]
> 没见着报错啊。方便提供下桌面的版本吗

这是我的桌面版本
![Screenshot_2024-01-20-13-15-45-558_com miui secur](https://github.com/ReChronoRain/HyperCeiler/assets/95175199/c952b1fa-846d-4ef1-bf1c-b53c4a4d2a2e)
这是我提取的系统桌面
[系统桌面_RELEASE-4.39.14.7750-12111906.zip](https://github.com/ReChronoRain/HyperCeiler/files/13996832/_RELEASE-4.39.14.7750-12111906.zip)
这是我录的解锁视频（平板录的，画质有些差，抱歉），可以看到优化解锁动画开启后解锁动画没有变化
[VID_20240120_132859.h264.zip](https://github.com/ReChronoRain/HyperCeiler/files/13996861/VID_20240120_132859.h264.zip)

**Comment by Horange321** [comment]
咱apk二进制相同。而且我也没看见有报错。
这就奇怪了，我的动画就是好的。
要不你等管理员回复吧

要不你再试试清个缓存（别把数据清了啊。只清缓存）

**Comment by sky-010** [comment]
> 咱apk二进制相同。而且我也没看见有报错。 这就奇怪了，我的动画就是好的。 要不你等管理员回复吧
> 
> 要不你再试试清个缓存（别把数据清了啊。只清缓存）
太奇怪了，我把缓存、数据都清了还是不行，然后我把其它模块全关了也还是不行，我通过scene把我的12pro伪装成12spro也不行，我重装了最新版的lsp也不行，我去重装系统试试（

**Comment by sky-010** [comment]
重装了系统还是不行，看起来小米可能对这个系列做了阉割:(

**Comment by Horange321** [comment]
没办法了😥。看下次ota给不给吧

**Comment by Horange321** [comment]
不对啊，还是有问题。
这次更新完我的也失效了，但是系统桌面apk的二进制仍然相同。
我去看了下，hook点都是正常的，也没有报错，但就是失效了。十分的奇怪

**Comment by sky-010** [comment]
> 不对啊，还是有问题。 这次更新完我的也失效了，但是系统桌面apk的二进制仍然相同。 我去看了下，hook点都是正常的，也没有报错，但就是失效了。十分的奇怪
我的这周三更新了版本为HyperCeiler_2.3.136_20240124_5e2f5404(136)_canary的HyperCeiler后，莫名其妙就好了，但是在周五更新了1.0.24.1.22.DEV的开发版后，就又失效了，实在搞不懂了（
