### ISSUE TITLE
🐛 [BUG]  cemiuilier 可以冻结应用商店，HyperCelier 不能

### ISSUE THREAD

**Issue by Dian-Jiao** [ReChronoRain/HyperCeiler#291]
### 问题描述

同样在启用「手机管家-应用状态限制」下，
cemiuiler 可以冻结应用商店，HyperCeiler 不能

### 模块日志

瞄了一眼 Lsposed 日志，没有特殊的东西，传这个应该更方便解决问题

[Cemiuiler_settings_backup_2024-01-16-23_40_15.json](https://github.com/ReChronoRain/HyperCeiler/files/13992605/Cemiuiler_settings_backup_2024-01-16-23_40_15.json)

### 复现步骤

```bash
首先，开启「手机管家-应用状态限制」

使用 cemiuiler 可以正常冻结/解冻应用
使用 HyperCeiler 点击冻结无反应
如下图
```

### 问题截图

以下均是可以正常冻结的情况

![Screenshot_2024-01-20-01-53-18-957_com miui securitycenter](https://github.com/ReChronoRain/HyperCeiler/assets/59251784/d99e32be-6c76-4386-8ad8-c2d7019235a8)
![Screenshot_2024-01-20-01-53-16-388_com miui securitycenter](https://github.com/ReChronoRain/HyperCeiler/assets/59251784/8b576fb5-d768-4617-99ba-551f7fdef115)

### HyperCeiler 设备信息

![Screenshot_2024-01-20-01-52-18-145_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/59251784/50192a42-51b0-4e54-9067-db4300eb7371)

**Comment by Dian-Jiao** [comment]
二分法翻了一下 commit，看起来是 ee7d70fd 没写好，不管「系统框架-其他-禁用是否允许禁用 APP 校检」是否开启，都没办法正常禁用应用商店，使用上一个版本的构建禁用应用商店就没有问题

**Comment by Horange321** [comment]
用爱玩机冻结，会给出操作步骤

**Comment by Dian-Jiao** [comment]
> 用爱玩机冻结，会给出操作步骤

不过这个 Issue 现在变成了「系统框架-其他-禁用是否允许禁用 APP 校验」功能不生效了

**Comment by HChenX** [comment]
已经修复
