### ISSUE TITLE
🐛 [BUG] <导致特定程序无法正常运行>

### ISSUE THREAD

**Issue by awsl1414** [ReChronoRain/HyperCeiler#301]
### 须知

- [x] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

当我使用此模块时，TVBox 白屏或者停止运行

### 模块日志

[LSPosed_2024-01-22T22_59_46.103273.zip](https://github.com/ReChronoRain/HyperCeiler/files/14011757/LSPosed_2024-01-22T22_59_46.103273.zip)

### 复现步骤

```bash
1. 返回 '桌面'
2. 点击 'tvbox'

出现问题：tvbox白屏或闪退

tvbox项目地址：https://github.com/o0HalfLife0o/TVBoxOSC/releases
```

### 问题截图

![Screenshot_2024-01-22-22-54-25-900_com github tvbox osc tk](https://github.com/ReChronoRain/HyperCeiler/assets/95275520/7de6b063-bc17-454a-b423-300c5df073a3)

### HyperCeiler 设备信息

![Screenshot_2024-01-22-22-54-07-925_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/95275520/9977af87-4fb6-4048-a73a-f19ee23b5fb5)

**Comment by HChenX** [comment]
向tv反馈
