### ISSUE TITLE
🐛 [BUG] 状态栏使用双排网络图标有问题，图标缩放也不生效

### ISSUE THREAD

**Issue by iaston** [ReChronoRain/HyperCeiler#305]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

状态栏使用双排网络图标有问题，使用后如图所示，两个图标叠起来了，此时即使使用了图标缩放也不生效，图标也不会变小

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'
无
....
出现问题
```

### 问题截图

![Screenshot_2024-01-24-18-35-42-954_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/11807657/702451a9-90c8-44fd-ba76-9d1250840931)

### HyperCeiler 设备信息

![Screenshot_2024-01-24-18-38-35-591_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/11807657/734ac1cf-3334-4018-a6be-e014ad13e08a)

**Comment by mu7220** [comment]
已在最新版修复
