### ISSUE TITLE
💡 [需求] 允许不安装小米相册编辑时编辑图片

### ISSUE THREAD

**Issue by huajideshutiao** [ReChronoRain/HyperCeiler#314]
### 需求内容

小米相册如果不安装小米相册编辑，就无法点击编辑按钮进行简单的图片处理，就像这样
![Screenshot_2024-01-27-03-05-10-095_com miui gallery](https://github.com/ReChronoRain/HyperCeiler/assets/38980554/e975f7e2-6d62-4070-89fe-542ad7583b9b)

但是通过第三方应用，却是可以用相册进行编辑的
![Screenshot_2024-01-27-03-05-40-772_com mixplorer beta](https://github.com/ReChronoRain/HyperCeiler/assets/38980554/0fca9940-8581-497b-927e-84e84e192cb6)
![Screenshot_2024-01-27-03-09-09-186_com miui gallery](https://github.com/ReChronoRain/HyperCeiler/assets/38980554/1dc77917-c2b7-4266-8d2e-834d70949634)
希望能规避这个限制

### 简单例子

如上

**Comment by huajideshutiao** [comment]
没绷住，我直接把classex.dex文件里的com.miui.mediaeditor全部改名为com.miui.gallery就可以了🤣幽默hyperos

**Comment by HChenX** [comment]
6
