### ISSUE TITLE
这个在模块里面打开控制中心的矩形磁铁之后，还是会有部分情况下会变成圆形的

### ISSUE THREAD

**Issue by Jiran233** [ReChronoRain/HyperCeiler#315]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在模块里面的系统界面里的控制中心把磁贴改为矩形的，它正常状况下它确实全部都是矩形的，但是有那么几个磁贴部分情况下会恢复到圆形，不过蓝牙的话那个有点不太一样，反正怎么说我也不知道怎么说，看图片吧，这说出来的话就是它没有完全关闭它图标是灰色的，那它那个灰色图标是圆的但是它本身确实还是圆角矩形的磁贴

### 模块日志

[LSPosed_2024-01-27T10_06_32.369967.zip](https://github.com/ReChronoRain/HyperCeiler/files/14070643/LSPosed_2024-01-27T10_06_32.369967.zip)

### 复现步骤

```bash
1. 前往 '模块当中打开系统界面点击控制中心与通知中心，在里面找到新控制中心，打开圆角矩形磁贴'

....
出现问题
然后有部分磁铁仍然会出现圆形的情况
```

### 问题截图

![Screenshot_2024-01-27-09-57-20-606_com tencent tmgp sgame](https://github.com/ReChronoRain/HyperCeiler/assets/120736843/e42d69bb-f052-4dcf-b0b5-1ebff61c9051)
![Screenshot_2024-01-27-09-56-50-828_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/120736843/a2b258f3-0541-41b1-8a35-eb5134bf118c)
![Screenshot_2024-01-27-09-56-40-702_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/120736843/96ab493b-0a26-474d-bc98-4610ac9dbbde)
![Screenshot_2024-01-27-09-56-26-947_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/120736843/b343f63e-c8e2-470a-9c39-b2e9c7da9040)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-01-27-10-05-36-334_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/120736843/19241363-c30f-46bf-9531-7cef42a8f015)

**Comment by az525456** [comment]
我的也是

**Comment by QingXuer** [comment]
我的直接失效![Screenshot_2024-02-04-13-22-23-113_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/97309254/a1c3d560-de6a-4085-a5d1-d47de0ac7955)

![Screenshot_2024-02-04-13-24-49-468_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/97309254/b851ff68-8826-4bf0-94b8-33e1cfc18c8c)
