### ISSUE TITLE
💡 [需求] <标题>

### ISSUE THREAD

**Issue by ghost** [ReChronoRain/HyperCeiler#317]
### 需求内容

大佬，能不能再出一个禁用快捷窗口按钮(也就是平板中间顶上的三个点)

### 简单例子

彻底禁用掉平板中间顶上的三个点

**Comment by mu7220** [comment]
？现在那个还不行吗

**Comment by zhou40138** [comment]
> ？现在那个还不行吗

主要是真的用不到这个功能，而且还会影响我使用微软桌面远程控制，所以大佬如果能的话，能上禁用这个功能吗？

**Comment by mu7220** [comment]
ban 掉那玩意有很大难度，暂时先待定

**Comment by zhou40138** [comment]
> ban 掉那玩意有很大难度，暂时先待定

好，那谢谢大佬了，那我就先等着
