### ISSUE TITLE
🐛 [BUG] <“系统界面-其他-固定应用”功能导致系统界面崩溃>

### ISSUE THREAD

**Issue by weinibuliu** [ReChronoRain/HyperCeiler#320]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

“系统桌面-其他-固定应用”功能启用时，百分百导致系统界面崩溃

### 模块日志

[Uploading LSPosed_2024-01-28T13_50_54.411282.zip…]()

### 复现步骤

```bash
1.开启上述功能
2.重启对应作用域
3.长按状态栏
4.系统界面崩溃，问题复现
```

### HyperCeiler 设备信息

![Uploading Screenshot_2024-01-28-13-45-35-829_com.sevtinge.hyperceiler.jpg…]()

**Comment by HChenX** [comment]
别用，我还没整理
