### ISSUE TITLE
💡 [需求] <增加音量滑块阶数上限>

### ISSUE THREAD

**Issue by orz12** [ReChronoRain/HyperCeiler#333]
### 需求内容

目前最多只能调到阶数29，还是太少了，有时候调到最小一格还想继续调小
希望能支持阶数最多到60以上
![Screenshot_2024-01-31-08-39-35-870_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/17450420/5747c2bd-e796-4c59-adf7-7ae4505a9839)

### 实现思路&截图

在app/src/main/res/xml/framework_volume.xml中将SeekBarPreferenceEx的app:maxValue="29"改至60以上

### 简单例子

无

**Comment by mu7220** [comment]
29 以上存在问题，不打算增加
