### ISSUE TITLE
🐛 [BUG] 开启抽屉模糊会导致桌面异常重载

### ISSUE THREAD

**Issue by OnismIS** [ReChronoRain/HyperCeiler#338]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

开启抽屉模糊后，在应用抽屉内打开应用然后上滑返回桌面，必定导致桌面重载，100%复现

#90 提交过此bug，但是被因重复提交而close，但我没有在open的issue里找到相关bug，且2.3.137_20240201_62916021 | canary版本仍可复现，故重复提交

### 模块日志

[LSPosed_2023-11-24T12_56_05.975493.zip](https://github.com/ReChronoRain/HyperCeiler/files/14137390/LSPosed_2023-11-24T12_56_05.975493.zip)

### 复现步骤

```bash
1. 打开“抽屉模糊”
2. 自“应用抽屉”打开任一应用
3. 使用上滑手势返回桌面

出现桌面重载
```

### 问题截图

![Screenshot_2024-02-02-16-36-21-362_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/119147710/6aa2b86a-b0da-4e9a-bafd-0c02a4b27574)

### HyperCeiler 设备信息

![Screenshot_2024-02-02-16-35-39-136_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/119147710/b24c1ddb-fb7a-4334-90eb-e125c35adab8)

**Comment by OnismIS** [comment]
#191 同样是此问题

**Comment by hjjhgyh** [comment]
除了桌面重载之外，在抽屉打开应用会丢失打开动画
