### ISSUE TITLE
💡 [需求] 在隐藏小白条时强制显示旋转屏幕按钮

### ISSUE THREAD

**Issue by Dian-Jiao** [ReChronoRain/HyperCeiler#339]
### 需求内容

![IMG_20240202_174013](https://github.com/ReChronoRain/HyperCeiler/assets/59251784/36da4d9f-7bd7-4aaf-86b5-62c0ddadb141)
如图，在方向锁定并且将手机方向横置的时候，这里有个旋转屏幕按钮

但是这个旋转屏幕按钮会在隐藏小白条的时候也被隐藏了 有去小米之家看，MIUI 和 HyperOS 都有这个 Bug
![Screenshot_2024-02-02-18-11-33-037_com miui home-edit](https://github.com/ReChronoRain/HyperCeiler/assets/59251784/8f661862-094b-498b-8ab9-9b2a96ae80cd)

### 简单例子

为系统框架添加强制显示旋转屏幕按钮以便 在隐藏小白条时能够正常显示旋转屏幕按钮

可能 HyperOS 以后会修，但是我们  K40 MIUI 只能当自强了 :(

**Comment by HChenX** [comment]
再说
