### ISSUE TITLE
💡 [需求] 澎湃OS下HyperCeiler的充电动画调整

### ISSUE THREAD

**Issue by ZhangDigital** [ReChronoRain/HyperCeiler#343]
### 需求内容

升级澎湃OS后，HyperCeiler的充电动画调整不生效，无论怎么调整锁屏充电动画都是默认的，也就是官方的蓝色流光效果

### 简单例子

使在HyperCeiler-系统界面-其他-充电动画中调整后的充电动画生效（MixAlpha样式或MIUI10光韵样式）

**Comment by mu7220** [comment]
新版目前仅折腾出一个 MIUI10 样式，不考虑再修这个了
