### ISSUE TITLE
🐛 [BUG] <always on display is not always on>

### ISSUE THREAD

**Issue by Vader77Darth** [ReChronoRain/HyperCeiler#344]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

I enabled the option "Unlock the display time limit of the always-on screen" and set my always on display to always on but it still turns itself off after the 10 second timer.

https://github.com/ReChronoRain/HyperCeiler/assets/87441738/6d3c872e-9bbf-483b-843c-dae20fffbb9f

### 模块日志

[LSPosed_2024-02-04T11_17_32.515187.zip](https://github.com/ReChronoRain/HyperCeiler/files/14156475/LSPosed_2024-02-04T11_17_32.515187.zip)

### 复现步骤

```bash
1. Enable "Unlock the display time limit of the always-on screen."
2. Open settings.
3. Go to wallpaper.
4. Go to Always-on display
5. Go to Display items.
6. Select Always.

....
出现问题
```

### 问题截图

Always-on display is set to always
![Screenshot_2024-02-04-11-21-37-756_com miui aod](https://github.com/ReChronoRain/HyperCeiler/assets/87441738/a8cd0c9a-9f81-4d7a-bdc5-41e08f7b8db3)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-02-04-11-23-20-008_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/87441738/48eb118d-af21-4c37-937e-e722f6db8c6f)

**Comment by DarkGradient** [comment]
Yeah, this problem is still present

**Comment by Vader77Darth** [comment]
Yea. It started happening after I updated to HyperOS. Not sure if this is related, but reading mode stays on in AOD in hyperos now and that is definitely not a good thing because all the pixels are always on which causes more battery drain. In miui, reading mode would disable itself in AOD.

**Comment by wefny** [comment]
Yes,after I update MIUI to HyperOS ,the problem precented. but if I turn off the "system optimization" in developer options , the problem disappeared and AOD worked perfectly.

**Comment by bladbl** [comment]
The problem is relevant.
Redmi note 11 pro+ 5G
HyperOs Global 1.0.3.0
Ceiler 2.4.141_14060332
Aod Release 2103.1.0.0-04181445
