### ISSUE TITLE
💡 [需求] <将小米运动健康入口重定向至ZeppLife>

### ISSUE THREAD

**Issue by HongkeChen** [ReChronoRain/HyperCeiler#351]
### 需求内容

在没有安装小米运动健康的情况下将小米澎湃OS内部分小米运动健康入口重定向至ZeppLife以达到启动目的而不是转跳至下载

### 简单例子

例如旧穿戴设备（如部分小米手环）连接后：系统设置→蓝牙设备设置→更多→管理该设备；
![Screenshot_2024-02-10-00-43-22-481_com xiaomi bluetooth-edit](https://github.com/ReChronoRain/HyperCeiler/assets/104653254/c37e5965-39a4-48bc-8b2a-2b043a7989d5)
ZeppLife相较于小米运动健康来讲更加稳定且对部分老穿戴适配更佳，我认为需要这个功能，开发者如果方便请酌情考虑，谢谢

**Comment by HChenX** [comment]
无设备
