### ISSUE TITLE
🐛 [BUG] <小米相册-编辑 自定义机型水印 在1.6.3.5版本中失效>

### ISSUE THREAD

**Issue by jyfyge** [ReChronoRain/HyperCeiler#356]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在 自定义机型水印 中修改机型后，打开小米相册-编辑添加AI画框，仍然为EXIF信息中的机型

### 模块日志

[LSPosed_2024-02-11T20_56_05.632697.zip](https://github.com/ReChronoRain/HyperCeiler/files/14232436/LSPosed_2024-02-11T20_56_05.632697.zip)

### 复现步骤

```bash
1. 前往 '小米相册-编辑 AI创作'
2. 点击 '定制画框'
3.选择任意画框

....
出现问题
```

### 问题截图

![Screenshot_2024-02-11-20-47-34-340_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/86462294/13c4df79-aef5-4b57-9877-4337197f17e4)
![Screenshot_2024-02-11-20-47-46-623_com miui mediaeditor](https://github.com/ReChronoRain/HyperCeiler/assets/86462294/e1448f61-cb96-4edb-baf2-ce3a7cd54684)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-02-11-21-01-01-457_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/86462294/775836fa-1124-4190-8a3a-bb6494059af3)

**Comment by mu7220** [comment]
已在最新 canary 版本临时修复此问题（暂时只能修改机型后缀）
