### ISSUE TITLE
移动网络图标单独显示位置bug

### ISSUE THREAD

**Issue by ggad23** [ReChronoRain/HyperCeiler#361]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

打开移动网络单独显示的选项后，大4G/5G图标显示在信号左侧，但是并未开启图标显示在信号左侧选项
![1](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/d9a72a64-dc73-411a-af43-811c10d99773)

### 模块日志

...

### 复现步骤

```bash
1.打开移动网络单独显示
2.并确认关闭显示在信号左侧选项
3.出现问题
```

### 问题截图

![图片注释](图片链接)
![1](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/45e45669-9456-48b8-be0b-fcf74c3d8feb)

### HyperCeiler 设备信息

![图片注释](图片链接)
![2](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/4a3a9da6-1115-451a-9b6e-e7fb13543383)

**Comment by mu7220** [comment]
试试最新 canary 还会不会出现这个问题

**Comment by mu7220** [comment]
![Screenshot_2024-02-21-10-44-55-966_tw.nekomimi.nekogram-edit.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/1f49df8e-9284-4bc5-9620-ac64479db8c1)

再试试这个
不行的话我搞个强制交换
