### ISSUE TITLE
💡 [需求] hyperos可以添加禁止小绿点功能吗

### ISSUE THREAD

**Issue by LCEN1361** [ReChronoRain/HyperCeiler#363]
### 需求内容

我发现hyperos无法像miui一样能关闭小绿点（实时权限调用显示）我没能在hyperceiler里找到这个功能
希望能添加禁止在状态栏里显示小绿点，以及禁止在控制中心上显示实时权限调用的应用

### 实现思路&截图

![IMG_20240216_094055](https://github.com/ReChronoRain/HyperCeiler/assets/124220372/f8821782-20a5-4d30-aa23-5044c7d21f51)
![IMG_20240216_093952](https://github.com/ReChronoRain/HyperCeiler/assets/124220372/e4313c9f-397a-4b0a-bed3-f779c975df60)

### 简单例子

当有后台应用调用相机/麦克风/定位时，手机不会有任何提示显示

**Comment by mu7220** [comment]
不打算做
