### ISSUE TITLE
Add an ability to remove roaming icon

### ISSUE THREAD

**Issue by zxsleebu** [ReChronoRain/HyperCeiler#367]
### 需求内容

Remove roaming icon in status bar

### 实现思路&截图

![Screenshot_2024-02-16-15-09-34-483_uz unnarsx cherrygram](https://github.com/ReChronoRain/HyperCeiler/assets/46263989/addef8a5-6f68-4d29-b65d-9c933e6d163f)

### 简单例子

remove the roaming icon. you already have this code in hyperceiler but it's not used afaik

**Comment by mu7220** [comment]
add
