### ISSUE TITLE
🐛 [BUG] <redmi note12 turbo无法解锁heif格式>

### ISSUE THREAD

**Issue by digiw** [ReChronoRain/HyperCeiler#368]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

redmi note12 turbo机型，系统版本MIUI 14.0.27，当对“相机”开启了解锁HEIF格式后，进入相机设置查看，并没有发现HEIF格式的启用选项出现，似乎解锁是无效的。

### 模块日志

[fulllog.zip](https://github.com/ReChronoRain/HyperCeiler/files/14313434/fulllog.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-02-17-00-09-30-750_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/5784996/9a5a2825-a22f-4dce-9db1-c5bdfd311934)

**Comment by mu7220** [comment]
各个相机的 hook 点都不同，这里只解锁了通用相机的共同点 hook，无效不会修复
