### ISSUE TITLE
🐛 [BUG] 负一屏模糊异常

### ISSUE THREAD

**Issue by Hatsushigure** [ReChronoRain/HyperCeiler#37]
### 问题描述

负一屏的模糊背景有时不会自动取消，导致退回桌面后仍存在模糊
**注：开启了“负一屏 Fold 样式”**

### 模块日志

没有日志捏

### 复现步骤

```bash
1. 前往 '负一屏'
2. 进入 '多任务' 页面
3. 返回桌面

出现问题
```

### 问题截图

https://github.com/saraSakuHj/HyperCeiler/assets/65275829/3a97d891-4edf-41c6-96c9-aea39da249a5

### 机型

fuxi

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 14

### HyperCeiler 版本

1.3.130_20231101

**Comment by HChenX** [comment]
待修

**Comment by SauronSkywalker** [comment]
智能助理 背景样式使用官方自带模糊会导致此bug，使用自定义背景模糊可以避免模糊异常

**Comment by Hatsushigure** [comment]
其实换自定义模糊也有极小概率触发 bug, 我昨天发现的（）
