### ISSUE TITLE
🐛 [BUG] <息屏常亮失效>

### ISSUE THREAD

**Issue by firetkycz** [ReChronoRain/HyperCeiler#374]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

红米note 12 Pro+最新澎湃跟最新模块，息屏常亮跟智能显示失效，麻烦大佬修复，感谢！

### 模块日志

[Uploading LSPosed_2024-02-17T15_14_05.597301.zip…]()

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-02-17-15-16-37-440_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/160308400/c435c917-82af-43e1-94a3-6fa590d7d4af)

**Comment by Horange321** [comment]
是不是与#344重复了？

**Comment by Horange321** [comment]
是不是与 #344 重复了？
