### ISSUE TITLE
💡 [需求] 将小米的播放控制中心随音量栏一起弹出？

### ISSUE THREAD

**Issue by Yos-X** [ReChronoRain/HyperCeiler#375]
### 需求内容

将小米的播放控制中心随音量栏一起弹出，类似下面这样：
![Image_1708159081149](https://github.com/ReChronoRain/HyperCeiler/assets/97019070/5b494993-0fad-4b56-96dc-d29283d1ad14)
（受 Windows Phone 的启发
![Image_1708159574414](https://github.com/ReChronoRain/HyperCeiler/assets/97019070/3380b92b-c436-467b-bb78-897b30a8e95a)

### 实现思路&截图

miui.systemui.miplay.MiPlayDetailActivity
![Screenshot_2024-02-17-16-39-04-960_miui systemui plugin](https://github.com/ReChronoRain/HyperCeiler/assets/97019070/043c513d-0ca9-4cf0-9191-f418397231bb)

### 简单例子

可在调节音量同时控制媒体播放

**Comment by HChenX** [comment]
感觉不错，我想想

**Comment by HChenX** [comment]
想了一下还是算了，感觉没必要，这个东西太大，遮挡严重
