### ISSUE TITLE
🐛 [BUG] <wifi密码无法查看>

### ISSUE THREAD

**Issue by kevinzhou9527** [ReChronoRain/HyperCeiler#376]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

最新版的查看已保存的wifi密码功能失效

### 模块日志

无

### 复现步骤

```bash
1. 前往 '设置-wlan-高级设置-管理已保存网络'

没有查看按钮，只有删除按钮。
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by Horange321** [comment]
log呢？
我的是好的

**Comment by SainoNamkho** [comment]
> log呢？ 我的是好的

我也有这个问题，请问该如何查看log？hyperceiler的数据路径下没有日志文件，只有lsposed自身有log，但是日志里面只有hook的内容，没有报错信息

**Comment by Horange321** [comment]
> > log呢？ 我的是好的
> 
> 我也有这个问题，请问该如何查看log？hyperceiler的数据路径下没有日志文件，只有lsposed自身有log，但是日志里面只有hook的内容，没有报错信息

就是lsp的log。右上角保存按钮会给你一个zip，这个发上来就行

**Comment by SainoNamkho** [comment]
> > > log呢？ 我的是好的
> > 
> > 
> > 我也有这个问题，请问该如何查看log？hyperceiler的数据路径下没有日志文件，只有lsposed自身有log，但是日志里面只有hook的内容，没有报错信息
> 
> 就是lsp的log。右上角保存按钮会给你一个zip，这个发上来就行

谢谢，这次抓的log里有相关内容了
[LSPosed_2024-02-20T14_45_02.039201.zip](https://github.com/ReChronoRain/HyperCeiler/files/14340478/LSPosed_2024-02-20T14_45_02.039201.zip)

另外，我现在root用的是apatch，也许有一定关系

**Comment by Horange321** [comment]
无法理解。等大佬修吧。
setTitle这种函数放println都没输出。
放弃了

**Comment by HChenX** [comment]
kill设置重新进呢？

**Comment by Horange321** [comment]
调试lsp肯定会强行停止重进拉log的。在别的地方是有输出的，放hookMethod里面就不行了

**Comment by HChenX** [comment]
> 调试lsp肯定会强行停止重进拉log的。在别的地方是有输出的，放hookMethod里面就不行了

哈？

**Comment by Horange321** [comment]
module.hook.systemsettings.ViewWifiPasswordHook
在53行上面插入个sout，能看到输出。
在56行上面插入个sout，就得不到输出。

hook点的class和method我都检查过了，都没有问题，lsp也没有报错信息，但56行的就是没有输出。

**Comment by Horange321** [comment]
我又能用了。真是奇怪

**Comment by SainoNamkho** [comment]
> 我又能用了。真是奇怪

我也突然能用了，没更新

**Comment by lisiupython** [comment]
抱歉打搅大家。实测还是存在问题：点击“管理已保存网络”，进去要加载几秒，然后查看某个WiFi，只有“取消”、“删除网络”两个按钮。我记得在[Cemiuiler]最终版本是正常的。系统hyperos 1.0.3（Android13）

**Comment by HChenX** [comment]
@lisiupython 结束设置进程即可
