### ISSUE TITLE
🐛 [BUG] <禁止自动关闭小米互传失效>

### ISSUE THREAD

**Issue by Siverse** [ReChronoRain/HyperCeiler#38]
### 问题描述

禁止自动关闭小米互传失效。在hyperos上，这个功能是失效的，互传版本2.21.5

### 模块日志

[日志](https://wwat.lanzoul.com/iOwzC1ekhwvg) 
日志已上传蓝某云
如果日志是答辩请回复我   我会再提供一份

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

10u

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132-20231111-bf8147d1

**Comment by Sevtinge** [comment]
已知 在修

**Comment by HChenX** [comment]
再试试？
