### ISSUE TITLE
💡 [需求] <移除锁屏界面的点击事件>

### ISSUE THREAD

**Issue by lswlc33** [ReChronoRain/HyperCeiler#381]
### 需求内容

开启锁屏画报后，**单击** 锁屏界面的壁纸（并非点击一个按钮），会出现一个新的界面，该界面有两个按钮，并且需要再次单击返回，误触可能极大

### 实现思路&截图

普通界面
![Screenshot_2024-02-20-08-31-22-402_lockscreen](https://github.com/ReChronoRain/HyperCeiler/assets/86835895/643063ab-797a-4eb1-8f61-29f1c586656b)
画报界面
![Screenshot_2024-02-20-08-31-25-929_lockscreen](https://github.com/ReChronoRain/HyperCeiler/assets/86835895/9aa62d28-d2ed-4319-bd6b-e379e6f19fb9)

### 简单例子

移除该界面打开锁屏画报的点击事件

> 进阶提议：
> - 为小米画报添加自定义图源，例如bing壁纸等
> - 为小米画报移除一些应用内广告

**Comment by Horange321** [comment]
把画报冻结就好了

**Comment by lswlc33** [comment]
> 把画报冻结就好了
要用的
目前没有发现同类功能相同更好的代替软件

**Comment by mu7220** [comment]
没看懂（
目前软件倒是把那个按钮整个干掉了

**Comment by HChenX** [comment]
无计划
