### ISSUE TITLE
💡 [需求] <希望可以在状态栏隐藏静音图标>

### ISSUE THREAD

**Issue by a-user-xing** [ReChronoRain/HyperCeiler#383]
### 需求内容

在手机开启静音之后，状态栏不显示静音图标。

### 简单例子

一些人的手机需要常年设置静音，所以静音图标没有什么用处，反而会看着拥挤。（也有可能引起不必要的烧屏）

关闭静音图标之后就可以减少这种现象。

**Comment by mu7220** [comment]
![Screenshot_2024-02-21-11-02-02-050_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/a5d4dca0-9945-47f2-985f-aa8c25f4fcd0)

这不是有吗（？

**Comment by a-user-xing** [comment]
目前版本 HyperCeiler 2.3.137_20240210 | beta，手机Redmi k50，系统为 Xiaomi HyperoS 1.0.24.1.29.DEV ，内核版本为 5.10.198-Pandora-Beta11-20240101 ，并没有静音的选择图标。
![Uploading Screenshot_2024-02-21-11-22-54-647_com.sevtinge.hyperceiler.jpg…]()

**Comment by a-user-xing** [comment]
> ![Screenshot_2024-02-21-11-02-02-050_com.sevtinge.hyperceiler.jpg](https://private-user-images.githubusercontent.com/80700814/306480056-a5d4dca0-9945-47f2-985f-aa8c25f4fcd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODYxMjEsIm5iZiI6MTcwODQ4NTgyMSwicGF0aCI6Ii84MDcwMDgxNC8zMDY0ODAwNTYtYTVkNGRjYTAtOTk0NS00N2YyLTk4NWYtYWE4YzI1ZjRmY2QwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMTM0YWUxMmE0OGZiMmUwNDc1ZDlhODRmNTQxZDY4NDdhYzExZGVlZDUxYTg5YzgzZGFlNjFlNGVlMDFhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwgE40dcYP35023d0gHiyhaLmitEzvBdI57Nsisn75I)
> 
> 这不是有吗（？

目前版本 HyperCeiler 2.3.137_20240210 | beta，手机Redmi k50，系统为 Xiaomi HyperoS 1.0.24.1.29.DEV ，内核版本为 5.10.198-Pandora-Beta11-20240101 ，并没有静音的选择图标。
![Uploading Screenshot_2024-02-21-11-22-54-647_com.sevtinge.hyperceiler.jpg…]()

**Comment by a-user-xing** [comment]
![Screenshot_2024-02-21-11-22-54-647_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/93827481/1c6c474c-a934-4289-b140-2525a02e70dd)
图片好像被吃了（）

**Comment by mu7220** [comment]
https://github.com/ReChronoRain/HyperCeiler/actions/runs/7983298682

暂时先用这个，距离下个 beta 发布还有一段时间
