### ISSUE TITLE
💡 [需求] <为引导式访问新增额外的退出方式>

### ISSUE THREAD

**Issue by Chr0n0stasis** [ReChronoRain/HyperCeiler#384]
### 需求内容

全屏显示的时候无法呼出通知栏，故希望新增实体按键的退出方式

### 简单例子

为引导式访问新增 连续按下两次电源键 后退出使他不会因为在全屏游戏中无法呼出而无法正常退出

**Comment by mu7220** [comment]
官方已有更好的固定方式(系统桌面-最近任务-长按任务-固定应用)
这边就不再增加了

**Comment by nxibjzC** [comment]
#527
