### ISSUE TITLE
🐛 [BUG] 手电筒亮度控制失效

### ISSUE THREAD

**Issue by xiongdai666** [ReChronoRain/HyperCeiler#385]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

![Screenshot_2024-02-23-00-01-25-792_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/133245958/c2959a53-7aa6-4380-a779-4d9553bba2cf)
系统界面-通知和控制中心-手电筒亮度控制失效

### 模块日志

[LSPosed_2024-02-22T23_58_01.411918.zip](https://github.com/ReChronoRain/HyperCeiler/files/14376280/LSPosed_2024-02-22T23_58_01.411918.zip)

### 复现步骤

```bash
开启功能后，下滑状态栏开启手电筒，一滑亮度控制条手电筒就灭了，并且再也打不开手电筒了
```

### 问题截图

![图片注释](图片链接)
![Uploading Screenshot_2024-02-22-23-57-43-427_com.miui.home.jpg…]()

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by JadynWong** [comment]
我的滑动亮度控制条不会，关闭手电筒，但是亮度控制失效了，好像是从加了 保存手电筒亮度的那个提交后失效的。

**Comment by HChenX** [comment]
不搞，因为我可以用
