### ISSUE TITLE
Double row signal bar is rendered incorrectly

### ISSUE THREAD

**Issue by zxsleebu** [ReChronoRain/HyperCeiler#386]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

![Screenshot_2024-02-22-21-09-55-655_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/46263989/4694b77e-deab-4ef0-8160-5290d8f55222)

### 模块日志

no need for it

### 复现步骤

```bash
1. Turn on Double row signal bar
2. Restart System UI
```

### 问题截图

already attached

### HyperCeiler 设备信息

![Screenshot_2024-02-22-21-14-41-504_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/46263989/f1292fc9-a81f-4390-bb53-671387042531)

**Comment by mu7220** [comment]
fix
