### ISSUE TITLE
🐛 [BUG] `禁用蓝牙临时关闭` 在 HyperOS 不可用

### ISSUE THREAD

**Issue by ztc1997** [ReChronoRain/HyperCeiler#388]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

`禁用蓝牙临时关闭`在 HyperOS 不再可用了吗，我注意到在这里 c34abe2 `禁用蓝牙临时关闭`的判断条件从`isMoreMiuiVersion(14f)`变成了`isMiuiVersion(14f)`

### 模块日志

……

**Comment by HChenX** [comment]
hyper自带
