### ISSUE TITLE
🐛 [BUG] <手机管家全局侧边栏背景自定义>

### ISSUE THREAD

**Issue by 2678768226** [ReChronoRain/HyperCeiler#39]
### 问题描述

手机管家的全局侧边栏背景自定义功能开启后，在游戏界面会因手机管家停止运行而无法呼出游戏工具箱，在视频软件则可以正常使用

### 模块日志

无法提供

### 复现步骤

```bash
打开cemiuiler，点击手机管家，打开全局侧边栏背景自定义，重启定义域，打开游戏，侧边栏无法呼出，并报错：手机管家屡次停止运行
```

### 问题截图

![IMG_20231111_223248](https://github.com/saraSakuHj/HyperCeiler/assets/141047742/58d1ff3c-e831-4d30-9672-f666593657cb)

### 机型

Redmi K40Gaming

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

1.3.130_20231101

**Comment by Lejunzhe** [comment]
一样，我也是

**Comment by didiisok** [comment]
我也是
![Uploading Screenshot_2023-11-23-18-18-54-996_com.sevtinge.hyperceiler.jpg…]()

**Comment by 3049298988** [comment]
炸反色了
尝试使用低亮度值的颜色

**Comment by mu7220** [comment]
新版已添加是否反色（与 WINI 当前显示效果一致），可避免出现这个问题
