### ISSUE TITLE
🐛 [BUG] <旧版磁贴排列设置无效>

### ISSUE THREAD

**Issue by soulpursuit** [ReChronoRain/HyperCeiler#390]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

开发者您好，旧版磁贴排列，都设置6列只有未展开的时候有效，这个问题有一段时间，等了几个版本没有看到您修复，还是来反馈一下

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![1000142994](https://github.com/ReChronoRain/HyperCeiler/assets/48674277/8dd24ef4-a428-4100-9836-1ebafb64f0fc)
![1000142995](https://github.com/ReChronoRain/HyperCeiler/assets/48674277/86ea2eda-1d9a-4c02-8ea2-37cebdeddd7b)
![1000142996](https://github.com/ReChronoRain/HyperCeiler/assets/48674277/a3c8a9ad-0a2a-4104-a8ae-5abf75b84daa)

### HyperCeiler 设备信息

![图片注释](图片链接)
![1000143000](https://github.com/ReChronoRain/HyperCeiler/assets/48674277/d7ab52f7-9160-49f2-b130-970a67426b74)

**Comment by mu7220** [comment]
已在最新版修复
