### ISSUE TITLE
當控制中心快捷按鈕下方為空時，將下頁的快捷按鈕顯示在本頁

### ISSUE THREAD

**Issue by XingLiAl** [ReChronoRain/HyperCeiler#392]
### 需求内容

當控制中心快捷按鈕下方為空時，即Mi Smart Play與Smart Home均關閉時，將下頁的快捷按鈕顯示在本頁，以利用下方空白空間與方便操作

### 实现思路&截图

![Screenshot_2024-02-25-23-03-48-467_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/61769640/684c3587-5d10-4369-bf26-723fd58130e4)

### 简单例子

控制中心快捷按鈕下方為空時，即Mi Smart Play與Smart Home均關閉時，將下頁的快捷按鈕顯示在本頁，以利用下方空白空間與方便操作

**Comment by XingLiAl** [comment]
系統版本為MIUI14.0.7

**Comment by mu7220** [comment]
> 系統版本為MIUI14.0.7

MIUI 调整一下新版控制中心的行数就行了

**Comment by XingLiAl** [comment]
> > 系統版本為MIUI14.0.7
> 
> MIUI 调整一下新版控制中心的行数就行了

好的感謝

**Comment by XingLiAl** [comment]
> > 系統版本為MIUI14.0.7
> 
> MIUI 调整一下新版控制中心的行数就行了

不過好像最多只能顯示四行，即使我在設置裡改成了6行
（雖然我刪掉一個圖標之後也能用嗚
![Screenshot_2024-02-26-00-26-45-123_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/61769640/9a81b2d7-55c8-4dd3-8451-ea7c4e8c1335)

**Comment by mu7220** [comment]
> > > 系統版本為MIUI14.0.7
> > 
> > MIUI 调整一下新版控制中心的行数就行了
> 
> 不過好像最多只能顯示四行，即使我在設置裡改成了6行
> （雖然我刪掉一個圖標之後也能用嗚
> ![Screenshot_2024-02-26-00-26-45-123_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/61769640/9a81b2d7-55c8-4dd3-8451-ea7c4e8c1335)
> 
> 

毕竟是利用原来系统界面能调整的上限，凑合用吧（

**Comment by XingLiAl** [comment]
> > > > 系統版本為MIUI14.0.7
> > > 
> > > MIUI 调整一下新版控制中心的行数就行了
> > 
> > 不過好像最多只能顯示四行，即使我在設置裡改成了6行
> > （雖然我刪掉一個圖標之後也能用嗚
> > ![Screenshot_2024-02-26-00-26-45-123_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/61769640/9a81b2d7-55c8-4dd3-8451-ea7c4e8c1335)
> > 
> > 
> 
> 毕竟是利用原来系统界面能调整的上限，凑合用吧（

好哦嗚
