### ISSUE TITLE
🐛 [BUG] 國際板桌面隨機閃退

### ISSUE THREAD

**Issue by Stardusstt** [ReChronoRain/HyperCeiler#394]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

國際板桌面閃退，高機率發生於重啟後，
必須關閉作用域並用dex2oat speed(everything依舊閃退) 重新編譯後再次重啟
發生後桌面資料會消失

### 模块日志

[verbose_2024-02-25T23_21_32.562397.log](https://github.com/ReChronoRain/HyperCeiler/files/14396835/verbose_2024-02-25T23_21_32.562397.log)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![Screenshot_2024-02-25-23-21-58-014_com miui bugreport](https://github.com/ReChronoRain/HyperCeiler/assets/40061990/d106caf9-e37a-4369-82d7-de4c08a7cd40)

### HyperCeiler 设备信息

![Screenshot_2024-02-25-23-29-46-302_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/40061990/f57e900d-6ba7-42eb-b530-03a5344cf45d)

**Comment by mu7220** [comment]
等后续分 Android 版本 inithook 的时候再看看会不会继续出现

目前挂 hook 跨了四个 Android 大版本，暂时排查不出是哪里的问题

**Comment by Stardusstt** [comment]
目前我是上了hyper (android14)後出現 , 同樣版本k50沒事

**Comment by goldwoods2005** [comment]
I had the same issue with Mi13ultra using global version hyperos.
The beta version make the launcher crash, can note swipe to navigate, black out totally
Switch back to stable version, the launcher works again.

But weirdest thing is this happened when I update from previous beta without any problem to latest beta. But aftee switch back to the previous beta it crashed too
Only stable version works uptonow

**Comment by Sevtinge** [comment]
目前确定是IXposedHookInitPackageResources导致的问题，正在重写

**Comment by HChenX** [comment]
哈？

**Comment by Sevtinge** [comment]
afc8cc5091e661f22ace9c96effc2fb85892b35d
