### ISSUE TITLE
全面屏適配的切換輸入法列表裡沒有原本不支援的輸入法

### ISSUE THREAD

**Issue by XingLiAl** [ReChronoRain/HyperCeiler#395]
### 需求内容

當為系統不支持的輸入法解鎖全面屏適配時，全面屏適配中的切換輸入法列表裡並沒有系統原本不支援的輸入法
https://github.com/RC1844/MIUI_IME_Unlock
可參考此項目進行修復

### 简单例子

https://github.com/RC1844/MIUI_IME_Unlock
可參考此項目進行修復

**Comment by mu7220** [comment]
需要勾选支持的和不支持全面屏输入法才能切换
你说的这种情况就只是勾选了不支持输入法(备注：无 root 缝补进去的也是这个效果)
![Screenshot_2024-02-26-09-07-34-324_com.github.android.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/7a9b585e-d837-4f27-a3d0-c24946e51cde)

![Screenshot_2024-02-26-09-07-41-124_com.github.android.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/24201ea9-17ab-467b-93a8-165dec663a24)

**Comment by XingLiAl** [comment]
> 需要勾选支持的和不支持全面屏输入法才能切换 你说的这种情况就只是勾选了不支持输入法(备注：无 root 缝补进去的也是这个效果) ![Screenshot_2024-02-26-09-07-34-324_com.github.android.jpg](https://private-user-images.githubusercontent.com/80700814/307636548-7a9b585e-d837-4f27-a3d0-c24946e51cde.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTA1NDcsIm5iZiI6MTcwODkxMDI0NywicGF0aCI6Ii84MDcwMDgxNC8zMDc2MzY1NDgtN2E5YjU4NWUtZDgzNy00ZjI3LWEzZDAtYzI0OTQ2ZTUxY2RlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAxMTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWI5NmU5MmI3ZTMxNWFhOTUzYzlkOWE2ZTBmNTA4NjYxZjA3YTM3YTAxZjA3NjMzMGFiZDBjNzk0ZGQ4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMDlfSIZqTGIzWgsU12gq75HKrlGXn3SwNrtGDfJGE8)
> 
> ![Screenshot_2024-02-26-09-07-41-124_com.github.android.jpg](https://private-user-images.githubusercontent.com/80700814/307636547-24201ea9-17ab-467b-93a8-165dec663a24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTA1NDcsIm5iZiI6MTcwODkxMDI0NywicGF0aCI6Ii84MDcwMDgxNC8zMDc2MzY1NDctMjQyMDFlYTktMTdhYi00NjdiLTkzYTgtMTY1ZGVjNjYzYTI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAxMTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDBjOTg4MDI2N2JiMjM4Zjc3NmFmNjk5Yjk2OWUyZGI1ZjEyODRmZTk5NDJlYjkyYTJlNGVjOTM4MWEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S7ESjsjh45lF6SyvRU7MQyFXUVZB-ozvGb-8pLtykdk)

感謝，我再試一下

**Comment by XingLiAl** [comment]
> 需要勾选支持的和不支持全面屏输入法才能切换
> 你说的这种情况就只是勾选了不支持输入法(备注：无 root 缝补进去的也是这个效果)
> ![Screenshot_2024-02-26-09-07-34-324_com.github.android.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/7a9b585e-d837-4f27-a3d0-c24946e51cde)
> 
> ![Screenshot_2024-02-26-09-07-41-124_com.github.android.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/24201ea9-17ab-467b-93a8-165dec663a24)
> 
> 

已解決，感謝
