### ISSUE TITLE
🐛 [BUG] 手电筒亮度控制在小米10/10S上不生效

### ISSUE THREAD

**Issue by CC0126** [ReChronoRain/HyperCeiler#396]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

小米10/10S上手电筒亮度调整需要调整brightness节点前先关闭（或设为0）之后再设置指定的亮度才能生效
 #324  后，小米10/10S正常了，但其他较新机型可能出现了问题
所以想征求一下意见，是否要在ui里可选设置两种模式，一种是设0，然后设指定亮度，另一种是直接设置指定亮度
或者是直接操作switch节点来关闭（可能会闪，或又出现不亮的情况）

### 模块日志

无

### HyperCeiler 设备信息

![Uploading Screenshot_2024-02-26-13-49-07-178_com.sevtinge.hyperceiler.jpg…]()

**Comment by CC0126** [comment]
#385

**Comment by HChenX** [comment]
我这边就是因为这个回退更改，并重写了手电筒亮度。
你给的方法虽然可以使这两个机型正常，但其他的会有问题。
我建议你把具体方法写出来，我写两个模式供选择，

**Comment by CC0126** [comment]
模式1--目前的方法（直接设置，对应aw22手电筒芯片机型）
模式2--兼容模式，即设0再设指定值（可能导致误判led短路开路，但对老机型（PM8150A直出）有效） 参考#331 
模式3--通过switch节点关闭再设立（Cemiuiler最早的实现 ，推荐的方法）
`            // if (file1.exists() && file2.exists()) {
            //     writeFileModule(flashFileTorch, flashInt);
            //     writeFileModule(flashFileSwitch, 1);
            //     writeFileModule(flashFileSwitch, 0);
            // } else if (file1.exists()) {
            //     writeFileModule(flashFileTorch, flashInt);
            // } else
            //     XposedLogUtils.logE(TAG, "Not Found FlashLight File: " + flashFileMtk + " And: " + flashFileTorch);
        }`

**Comment by HChenX** [comment]
设置0是指把亮度改成0？

**Comment by HChenX** [comment]
模式3，可能会导致手电筒频闪，我不知道其他的会不会

**Comment by CC0126** [comment]
> 设置0是指把亮度改成0？

是的

> 模式3，可能会导致手电筒频闪，我不知道其他的会不会

频闪指的是调亮度时肉眼可见的频闪吗？实际上两个方案都有点频闪，但是老机型只能用这个方案（包括cit里面的led灯亮度测试也会闪，而且闪的比 #331 还要厉害）

**Comment by HChenX** [comment]
好的，那就这样改改

**Comment by HChenX** [comment]
已经调整

**Comment by JadynWong** [comment]
额，还是没生效，看代码逻辑和CC0126改的还是有差别，看变更前的代码https://github.com/ReChronoRain/HyperCeiler/commit/6414c5ddcc865f69a90b6c0806ca8120436e3092
模式1 bother,bmtk,btorch都为true时，应该写入other


不会写java代码，请 @CC0126检查下？

**Comment by HChenX** [comment]
再试

**Comment by JadynWong** [comment]
> 再试

ok了
