### ISSUE TITLE
🐛 [BUG] 应用包管理组件的自定义安装来源功能可能会导致无法安装应用

### ISSUE THREAD

**Issue by xuangeyouneihan** [ReChronoRain/HyperCeiler#397]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

当应用包管理组件的自定义安装来源不为空时有可能会在安装应用时无法弹出界面

### 模块日志

[log.txt](https://github.com/ReChronoRain/HyperCeiler/files/14400424/log.txt)

### 复现步骤

```
原本自定义安装来源那里填的是文件管理的包名。我今天频繁安装卸载谷歌相机和RCX，怀疑与这个有关。要想复现的话可以试试让自定义安装来源那里不为空然后多次安装应用。
```

### 问题截图

![Screenrecorder-2024-02-26-14-18-13-27](https://github.com/ReChronoRain/HyperCeiler/assets/50788434/d9f4318d-80da-4a65-91d0-400540ae5a0d)

### HyperCeiler 设备信息

![Screenshot_2024-02-26-13-53-05-916_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50788434/14cbbb11-ebea-4850-969f-f3ee1287ac9f)

**Comment by CLOUDERHEM** [comment]
你应该可以用logcat抓一下packageinstaller日志。

**Comment by Sevtinge** [comment]
复现不能
