### ISSUE TITLE
🔌 [移植] <米客，导航手势更多功能>

### ISSUE THREAD

**Issue by xly2333** [ReChronoRain/HyperCeiler#402]
### 仓库地址

https://github.com/monwf/customiuizer

### 移植内容

想要米客的全面屏导航手势里屏幕两侧向内滑动并停顿。可以选择打开各种功能。特别想通过这个展开侧边栏

### 相关描述&截图

https://www.freeimg.cn/i/2024/02/29/65e07aa727246.jpg
https://www.freeimg.cn/i/2024/02/29/65e07ad13743c.jpg

**Comment by HChenX** [comment]
不想写
