### ISSUE TITLE
🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by xly2333** [ReChronoRain/HyperCeiler#403]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

每次重启过后，模块生成的5g磁贴。在放入磁贴栏之后，总是会进入磁贴备选区，并非生成的磁贴直接消失

### 模块日志

https://wwd.lanzouq.com/iMvfR1ps0kni
这是仅保留此一模块时的日志

### 复现步骤

```bash
我手上有一台k50pro还有k60至尊，通过模块生成的5g磁贴开关，我将它放入到磁贴栏之后，重启一次都会直接消失，但却能够直接在磁贴的备选栏内找到。本人己关闭其他模块进行后测试，但是还是有这个问题，两个机型全都能够复现，系统均为官方系统最新，但均为第三方内核，我不好保证这是否和内核有关
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by HChenX** [comment]
未知
