### ISSUE TITLE
🐛 [BUG] 引导式访问 相关功能导致系统界面崩溃且功能无效果

### ISSUE THREAD

**Issue by huoyan1231** [ReChronoRain/HyperCeiler#406]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

1 开启或关闭 引导式访问 开关会导致系统界面崩溃
2 开启开关后试图启用/禁用引导式访问（长按状态栏）会导致系统界面崩溃
3 且引导式访问功能“开启”时当前应用程序并未被固定

### 模块日志

[LSPosed_2024-03-01T02_21_46.185041.zip](https://github.com/ReChronoRain/HyperCeiler/files/14451980/LSPosed_2024-03-01T02_21_46.185041.zip)

### HyperCeiler 设备信息

![8d26968448b71c7458369d567bd6eac6](https://github.com/ReChronoRain/HyperCeiler/assets/53113734/fb96aa17-75a0-4b00-9524-aff2fff49977)

**Comment by hexadecimal233** [comment]
这问题好久了，但我这固定应用能工作

**Comment by HChenX** [comment]
应该不是崩溃吧，只是锁屏了，这应该是安卓14加的新东西。

**Comment by huoyan1231** [comment]
> 应该不是崩溃吧，只是锁屏了，这应该是安卓14加的新东西。

应该是崩溃，系统界面直接卡住无响应，一段时间后黑屏，黑屏几秒后进锁屏

**Comment by hexadecimal233** [comment]
> 应该不是崩溃吧，只是锁屏了，这应该是安卓14加的新东西。

正常锁屏会有动画，现在是直接黑屏

**Comment by nxibjzC** [comment]
似乎是com/sevtinge/hyperceiler/module/hook/systemui/UiLockApp.java:77 调用不存在的方法 导致了systemui崩溃，注释此行后问题解决，但会导致新的问题：退出引导式访问后手势线功能失效，之前不存在此问题似乎是systemui重启的副作用
