### ISSUE TITLE
空白处双击锁屏不生效🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by fanld** [ReChronoRain/HyperCeiler#409]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

空白处双击锁屏不生效

### 模块日志

空白处双击锁屏不生效

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by oznll** [comment]
同求！！！我最喜欢这个功能了！
