### ISSUE TITLE
💡 [需求] 自定义安装来源校验

### ISSUE THREAD

**Issue by CLOUDERHEM** [ReChronoRain/HyperCeiler#412]
### 需求内容

如果自定义安装来源的包名是手机上不存在的应用, 会导致应用包管理组件没办法安装软件(点击安装包没有反应), 有些时候设置错不了解可能不知道怎么解决. 可以在设置前提示或者设置时候校验一下包名

### 实现思路&截图

* 提示一下用户可能存在的问题 
* 或者设置之后可以简单的对包名做一个校验, 如果不合适可以提示给用户

### 简单例子

null

**Comment by HChenX** [comment]
不要
