### ISSUE TITLE
💡 [需求] <标题>锁屏状态下快速打开手电筒

### ISSUE THREAD

**Issue by kkk101** [ReChronoRain/HyperCeiler#415]
### 需求内容

锁屏时双击音量键打开手电筒

### 实现思路&截图

![Screenshot_2024-03-03-23-22-40-735_name monwf customiuizer](https://github.com/ReChronoRain/HyperCeiler/assets/95399764/9ed64c9c-4b06-4988-bc91-361272a55fa1)

### 简单例子

快速打开手电筒

**Comment by HChenX** [comment]
拒绝
