### ISSUE TITLE
🐛 [BUG] 激活模块之后，Pad刷新率锁120，软件之内锁60，不激活无问题

### ISSUE THREAD

**Issue by badnng** [ReChronoRain/HyperCeiler#417]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

激活模块之后，除游戏之外有144，APP场景只有60，设置120，桌面120

### 模块日志

[LSPosed_2024-03-04T17_46_32.648224.zip](https://github.com/ReChronoRain/HyperCeiler/files/14479576/LSPosed_2024-03-04T17_46_32.648224.zip)

### 复现步骤

```bash
1. 激活模块
2. 查看刷新率显示
出现问题
```

### 问题截图

我拍了视频，阿里云盘给你们
VID_20240304_165348.mp4
https://www.alipan.com/s/AstA7eXi76R
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

### HyperCeiler 设备信息

![图片注释](图片链接)
![image](https://github.com/ReChronoRain/HyperCeiler/assets/115983722/fb3d90bd-8fdb-4e57-9962-34c22a14ec28)

**Comment by HChenX** [comment]
重置模块再试
