### ISSUE TITLE
💡 [需求] <增加“显示完整展开的通知”功能>

### ISSUE THREAD

**Issue by yueqingyou** [ReChronoRain/HyperCeiler#42]
### 需求内容

希望增加 “展开通知” “显示完整展开的通知” 功能
截图为 米客 模块功能相关位置截图

### 实现思路&截图

下图为 米客 模块功能相关位置截图
![IMG_20231112_210948](https://github.com/saraSakuHj/HyperCeiler/assets/70048863/1417047b-70f4-4eff-89bc-fea315214a8d)

### 简单例子

具体作用是可以设置默认展开全部通知

前提： 设置hyperos的通知样式为 **原生样式**
![Screenshot_2023-11-13-12-38-37-663_com miui notification](https://github.com/saraSakuHj/HyperCeiler/assets/70048863/29feeb92-ffa2-490a-b968-b0ee7dc62703)

展开前
![Screenshot_2023-11-13-12-39-58-072_com android chrome](https://github.com/saraSakuHj/HyperCeiler/assets/70048863/3009b683-68ea-4cea-97e1-8170033866b9)

展开后
![Screenshot_2023-11-13-12-40-04-189_com android chrome](https://github.com/saraSakuHj/HyperCeiler/assets/70048863/28106d61-1279-4a63-ab2b-3224b9950d05)

希望能够实现 **全部通知默认为展开状态**

**Comment by HChenX** [comment]
搁置

**Comment by HChenX** [comment]
已经加入
