### ISSUE TITLE
💡 [需求] <加回横屏状态下的悬浮通知高级材质背景模糊>

### ISSUE THREAD

**Issue by kijwt133** [ReChronoRain/HyperCeiler#421]
### 需求内容

23年11月中旬左右的澎湃版本开始阉割了横屏状态的悬浮通知的背景模糊，并称为为了不遮挡显示内容的特性，但结果是变透明了更看不清了。。。请求加回来（小米14的稳定版16版本还是有的，19版本就阉割掉了）
![92cd75c9e7caf753047b186b60c31e16](https://github.com/ReChronoRain/HyperCeiler/assets/114457581/70e9e7a9-58fd-42dc-8ebc-32c8ce8cfb42)
![5537f762fdf28b5dab7ebd5594101f6d](https://github.com/ReChronoRain/HyperCeiler/assets/114457581/5270ecb4-8272-4df1-b624-9e94767418e5)

### 实现思路&截图

小绿书上的一个帖子提供了MIUI14下反编译systemui重新开启横屏悬浮通知模糊的方法，但是在澎湃的systemui里面没有发现相关字段，只有相似的代码，感觉可以用来做个参考。
https://www.coolapk.com/feed/52893204?shareKey=YTA3MTRkZGJmYTJmNjVlNmI4MTY~&shareUid=1499664&shareFrom=com.coolapk.app_5.3

### 简单例子

![5537f762fdf28b5dab7ebd5594101f6d](https://github.com/ReChronoRain/HyperCeiler/assets/114457581/24d94085-86e6-42bf-9030-8f379b13e0af)

**Comment by Sevtinge** [comment]
已完成 6d04623f6ee62014bf60b3ab0642740cbe47c4c1
