### ISSUE TITLE
状态栏网速添加单行显示

### ISSUE THREAD

**Issue by 511xy** [ReChronoRain/HyperCeiler#43]
### 需求内容

hyper状态栏网速目前默认是双杠，字体较小，建议添加单行显示

### 实现思路&截图

![Screenshot_2023-11-13-13-41-12-169_com android browser](https://github.com/saraSakuHj/HyperCeiler/assets/50691422/b5a0ce30-7130-441f-8a08-31eb2abfd954)

### 简单例子

hyper状态栏网速目前默认是双杠，字体较小，建议添加单行显示

**Comment by HChenX** [comment]
搁置

**Comment by Sevtinge** [comment]
鸽置 且几乎不打算做
