### ISSUE TITLE
🐛 [BUG] 横屏时左下角的旋转按钮没了

### ISSUE THREAD

**Issue by foreverloveforeverdream** [ReChronoRain/HyperCeiler#431]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

通过ceiler的安全模式排查过，只要不修改系统界面（打开不修改系统界面开关）就不会有这个问题。但是关闭安全模式的开关，把所有系统界面相关的功能修改都关了，还是会存在这个问题。

### 模块日志

[LSPosed_2024-03-08T08_14_05.024023.zip](https://github.com/ReChronoRain/HyperCeiler/files/14531660/LSPosed_2024-03-08T08_14_05.024023.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![Screenshot_2024-03-08-08-01-54-889_com salt music-edit](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/738d2c5c-6c24-421b-a4dd-6217ac6d95d6)

### HyperCeiler 设备信息

![Screenshot_2024-03-08-08-18-48-016_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/9a9cb574-17e0-4681-b536-feb9124dee7b)

**Comment by HChenX** [comment]
打开系统框架-其他-旋转建议

**Comment by foreverloveforeverdream** [comment]
忘了说了，开了也不行，我还特地试过屏幕旋转、旋转建议一起开，一起关，一个开另一个关……都不行……
