### ISSUE TITLE
"禁止安装时上传应用信息"开启后完成下方不显示打开按钮

### ISSUE THREAD

**Issue by hexadecimal233** [ReChronoRain/HyperCeiler#435]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

标题

### 模块日志

...无报错

### 复现步骤

```bash
安装任何应用
```

### 问题截图

![image](https://github.com/ReChronoRain/HyperCeiler/assets/62250232/d66bb5c6-d2a7-4199-824e-81461500fe54)

### HyperCeiler 设备信息

![image](https://github.com/ReChronoRain/HyperCeiler/assets/62250232/be094791-dd4c-4a7f-bfef-2a0daca3048a)

**Comment by yihao0628** [comment]
这是安装的一个模块，本来就安装了不会显示打开入口，不妨安装一个QQ或者微信这样的常规软件，然后再放截图

**Comment by hexadecimal233** [comment]
错误的，hyper本来安装了就能打开

**Comment by yihao0628** [comment]
> 错误的，hyper本来安装了就能打开

好吧，我缺乏测试了

**Comment by CLOUDERHEM** [comment]
似乎这个不是很重要
