### ISSUE TITLE
🐛 [BUG] <问题标题>隐藏无SIM卡图标失效

### ISSUE THREAD

**Issue by yihao0628** [ReChronoRain/HyperCeiler#438]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在MIUI14.0.8中隐藏“无SIM卡”图标失效

### 模块日志

[LSPosed_2024-03-12T01_23_47.767484.zip](https://github.com/ReChronoRain/HyperCeiler/files/14562371/LSPosed_2024-03-12T01_23_47.767484.zip)

### 复现步骤

```bash
1. 前往 'hyperceiler'
2. 设置 '系统界面-状态栏-图标-无SIM卡图标'为始终隐藏
3. 重启 '系统界面'
4. '无SIM卡图标'未被隐藏
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-03-12-01-17-44-342_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/75688855/a0b0d0ee-3296-4891-8291-eb9dd0afaa38)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-03-12-01-28-50-908_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/75688855/d5be5abc-62b6-45af-aac6-2e9e6975f80a)

**Comment by san3456** [comment]
太专业了向你学习

**Comment by yihao0628** [comment]
> 太专业了向你学习

？？？
