### ISSUE TITLE
🐛 [BUG] 始终显示VPN无效

### ISSUE THREAD

**Issue by jarieshan** [ReChronoRain/HyperCeiler#44]
### 问题描述

始终显示VPN图标功能打开后，VPN图标仍然被折叠
hyperos 1.0.21.0
![Screenshot_2023-11-13-13-50-14-654_com android chrome](https://github.com/saraSakuHj/HyperCeiler/assets/45466320/64a779c8-ff6f-49aa-8435-86f13bbe60f5)

### 模块日志

[LSPosed_2023-11-13T13_51_45.615950.zip](https://github.com/saraSakuHj/HyperCeiler/files/13331140/LSPosed_2023-11-13T13_51_45.615950.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

Xiaomi 14 Pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231113

**Comment by HChenX** [comment]
小米写法更改，无法显示。
