### ISSUE TITLE
解决小米平板6一碰秒传

### ISSUE THREAD

**Issue by awsl1414** [ReChronoRain/HyperCeiler#443]
### 需求内容

解决root后小米pad 6s pro一碰秒传显示系统被修改问题

### 实现思路&截图

![Screenshot_2024-03-13-11-24-47-809_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/95275520/dc4bd712-3f90-422c-aa4d-8a2d762d775b)
![Screenshot_2024-03-13-11-18-36-815_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/95275520/84060601-7225-4c23-b924-629b81b1bb47)

### 简单例子

希望通过某种方式绕过系统检测

**Comment by awsl1414** [comment]
补充：
magisk已隐藏
shamiko：白名单模式
![Uploading Screenshot_2024-03-13-11-43-01-389_e.mnr.jpg…]()

**Comment by mu7220** [comment]
![Screenshot_2024-03-13-11-50-26-454_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/80700814/d4fd7b56-86e9-453e-a5aa-4c258d762ab5)

请

**Comment by awsl1414** [comment]
谢谢
