### ISSUE TITLE
🐛 [BUG] <开启多阶音量后蓝牙耳机无声音>

### ISSUE THREAD

**Issue by CangluX** [ReChronoRain/HyperCeiler#446]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

设备k50 版本 hyperos1.0.24.3.4.dev 耳机 红米airdost3pro固件版本1.0.8.8

### 模块日志

无

### 复现步骤

```bash
1. 开启媒体音量阶数，调到最大
2. 连接蓝牙耳机
出现问题
耳机没有任何声音，重启无效，只有关掉音量阶数才能恢复
```

### 问题截图

无

### HyperCeiler 设备信息

无

**Comment by Horange321** [comment]
**以官方回复为准**
当音量和耳机音量档位不匹配的时候会出问题。连蓝牙耳机的时候建议别用了
