### ISSUE TITLE
💡 [需求] <将小爱捷径添加到指纹键轻拍两下中>

### ISSUE THREAD

**Issue by JiumoHuashu** [ReChronoRain/HyperCeiler#449]
### 需求内容

这是一个MIUI 13和MIUI 14中都有的功能澎湃去除了它，它可以在悬浮球-小爱捷径中唤出，希望可以在澎湃中添加。
组件是：
com.xiaomi.voiceassistant.AiSettings.AiShortcutActivity

### 实现思路&截图

![Screenshot_2024-03-14-13-53-11-128_com miui securitycore](https://github.com/ReChronoRain/HyperCeiler/assets/145196981/a79ef5bb-eca8-4aee-b618-fa7d4c4c446e)

### 简单例子

com.xiaomi.voiceassistant.AiSettings.AiShortcutActivity

**Comment by HChenX** [comment]
无计划，记得没错长按电源键也可以呼出小爱。
