### ISSUE TITLE
💡 [需求] 阻止miui自动关闭应用自启动选择

### ISSUE THREAD

**Issue by huoyan1231** [ReChronoRain/HyperCeiler#450]
### 需求内容

如题
miui会自动关闭一些应用的自启动选项

### 简单例子

添加此功能以保证自启动设置常驻生效

**Comment by Vstory** [comment]
你只要不去手机管家里点击一键优化，就不会有这个问题

**Comment by huoyan1231** [comment]
不点也会有，我这一直被自动关闭，手机管家我都不打开的

于 2024年3月14日 GMT+08:00 20:43:07, Vstory ***@***.***> 写到:

**Comment by HChenX** [comment]
没遇到过，miui应该没有这个逻辑吧

**Comment by huoyan1231** [comment]
> 没遇到过，miui应该没有这个逻辑吧

我这边是hyperos，随手填miui了（
确实有，但是这个东西很少出现
我也是被这东西弄了好几天了才发现这东西
我这边测试稳定复现的程序：
smartspacer的duolingo插件
倒计时插件
通知插件
