### ISSUE TITLE
💡 [需求] 避免系统自带玩意儿往外置存储里拉屎

### ISSUE THREAD

**Issue by MWTJC** [ReChronoRain/HyperCeiler#452]
### 需求内容

如图所示，每次我将外置存储通过otg接上手机，部分系统自带玩意儿都会往里面拉屎，虽然我见过另一台华为手机拉屎情况更为严重，但以前k30s刷flyme确实没出现过这种现象。

### 实现思路&截图

之前是有见过有专门用于防止软件在手机存储根目录拉屎的lsposed模块，但尚不明确两者思路是否一致
如图所示，每次还不一样：
![image](https://github.com/ReChronoRain/HyperCeiler/assets/74529082/d648e951-6934-4d27-b3a9-b6d300a5bb60)
![image](https://github.com/ReChronoRain/HyperCeiler/assets/74529082/aa3f57ea-ca14-4157-bd49-0daa2ed6f498)

### 简单例子

因为这拉屎的软件似乎不止一个，所以暂时无从确定该把这想法加到哪一块…

**Comment by HChenX** [comment]
无计划
