### ISSUE TITLE
官方系统提示非官方ROM

### ISSUE THREAD

**Issue by CGBB0** [ReChronoRain/HyperCeiler#463]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

![Screenshot_2024-03-17-21-20-22-485_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/101496448/2a6f7e97-04ee-4652-a954-f5d249bab489)
![Screenshot_2024-03-17-21-20-14-307_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/101496448/a012708d-b198-4ae3-88d5-732965bfc890)

### 模块日志

![Uploading Screenshot_2024-03-17-21-24-11-039_com.sevtinge.hyperceiler.jpg…]()

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by mu7220** [comment]
请上传你的 HyperCeiler 设备信息截图

(hyperceiler 设置→开发者选项→调试信息)

**Comment by CGBB0** [comment]
![Screenshot_2024-03-17-22-16-07-156_com.sevtinge.hyperceiler.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/101496448/e392ec31-b403-4604-9aa3-ba4259490c36)

**Comment by CGBB0** [comment]
![Screenshot_2024-03-17-22-16-53-268_com.topjohnwu.magisk.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/101496448/58cc15f3-d95c-499d-a94a-7d60cc4f459c)

这是全部模块，没有冲突的
