### ISSUE TITLE
🐛 [BUG] <网速单排显示，会四倍网速>

### ISSUE THREAD

**Issue by mingyu0401** [ReChronoRain/HyperCeiler#469]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

如题，试图单排显示网速时会将近四倍网速显示。1月29到现在的canary最新都有的问题，k60Pro澎湃开发，狐狸面具和ksu均复现。群友也会遇到，主播说call焕晨）
我是明雨哦

### 模块日志

没开（这种bug开了也没用吧）

### 复现步骤

```bash
网速指示器样式选择“值和单位单行显示”或“上下行网速单行显示”，重启，测速。（保险起见可以其他设置也保持一致下）
```

### 问题截图

触发关键:![Screenshot_2024-03-19-23-59-25-302_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/c621a6ce-4072-4c3e-a978-5959bd014cd2)
示例四倍:![Screenshot_2024-03-19-23-55-30-425_com huawei genexcloud speedtest](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/49aa4cc5-2c74-4cba-8b10-c01d0a8b717b)
详细设置:![Screenshot_2024-03-20-00-21-29-367_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/877164ac-140d-459c-9e6d-8cdda3208f7a)
![Screenshot_2024-03-20-00-21-36-544_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/e8fd12a8-16a7-4948-b44a-c571404976fd)
call焕晨）
![Screenshot_2024-03-20-00-16-27-414_com tencent mobileqq-edit](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/d54daac7-450a-4291-b1fa-b91e00501fc8)

### HyperCeiler 设备信息

![Screenshot_2024-03-20-00-25-25-301_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/67409983/92b741e6-789e-4887-aca1-a409df22087d)

**Comment by HChenX** [comment]
@Sevtinge 为什么要call我？

**Comment by HChenX** [comment]
@mu7220

**Comment by mu7220** [comment]
先搁置，等我找个时间排查

**Comment by Horange321** [comment]
#480
