### ISSUE TITLE
🐛 [BUG] 更新最新版本后状态栏网速无法显示

### ISSUE THREAD

**Issue by yyyyq97** [ReChronoRain/HyperCeiler#472]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

更新最新版本后状态栏网速无法显示，MIUI14不显示，更新了澎湃的手机能显示

### 模块日志

LSPosedLogcat New 30T T1Le: ./data/adb/1spd/1og verbose_2024-03-20T12:42:29.854756.log [ 2024-03-20T12:42:36.909 0：881：1079 I/ LSPosedLogcat ] !!refresh_modules!! [ 2024-03-20T12:42:36.910 Q“ 881:1087 I/ LsPosedLogcat ] New log file: /data/adb/lspd/log/ modules_2024-03-20T12:42:36.910673.1og [ 2024-03-20T12:43:04.710 0 1000：24583：24583 I/ LSPosed ] Loading xposed for com.android.systemui/ 1000 [ 2024-03-20T12:43:04.715 1000：24583: 24583 I/LSPosed-Bridge ] Loading legacy module com.sevtinge.hyperceiler from / data/app/~~u3aihred7w0b43B_me6RmA==/ com.sevtinge.hyperceiler-aYp_d4zu6ZciorbMjc0dbQ==/base.apk [ 2024-03-20T12:43:04.726 1000：24583: 24583 I/LSPosed-Bridge] Loading class com.sevtinge.hyperceiler.XposedInit [ 2024-03-20T12:43:05.276 1000：24583: 24632 I/LSPosed-Bridge] [HyperCeiler] [W][PluginHelper]: im get ClassLoader: daivik.system.PathClassLoader[DexPathList[[zip file "/product/productapp/MIUISystemUIPlugin/ MIUISystemUIPlugin.apk"],nativeLibraryDirectories=[/ product/app/MIUIsystemUiPlugin/1ib/arm64， /product7app/product7app MIUISystemUIPlugin/MIUISystemUIPlugin.apk!/lib/arm64- v8a, /system/lib64,/system_ext/lib64,/system/lib64,/ system_ext/lib64]]] [ 2024-03-20T12:44:02.257 10114：25499: 25499 I/LSPosed ] Loading xposed for com.miui.contentextension/10114 [ 2024-03-20T12:44:02.263 10114：25499: 25499 I/LSPosed-Bridge ] Loading legacy module com.sevtinge.hyperceiler from / data/app/~~u3aihred7w0b43B me6RmA==/ com.sevtinge.hyperceiler-aYp_d4zu6ZciorbMjcOdbQ==/base.apk [ 2024-03-20T12:44:02.27210114：25499: 25499 I/LSPosed-Bridge ] Loading class com.sevtinge.hyperceiler.XposedInit [ 2024-03-20T12:44:18.625 10148：30033: 30033 I/LSPosed ] Loading xposed for com.android.fileexplorer/10148 [ 2024-03-20T12:44:18.629 10148：30033: 30033 I/LSPosed-Bridge ] Loading legacy module com.sevtinge.hyperceiler from / data/app/~~u3aihred7w0b43B_me6RmA==/ com.sevtinge.hyperceiler-aYp_d4zu6ZciorbMjcOdbQ==/base.apk [ 2024-03-20T12:44:18.637 10148：30033 30033 I/LSPosed-Bridge ] Loading class com.sevtinge.hyperceiler.XposedInit
![Uploading Screenshot_2024-03-20-12-47-51-326_com.android.shell.jpg…]()

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Uploading Screenshot_2024-03-20-12-39-47-577_com.android.chrome.jpg…]()

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-03-20-12-48-08-158_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/54359754/2aab5e95-9779-451d-823a-ee53f873641f)

**Comment by yyyyq97** [comment]
![Uploading Screenshot_2024-03-20-12-52-10-443_com.android.settings.jpg…]()

**Comment by HChenX** [comment]
主要开发者已经没人使用Miui14系统了，能用就别更新

**Comment by Horange321** [comment]
这不是HyperCeiler吗？
