### ISSUE TITLE
💡 [需求] <对 天气 开启强制深色模式>

### ISSUE THREAD

**Issue by NianBroken** [ReChronoRain/HyperCeiler#473]
### 需求内容

以 小米天气 15.0.6.1 为例
在白天下滑进入详情页时，显示为白色
在夜晚下滑进入详情页时，显示为黑色

当开启 小米天气强制深色模式 后，则无论当前为白天或黑夜，均显示黑色。

### 简单例子

null

**Comment by Sevtinge** [comment]
a04fd997f4009b0766f450d8da8507d5d3171410
