### ISSUE TITLE
💡 [需求] <系统桌面自定义动画曲线的一些建议>

### ISSUE THREAD

**Issue by wear-sky** [ReChronoRain/HyperCeiler#474]
### 需求内容

1、系统桌面自定义动画曲线默认参数不对。打开此功能后不修改具体参数，桌面动画也会变得很奇怪。猜测是MIUI时期的默认参数遗留到现在，跟澎湃桌面的默认参数不匹配了。
2、建议提高参数可调节的最大值。像rect_ratio的阻尼是可以大于1的，设置到1以上可以调节出非线性动画减速效果。目前只能调到0.99。
3、建议给每一个参数都设置一个选择按钮，选上才会修改对应参数，不选则保持默认。
4、建议给参数调节提供手动输入功能，拖动有时候很难准确拖到具体数值。

### 简单例子

关于第4点，可以在点击拖动条后弹出输入框。

**Comment by Sevtinge** [comment]
谢谢提醒 我看下

**Comment by Sevtinge** [comment]
389d1da556c7ee42050b8f49b6be034ff59dc7e3

**Comment by wear-sky** [comment]
> [389d1da](https://github.com/ReChronoRain/HyperCeiler/commit/389d1da556c7ee42050b8f49b6be034ff59dc7e3)

最大值是给到了1.99吗？建议再给高点，我之前看到一个模仿ios的修改桌面给调到2.多了。
