### ISSUE TITLE
💡 [需求] 修改状态栏“右侧”所有图标的左右间距

### ISSUE THREAD

**Issue by NianBroken** [ReChronoRain/HyperCeiler#475]
### 需求内容

目前HyperCeiler仅能修改“网速、移动网络、电池”的左右间距。

因此，希望能够增加“‘右侧’所有图标左右间距”的选项。

当修改该选项后，将对包括但不限于“WIFI、蓝牙、移动网络、位置信息、闹钟、VPN、耳机、静音、勿扰”等“右侧”所有图标，增加左右间距。

**Comment by Sevtinge** [comment]
暂无计划
