### ISSUE TITLE
💡 [需求] 取消锁屏界面的白色遮罩

### ISSUE THREAD

**Issue by NianBroken** [ReChronoRain/HyperCeiler#476]
### 需求内容

在新版MIUI/Hyper中，开启指纹解锁后，当亮度较低时，锁屏壁纸会被一个白色遮罩给提亮，官方的解释是为了提高指纹解锁的成功率。

但这个白色遮罩极为影响锁屏页面的美观性，同时还会因亮度过高而对眼睛造成不可逆的伤害。

**Comment by Sevtinge** [comment]
短期内不考虑
