### ISSUE TITLE
💡 [需求] 系统更新关闭“开启自动更新”提示

### ISSUE THREAD

**Issue by Ptilopsis01** [ReChronoRain/HyperCeiler#477]
### 需求内容

如题所述，hyperos进入系统更新时会频繁提示“开启自动更新”，希望可以关闭该内容

### 简单例子

不再显示“开启自动更新”提示

**Comment by Sevtinge** [comment]
伪装系统版本

**Comment by Horange321** [comment]
> 伪装系统版本

伪装版本了不就收不到更新了吗？

**Comment by Ptilopsis01** [comment]
对啊，我不是不想收到系统更新，我是觉得这个弹窗很烦希望能关掉

**Comment by Horange321** [comment]
写完了，但是昨天更新了就没这个Dialog了。等下个星期测试好了再pr。
下周五记得踢我一下

**Comment by Horange321** [comment]
写完了，但是昨天更新了就没有这个提示了。等下周测试完了再pr。
下周五记得踢我一下

**Comment by Ptilopsis01** [comment]
@Horange321 大佬系统更新推送了

**Comment by Horange321** [comment]
#499
