### ISSUE TITLE
💡 [需求] 小米相册国际版支持同步至OneDrive，不知能否通过ceiler整合？

### ISSUE THREAD

**Issue by wwjjhh1995** [ReChronoRain/HyperCeiler#479]
### 需求内容

在去年9月的更新中，米子效仿三星，在自家的MIUI gallery中原生支持将相册同步至OneDrive。
此功能疑似有区域限制，不知能否通过伪装，为国行系统开启此功能？
相关报道和说明：
https://support.microsoft.com/zh-tw/office/onedrive-%E8%88%87-xiaomi-%E6%95%B4%E5%90%88-04b04610-ecce-4b93-a236-4508403dd204
https://xiaomiui.net/new-miui-gallery-to-support-photo-video-backup-on-onedrive-51242/

### 简单例子

为小米相册提供OneDrive同步入口。

**Comment by Horange321** [comment]
没用过国际版。但是请问两个版本的相册apk相同吗？

**Comment by Sevtinge** [comment]
apk存在差异 部分版本onedrive备份未入版 短期不考虑添加
