### ISSUE TITLE
💡 [需求] <标题>在选择主题色中添加十六进制或是RGB颜色代码的选项

### ISSUE THREAD

**Issue by Komneni** [ReChronoRain/HyperCeiler#485]
### 需求内容

目前在系统界面-其他-选择主题色中只能使用网格或是滑块取色，希望能够加入十六进制或是RGB颜色代码，如图

### 简单例子

![Screenshot_2024-03-23-00-10-50-284_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/52524726/228aa34c-c950-411f-a61f-fd15d9199a2c)
![Screenshot_20240323-001103_设置](https://github.com/ReChronoRain/HyperCeiler/assets/52524726/f96e1bf7-349a-4696-8c65-03091085dab5)

**Comment by Sevtinge** [comment]
miuixv3在路上 实现了这个
