### ISSUE TITLE
状态栏字体加粗显示bug

### ISSUE THREAD

**Issue by ggad23** [ReChronoRain/HyperCeiler#487]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

打开状态栏时钟指示器和移动网络单独显示的加粗选项时，无加粗效果

### 模块日志

[LSPosed_2024-03-23T09_47_44.437906.zip](https://github.com/ReChronoRain/HyperCeiler/files/14729866/LSPosed_2024-03-23T09_47_44.437906.zip)

### 复现步骤

```bash
1.打开时钟指示器和移动网络单独显示的加粗选项
出现问题
```

### 问题截图

![122](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/d5bc8ad3-e700-4a4c-a6c0-1a6e6c8daa43)

![12](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/bc5b0038-01e0-4552-aec0-ee7d07488066)
![1333](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/b69d238b-1bc6-47dc-8b8f-74795672e837)
![133](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/b089119e-56d5-4546-9970-ada77313c15c)

### HyperCeiler 设备信息

![3366](https://github.com/ReChronoRain/HyperCeiler/assets/125014975/0498abbd-344e-48e2-a78e-28de654309ed)

**Comment by Horange321** [comment]
这是第三方主题吧？

**Comment by ggad23** [comment]
> 这是第三方主题吧？

不好意思，没排查清楚问题，是字体的问题，不是第三方主题的问题。话说这个加粗选项的实现能否通过直接调用粗体的字重来显示呢？

**Comment by mu7220** [comment]
> > 这是第三方主题吧？
> 
> 不好意思，没排查清楚问题，是字体的问题，不是第三方主题的问题。话说这个加粗选项的实现能否通过直接调用粗体的字重来显示呢？

hyperOS 自己的问题，不会打算修改

**Comment by mu7220** [comment]
> > 这是第三方主题吧？
> 
> 不好意思，没排查清楚问题，是字体的问题，不是第三方主题的问题。话说这个加粗选项的实现能否通过直接调用粗体的字重来显示呢？

hyperOS 自己的问题，不会打算修改
