### ISSUE TITLE
🐛 [BUG] Double button Disable/Enable Apps

### ISSUE THREAD

**Issue by JeelsBoobz** [ReChronoRain/HyperCeiler#496]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

Contains double button for enable/disable apps

### 模块日志

No crash

### 问题截图

![IMG_20240328_101924_661](https://github.com/ReChronoRain/HyperCeiler/assets/38210868/f43248aa-f42d-4762-808d-bc21f6b1cfef)
![IMG_20240328_101924_033](https://github.com/ReChronoRain/HyperCeiler/assets/38210868/ab006bfc-6bf0-4f81-b0d7-10385f234c3e)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-03-28-10-17-59-913_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/38210868/1e020a92-e3c1-4f17-8107-61f2e7d1daad)

**Comment by Horange321** [comment]
MIUI or HyperOS?

**Comment by HChenX** [comment]
know
