### ISSUE TITLE
澎湃系统的控制中心和通知栏背景分别设置

### ISSUE THREAD

**Issue by Tampledb** [ReChronoRain/HyperCeiler#497]
### 需求内容

如题，更新澎湃以后，qs_control_bg.9.png的透明图失效，只要设置了notification_panel_window_bg.9.png，则下拉控制中心和通知栏背景就会全起作用。不知道是澎湃改写了控制栏背景的名称还是单纯的bug，1人血书求改回来（捂脸痛哭）

### 简单例子

![IMG_1104(1)(1)](https://github.com/ReChronoRain/HyperCeiler/assets/96903051/60035637-ab9b-4d79-8390-7e360be41a84)

**Comment by Tampledb** [comment]
![IMG_1104(1)(1).PNG](https://github.com/ReChronoRain/HyperCeiler/assets/96903051/9f960d2c-ed64-4d1a-8044-a32ee2c3b5be)

试试看吧，万一能做呢

**Comment by mu7220** [comment]
不打算做
