### ISSUE TITLE
无法停用从旧版本导入的通知设置

### ISSUE THREAD

**Issue by PL7963** [ReChronoRain/HyperCeiler#502]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

系統介面>通知與控制中心>通知設定 若在舊版HyperCeiler/Cemiuiler啟用，導入後則無法關閉設定，且會持續生效
最新版Canary仍然保有此问题

### 模块日志

.

### 复现步骤

```bash
1. 在舊版HyperCeiler啟用通知設定，並備份配置
2. 於新版HyperCeiler導入配置
```

### 问题截图

![Screenshot_2024-03-30-12-55-22-356_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/44529370/b5a72be2-032a-4c45-8a35-ddf60c5847f4)

### HyperCeiler 设备信息

![Screenshot_2024-03-30-13-04-33-922_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/44529370/9848228e-9c48-4269-aa09-63a779137aba)

**Comment by HChenX** [comment]
自己手动从新设置
