### ISSUE TITLE
💡 [需求] 去除「工作台」磁贴的机型限制

### ISSUE THREAD

**Issue by hrsthrt74** [ReChronoRain/HyperCeiler#503]
### 需求内容

米系低端板子上默认无「工作台」磁贴，用`settings put secure sysui_qs_tile xxx`的方法也无法添加，但磁贴相关资源确实存在于`系统界面组件`中，想拜托各位大佬去除机型限制

### 实现思路&截图

可能有用的信息：
工作台磁贴在`sysui_qs_tile`的值：`dtmdtm`
磁贴图标位于`系统界面组件`（貌似比较新的任意版本都可）

### 简单例子

为「工作台」磁贴去除机型限制，以便低端平板机型添加至控制中心

**Comment by Sevtinge** [comment]
是```sysui_qs_tiles```吧

**Comment by hrsthrt74** [comment]
> 是`sysui_qs_tiles`吧

确实，手打打错了（

**Comment by hrsthrt74** [comment]
`系统界面组件`的`MiuiDesktopModeTile`类，`isAvailable`方法，让它总是返回true就可以了😂我这边改dex测试能用了，把`isAvailable`方法改成了：
```
.method public isAvailable()Z
.registers 1

const/4 v0, 0x1

return v0
.end method
```
hook啥的我就不会了，上面那段代码还是问 ChatGPT 问来的😂
