### ISSUE TITLE
💡 [REQ] Extended Power Menu

### ISSUE THREAD

**Issue by JeelsBoobz** [ReChronoRain/HyperCeiler#505]
### 需求内容

New feature Extended Power Menu like https://github.com/MonwF/customiuizer/blob/d8f162653c413674f36a7d8d2b05cbd8543cf40c/app/src/main/java/name/monwf/customiuizer/mods/SystemUI.java#L3462

### 简单例子

https://github.com/MonwF/customiuizer/blob/d8f162653c413674f36a7d8d2b05cbd8543cf40c/app/src/main/java/name/monwf/customiuizer/mods/SystemUI.java#L3462

**Comment by HChenX** [comment]
不想写
