### ISSUE TITLE
🐛 [BUG] <警告进入安全模式频繁出现>

### ISSUE THREAD

**Issue by ilixtic** [ReChronoRain/HyperCeiler#518]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

更新最新版后频繁出现警告进入安全模式

### 模块日志

[LSPosed_2024-04-05T10_15_42.057509.zip](https://github.com/ReChronoRain/HyperCeiler/files/14879062/LSPosed_2024-04-05T10_15_42.057509.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片
![522b14875246ef4ffd858e628f342e35](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/b39e6fcb-443e-4b66-bc90-a5c515e0d8ac)
注释](图片链接)
![a662a8bf6effbf21f6c4971ab580ea77](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/b4829911-2fc4-4e8f-
![4012f5c2f15e2a68ae40e368fcc98568](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/f295f3b4-3771-4847-8cb4-aa787dd7ade7)
8e3d-dab
![4a67372224d687bcbe7c68760e358dcf](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/00559c96-b863-4439-9ab4-6fe99668ddb5)
8a46be762)

### HyperCeiler 设备信息

![图片注释](图片链接)
![26062e64b375acd73170d9e403a5392b](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/2d2e0c6f-5d9e-4def-9e26-5767cba7b827)

**Comment by ilixtic** [comment]
![522b14875246ef4ffd858e628f342e35](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/30466f2a-8f3a-450b-a93f-5bea0a4da744)

**Comment by ilixtic** [comment]
![a662a8bf6effbf21f6c4971ab580ea77](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/0cac9953-1e56-4abc-b1ef-c46812b12be8)

**Comment by mu7220** [comment]
> ![522b14875246ef4ffd858e628f342e35](https://github.com/ReChronoRain/HyperCeiler/assets/120478622/30466f2a-8f3a-450b-a93f-5bea0a4da744)
> 

有没有可能，是你手机管家有问题了
安全模式本来就是这样工作的
