### ISSUE TITLE
💡 关闭手机管家危险操作警告页面

### ISSUE THREAD

**Issue by 3049298988** [ReChronoRain/HyperCeiler#519]
### 需求内容

添加一个按钮，或者是默认执行
pm disable com.miui.securitycenter/com.miui.permcenter.privacymanager.SpecialPermissionInterceptActivity
来关闭下面这个页面
![Screenshot_2024-04-05-13-53-25-818_com miui securitycenter](https://github.com/ReChronoRain/HyperCeiler/assets/61861526/de17e44f-aeda-4380-b87d-fbb02c0905af)

**Comment by mu7220** [comment]
无计划

**Comment by 3049298988** [comment]
> 无计划

坏诶（

**Comment by mu7220** [comment]
@3049298988 不许说坏
就是没计划(懒得做)
