### ISSUE TITLE
息屏十秒限制解除失效

### ISSUE THREAD

**Issue by mysh212** [ReChronoRain/HyperCeiler#520]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

息屏十秒限制解除失效

### 模块日志

[Uploading LSPosed_2024-04-06T08_51_26.364736.zip…]()

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

Debug Info by HyperCeiler VersionName = 2.4.141_14060332 VersionCode = 141 BuildTime = (UTC+0:00) 2024-03-31 18:24:35 BuildType = bamboo GitHash = 3bea86db Debug = false ApplicationId = com.sevtinge.hyperceiler MarketName = Redmi Note 12 Turbo DeviceName = marble Model = 23049RAD8 C Brand = Redmi Manufacture = Xiaomi Board = marble Soc = taro FingerPrint = Redmi/marble/marble:14/UKQ1.230804.001/V816.0.2.0.UMRCNXM:user/release-keys Locale = zh-CN Language = zh_TW AndroidId = 880b01b 0 a57053b 2 AndroidVersion = 34 MiuiVersion = 0.0 HyperOsVersion = 1.0 SystemVersion = V816.0.2.0.UMRCNXM Builder = builder RomAuthor = BaseOs = Host = pangu-build-component-system-543686-0 c38x-smsh5-77cjj BuildDate = Fri Jan 26 12:48:22 UTC 2024 Signature = 46:4 C:5 C:9 D:A 2:8 C:AE:E 6:B 3:28:8 D:AE:13:2 C:A 3:6 D:52:A 1:64:89:E 0:95:CF:7 B:52:AC:A 7:11:F 0:93:82:3 C SignCheckPass = true ModuleActive = true RootPermission = true

**Comment by mu7220** [comment]
@mysh212 这第三份相同问题了吧

**Comment by mysh212** [comment]
ouo
