### ISSUE TITLE
🐛 [BUG] 磁铁没有自动补全

### ISSUE THREAD

**Issue by sxwzxc** [ReChronoRain/HyperCeiler#525]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在经典控制中心增加行列数后，磁贴没有补全。

### 模块日志

![Screenshot_2024-04-06-16-59-40-678_com android shell](https://github.com/ReChronoRain/HyperCeiler/assets/33121657/bb45c89b-884e-43a8-85af-7c002f8c0c6b)

### 复现步骤

```bash
增加经典控制中心的行列数，重启系统。
打开通知栏。
存在第二页的情况下，第一页磁贴未满。
```

### 问题截图

![Screenshot_2024-04-06-16-55-02-155_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/33121657/184b2015-46ec-44c1-b29d-0ce7ee37b888)

### HyperCeiler 设备信息

![Screenshot_2024-04-06-17-01-39-064_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/33121657/bf6e0fed-fbe3-4cf8-8e57-912bb34aa720)

**Comment by Sevtinge** [comment]
？
