### ISSUE TITLE
💡 [需求] <解决引导式访问时状态栏干扰触控>

### ISSUE THREAD

**Issue by nxibjzC** [ReChronoRain/HyperCeiler#527]
### 需求内容

提供一个选项以：
1.在引导式访问时隐藏状态栏
2.由于状态栏隐藏了，需要提供新的退出引导式访问的方式

### 实现思路&截图

我已经基本完成了它，如果管理员希望，我将做一些完善并提交pull request，这是我目前已经做了的 https://github.com/ReChronoRain/HyperCeiler/compare/main...nxibjzC:HyperCeiler:main
我的实现：
1.通过为状态栏窗口添加相关监听，在进入引导式访问时设置状态栏不可见，退出时反之
2.对长按电源进行hook，触发退出引导式访问

### 简单例子

对astroDX等反复在边缘区域操作的游戏有很大帮助

**Comment by nxibjzC** [comment]
also solved #384 #357

**Comment by Chr0n0stasis** [comment]
之前实测的时候有的时候长按通知栏经常退不出去，所以这个对于我来说似乎好用很多

**Comment by HChenX** [comment]
你可以做，做完PR即可，我会检查

**Comment by p88oo** [comment]
请问目前版本2.4.141_14060332内置的引导式访问是新做的吗，现在引导式访问开启时状态栏会残留（只显示半透明栏，不显示时间图标等内容），退出要先下滑一次长按才会退出并显示时间、图标

**Comment by nxibjzC** [comment]
> 请问目前版本2.4.141_14060332内置的引导式访问是新做的吗，现在引导式访问开启时状态栏会残留（只显示半透明栏，不显示时间图标等内容），退出要先下滑一次长按才会退出并显示时间、图标

版本太旧了，请到telegram Canary Test频道获取2.4.144以上的版本

**Comment by p88oo** [comment]
> > 请问目前版本2.4.141_14060332内置的引导式访问是新做的吗，现在引导式访问开启时状态栏会残留（只显示半透明栏，不显示时间图标等内容），退出要先下滑一次长按才会退出并显示时间、图标
> 
> 版本太旧了，请到telegram Canary Test频道获取2.4.144以上的版本

好的，我一般只看lsp仓库的更新，都不知道有新版本😂
