### ISSUE TITLE
『bug』截图无法解除最小区域限制

### ISSUE THREAD

**Issue by sxyofficial** [ReChronoRain/HyperCeiler#528]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

选中解锁截图区域最小限制，重启作用域并截图后发现此功能已失效
https://github.com/ReChronoRain/HyperCeiler/assets/138845393/6b8728b0-17a1-45b7-a45d-3e5981730011

### 模块日志

[LSPosed_2024-04-07T11_00_35.934513.zip](https://github.com/ReChronoRain/HyperCeiler/files/14895622/LSPosed_2024-04-07T11_00_35.934513.zip)

### 复现步骤

```bash
使用的是最新ci，重启手机后开启解锁截图区域最小限制并重启作用域，截图后发现无法解锁截图区域最小限制
```

### HyperCeiler 设备信息

![Screenshot_2024-04-07-11-01-23-339_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/138845393/3ffe3e61-a375-4664-8cfc-3e6bdfe65f11)

**Comment by mu7220** [comment]
@sxyofficial 把自己的截屏应用更新一下下就正常了
这边表示不清楚为什么会这样

**Comment by sxyofficial** [comment]
> @sxyofficial 把自己的截屏应用更新一下下就正常了
> 这边表示不清楚为什么会这样

截屏是最新的qwq![Screenshot_2024-04-07-11-23-01-929_com.miui.securitycenter.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/138845393/5e37130e-6d76-45be-904c-3942264f9816)

**Comment by mu7220** [comment]
那就卸载更新后重新更新

**Comment by mu7220** [comment]
这边也是这个版本，无任何异常
