### ISSUE TITLE
🐛 [BUG] <配置设置自动恢复默认>

### ISSUE THREAD

**Issue by wzgrx** [ReChronoRain/HyperCeiler#532]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

lsp卸载后，模块设置会自动恢复默认，希望加个自动备份配置的功能

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by HChenX** [comment]
莫名其妙
