### ISSUE TITLE
🐛 [BUG] <app无法横屏显示>

### ISSUE THREAD

**Issue by Saulwonderfulman** [ReChronoRain/HyperCeiler#533]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在小米平板6p刷入最新模块(2.4.141_14060332 bamboo)后,app无法横屏.但在之前的版本app是可以正常横竖屏转换的

### 模块日志

日志正常

### 复现步骤

```bash
刷入模块打开app即可复现
```

### 问题截图

只能竖屏显示无法横屏显示

### HyperCeiler 设备信息

![20240408214256](https://github.com/ReChronoRain/HyperCeiler/assets/67410761/5121c26b-9a5b-405c-ad5e-1d41cd2e07a4)

**Comment by HChenX** [comment]
en

**Comment by mu7220** [comment]
无法横屏显示是因为手机端目前横显示有问题，强制竖屏了，没适配

等后面调整一下逻辑
