### ISSUE TITLE
[BUG]功能失效

### ISSUE THREAD

**Issue by AkinCat** [ReChronoRain/HyperCeiler#534]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

ceiler的隐藏状态栏图标和调试docker栏出现异常

### 模块日志

软件没崩溃 只是不起作用

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-04-09-01-11-25-861_com android shell](https://github.com/ReChronoRain/HyperCeiler/assets/150003389/9730adf6-ee29-4dca-8ae8-4618168f4f69)
![Screenshot_2024-04-09-01-13-00-170_com android settings](https://github.com/ReChronoRain/HyperCeiler/assets/150003389/c96a6aa0-0b1a-46e1-a54c-e26c0b91d1cc)
![Screenshot_2024-04-09-01-12-22-974_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/150003389/07a0dabb-9e00-43cb-bac3-238582ea1149)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-09-01-37-01-311_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/150003389/82a2e6ab-8756-4dc1-804a-4504661c5d8b)

**Comment by AkinCat** [comment]
图二是想表达 我勾选了隐藏图标但是图标并没有发生变化

**Comment by mu7220** [comment]
没崩溃也要提供 debug 日志，这是一个反馈基本原则问题

hyperceiler 设置→日志输出等级改成 debug，然后复现一次，将 lsposed 日志上传发给我

**Comment by AkinCat** [comment]
> 没崩溃也要提供 debug 日志，这是一个反馈基本原则问题
> 
> hyperceiler 设置→日志输出等级改成 debug，然后复现一次，将 lsposed 日志上传发给我

发到你的邮箱了，不好意思不是很懂这些

**Comment by HChenX** [comment]
尝试更新版本，不行再开个issued记得日志。
