### ISSUE TITLE
🐛 [BUG] <日志输出级别无法调整至Debug>

### ISSUE THREAD

**Issue by marskiti** [ReChronoRain/HyperCeiler#535]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在最新的canary版本Hyperceiler中，无法启用Debug等级。具体为选择Debug选项后，重启设备仍然显示为Info选项。在4月1号的愚人节版本无此现象。

### 模块日志

[LSPosed_2024-04-10T19_29_00.901386.zip](https://github.com/ReChronoRain/HyperCeiler/files/14931530/LSPosed_2024-04-10T19_29_00.901386.zip)

### 复现步骤

```bash
1. 前往 '点击HyperCeiler'
2. 点击 '设置'
3. 选择日志输出等级为'Debug'
4. 重启设备
5. 打开HyperCeiler→设置→日志输出等级仍然是Info
....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-04-10-19-32-59-974_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/95144979/aadde80f-4c05-4f91-b661-0cd28b5e325c)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-10-19-26-43-186_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/95144979/5b1a777f-146e-4df9-aa9d-89aaec2713db)

**Comment by Sevtinge** [comment]
c3cbb6bdc43e5d3c65dd177e175ddff9f06b7cc1
