### ISSUE TITLE
🐛 [BUG] <新春画框失效>

### ISSUE THREAD

**Issue by junguoqianshan** [ReChronoRain/HyperCeiler#546]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

小米相册—编辑的解锁新春定制画框功能失效

### 模块日志

[LSPosed_2024-04-12T21_28_41.473465.zip](https://github.com/ReChronoRain/HyperCeiler/files/14959340/LSPosed_2024-04-12T21_28_41.473465.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by mu7220** [comment]
无失效，此相框仅存在于部分版本中，在最新的相册编辑中均已移除(也就是没用)
