### ISSUE TITLE
跳过敏感设置10秒警告时间

### ISSUE THREAD

**Issue by cicur** [ReChronoRain/HyperCeiler#548]
### 需求内容

跳过敏感设置（如安装未知应用、无障碍、USB调试等）10秒警告时间
![IMG_20240414_104441](https://github.com/ReChronoRain/HyperCeiler/assets/88472780/45896921-4fdf-4249-a2d6-0c26dd8bcccf)

### 实现思路&截图

[Woobox For MIUI](https://github.com/Simplicity-Team/WooBoxForMIUI) 有这个功能，或许可以参考

### 简单例子

跳过敏感设置的警告时间，以便直接确认

**Comment by HChenX** [comment]
有

**Comment by DreammStill** [comment]
这个功能在憨批露里面的安全服务里面
