### ISSUE TITLE
💡 [需求] 部分机型解锁同时开启高刷和防闪烁

### ISSUE THREAD

**Issue by Ptilopsis01** [ReChronoRain/HyperCeiler#549]
### 需求内容

如题，目前部分机型这两个功能不能同时开启，但可以通过省电模式卡bug卡出来，也就是理论上是能同时开的，希望可以通过模块实现

### 简单例子

如上所述

**Comment by Mubai-meng** [comment]
卡出来的好像是假的吧

**Comment by Ptilopsis01** [comment]
不是，之前有很多卡出来的
不过现在好像卡不了了，因为开省电会锁60hz

**Comment by HChenX** [comment]
无计划
