### ISSUE TITLE
🐛 [BUG]网速，dock模糊无效

### ISSUE THREAD

**Issue by horrself** [ReChronoRain/HyperCeiler#55]
### 问题描述

1.由于hyper把网速功能直接移动到右边并自动分成两行，网速的各种设置均无效（如网速显示在右边，加粗等）
2.hyper系统的dock栏模糊无效

### 模块日志

可以联系我要日志

### 复现步骤

```bash
1. 前往 搜索网速
2. 点击 网速 图标右侧显示（其实应该改成左侧效果）无效

....
出现问题
前往dock栏背景模糊
点击系统模糊，无效
```

### 问题截图

![图片注释](图片链接)

### 机型

13pro

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132-20231114

**Comment by Sevtinge** [comment]
你用hyper就别用系统模糊了 至于网速 在修了 别急

**Comment by Sevtinge** [comment]
网速修好了 请在最新Canary版本验证
