### ISSUE TITLE
💡 [需求&&BUG] <在hyper系统的链式启动管理中添加手动管理，在HyperCeiler中修复“移除链式启动弹窗”>

### ISSUE THREAD

**Issue by lux-QAQ** [ReChronoRain/HyperCeiler#552]
### 需求内容

需求的根源：我使用了两个 xp模块分别名为AdClose（用来阻止常见广告SDK的初始化）和算法助手，这两个模块的作用域都勾选了QQ，但是当我进入 应用信息->权限使用记录 时我发现QQ多次请求启动这两个模块被拒绝（但是hyperos并没有在QQ请求启动这两个模块的时候，弹出链式启动的授权窗口）。
![问题](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/6ad74ad9-bc33-481f-93d9-0081f87c32ba)
我发现这两个模块的作用域下其他应用存在同样的问题，因此可以推测是hyperos本身的问题。
我试着去 隐私与安全- >其他权限->链式启动管理 中手动添加这两个模块的链式启动权限，但是发现并没有手动管理的按钮（也就是说只能通过弹出链式启动的授权窗口来添加授权）
![问题所在](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/619aea0c-947c-4df6-8cc4-62b2d650d9c1)
然后我在HyperCeiler找到了 移除链式启动弹窗 这一选项卡，当我开启并重启手机后，我发现该功能无效，链式启动弹窗仍然出现，上文的问题仍然存在。
![现有的功能](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/6effc82f-176b-4eb7-a115-b9fb51683bff)

设备：K60PRO
HyperCeiler版本：2.4.141_14060332
hyper os版本：1.0.8.0.UMKCNXM
权限管理服务版本：1.8.4

### 实现思路&截图

1. 在 隐私与安全- >其他权限->链式启动管理 中添加手动管理的按钮。
2. 
![s2](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/ae947082-93a1-4a2b-8c1a-c31d0c7f6960)
![Uploading s1.jpg…]()
检查并修复HyperCeiler中“移除链式启动弹窗”选项卡

### 简单例子

![s1](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/92778661-5231-4b86-992b-d2d8b502918a)
![s2](https://github.com/ReChronoRain/HyperCeiler/assets/51485740/849d7f90-1e88-43c0-b266-1f5b3b1e82dc)

**Comment by HChenX** [comment]
我觉得你应该反馈给这个这几个模块的作者

**Comment by lux-QAQ** [comment]
我确实去这两模块的仓库里面提出issue了，但是我感觉这是hyperos自身的机制导致的问题，希望HyperCeiler的大大们能优化下链式启动的手动授权。

**Comment by mu7220** [comment]
这个链式启动弹窗比较奇怪
模块开了之后默认是确认的

debug 也没出现问题，~~暂时开摆~~
