### ISSUE TITLE
不显示通知模糊相关设置

### ISSUE THREAD

**Issue by DreammStill** [ReChronoRain/HyperCeiler#556]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

基于安卓 13 的 hyper os 在憨批露中不显示通知模糊相关的设置，搜索是可以搜到的，但是不显示

### 模块日志

[LSPosed_2024-04-17T18_03_23.370836.zip](https://github.com/ReChronoRain/HyperCeiler/files/15009317/LSPosed_2024-04-17T18_03_23.370836.zip)

### 复现步骤

```bash
1. 前往 '系统界面组件'
2. 点击 '通知与控制中心'

....
其中没有通知模糊相关内容
```

### 问题截图

![Screenshot_2024-04-17-18-03-54-008_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/77729084/a6187cd1-19c0-4bca-b0d6-34cd9dbb57b8)

### HyperCeiler 设备信息

![Screenshot_2024-04-17-18-05-18-506_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/77729084/559b1e4f-9a8e-429b-b6e6-0ee0706f6c4e)

**Comment by DreammStill** [comment]
通知模糊在 cemiuier 中是存在的，而且继承到 hyperceiler 也是可以显示的，但是会造成一些问题，比如通知音量控件与其他空间重叠混乱，因此我选择了重置，所以这一部分可能没有日志，重置后没有了通知模糊相关的设置。然后就是，关于通知栏显示的图标数量也无法修改，修改不生效

**Comment by HChenX** [comment]
安卓13的hyper不维护

**Comment by mu7220** [comment]
@DreammStill 通知模糊相关设置 HyperOS 不维护，所以不显示
通知图标显示数量待看，不一定会维护

**Comment by DreammStill** [comment]
好的
