### ISSUE TITLE
🐛 [BUG] 点击“系统桌面”选项后，再点击“文件夹”选项，直接崩溃

### ISSUE THREAD

**Issue by Unbengabled** [ReChronoRain/HyperCeiler#557]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

点击“系统桌面”选项后，再点击“文件夹”选项，直接崩溃并返回到模块首页，甚至在搜索框输入与文件夹有关的选项，然后点击进入，也会崩溃

### 模块日志

[LSPosed_2024-04-17T20_39_38.262161.zip](https://github.com/ReChronoRain/HyperCeiler/files/15011029/LSPosed_2024-04-17T20_39_38.262161.zip)

### 复现步骤

```bash
第一种情况：
1. 前往 '系统桌面'
2. 点击 '文件夹'
3. 立即崩溃，然后返回到模块主界面
第二种情况：
1. 在搜索中输入与“系统桌面——文件夹”有关的选项（比如“隐藏今日推荐开关”）
2. 点击进入上面的选项
3. 立即崩溃
```

### 问题截图

此为异常跟踪App返回的结果，显示为空指针导致的问题
![Screenshot_2024-04-17-19-14-37-057_com fankes apperrorstracking](https://github.com/ReChronoRain/HyperCeiler/assets/103240622/0889f4c8-d6b8-46d3-abf6-f041a3f275ee)

### HyperCeiler 设备信息

![Screenshot_2024-04-17-20-53-14-689_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/103240622/95a647ff-2f86-48ac-b307-e0b0c3247a66)

**Comment by Unbengabled** [comment]
![Screenshot_2024-04-17-20-53-14-689_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/103240622/7aa1f713-309b-4271-aeaf-36cbd62428a1)

**Comment by Horange321** [comment]
貌似好多平板在这里崩了
