### ISSUE TITLE
🐛 [BUG] 状态栏通知图标最大数量 失效

### ISSUE THREAD

**Issue by lkslks77** [ReChronoRain/HyperCeiler#560]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

系统界面 状态栏通知图标最大数量 失效

### 模块日志

[modules_2024-04-18T20_42_58.103198.log](https://github.com/ReChronoRain/HyperCeiler/files/15026131/modules_2024-04-18T20_42_58.103198.log)

### 复现步骤

```bash
1. 前往 '系统界面-状态栏-图标'
2. 点击 '通知图标最大数量：6'
3. 重启系统界面
....
出现问题，未生效
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-18-22-17-30-283_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/113218705/210d4296-536a-4690-9496-6de2d6648bb5)

**Comment by mu7220** [comment]
@lkslks77 已修复
