### ISSUE TITLE
🐛 [BUG] 滑动桌面时，底栏背景不完全显示

### ISSUE THREAD

**Issue by violetfinancier** [ReChronoRain/HyperCeiler#563]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

滑动桌面时，底栏背景不完全显示

### 模块日志

模块未崩溃，无日志

### 复现步骤

```bash
1. 前往 '桌面 底栏'设置底栏背景，最好设置圆角（圆角会被削去，更明显）
2. 滑动桌面复现

....
出现问题
```

### 问题截图

https://github.com/ReChronoRain/HyperCeiler/assets/97280997/08087a1b-4707-44b4-82ae-76e061b66ddd

### HyperCeiler 设备信息

![Screenshot_2024-04-20-10-48-47-484_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/97280997/e9d7ca33-16c2-484b-a8fe-d5a72a489e9b)

**Comment by HChenX** [comment]
不透明度设置为1，具体让 @Sevtinge 来修
