### ISSUE TITLE
🐛 [BUG] 更新系统后系统桌面一直崩溃

### ISSUE THREAD

**Issue by foreverloveforeverdream** [ReChronoRain/HyperCeiler#566]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

更新了小米13最新1.0.24.4.15.dev开发版系统后，先是zagisk自动关闭了，手动开启重启后，桌面一直闪退，然后hyperceiler检测到就自动开启了安全模式，手动解除安全模式，并且关掉有关系统桌面的一切修改后系统桌面仍然不断闪退。
![Screenshot_2024-04-21-11-26-10-226_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/d8bc3bed-71eb-47a0-835e-bb21b65285f3)

### 模块日志

![Screenshot_2024-04-21-11-26-18-307_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/566a4c34-5e1a-4b2f-97e5-af97cb30d4cd)
![Uploading Screenshot_2024-04-21-11-26-27-523_com.sevtinge.hyperceiler.jpg…]()
[LSPosed_2024-04-21T12_47_08.926340.zip](https://github.com/ReChronoRain/HyperCeiler/files/15050687/LSPosed_2024-04-21T12_47_08.926340.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-04-21-12-48-34-886_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/705ba537-97ca-4772-84e1-e2031a628eac)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-21-12-49-25-549_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/23316634/772f0dcb-26f7-4724-a3a5-3c590d08c5ae)

**Comment by HChenX** [comment]
清空哈皮露数据，或者直接卸载，桌面还崩溃就自己找原因
