### ISSUE TITLE
系统界面崩溃

### ISSUE THREAD

**Issue by chennanye** [ReChronoRain/HyperCeiler#569]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

hook系统界面后下拉通知会直解重启系统界面，锁屏界面来通知会导致系统界面疯狂重启

### 模块日志

[LSPosed_2024-04-22T15_30_28.696286.zip](https://github.com/ReChronoRain/HyperCeiler/files/15059206/LSPosed_2024-04-22T15_30_28.696286.zip)

### 复现步骤

```bash
1.通知栏弹出消息
2.下拉通知
出现问题
系统界面崩溃
```

### 问题截图

这个不太好截图吧😶😶😶

### HyperCeiler 设备信息

![图片注释](图片链接)
![Uploading Screenshot_2024-04-22-15-34-06-318_com.sevtinge.hyperceiler.jpg…]()

**Comment by mu7220** [comment]
@chennanye 已知，~~五一放假再修~~，建议先关掉时钟指示器的动画（

**Comment by chennanye** [comment]
> @chennanye 已知，~五一放假再修~，建议先关掉时钟指示器的动画（

好的，大佬辛苦

**Comment by mu7220** [comment]
重研究了一下，大概率是米米的问题
~~感觉修不了~~

时钟指示器动画还是关了比较好
~~其他可能导致崩溃的 hook 在整理~~
