### ISSUE TITLE
🐛 [BUG] <Disable automatic closing of Mi Share is not working>

### ISSUE THREAD

**Issue by Vader77Darth** [ReChronoRain/HyperCeiler#570]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

Upon enabling "Disable automatic closing of Mi Share," it still disables itself automatically happening. This has started happening after Mi share was renamed to Xiaomi share in the latest OS update for my device.

### 模块日志

[LSPosed_2024-04-22T09_04_45.825347.zip](https://github.com/ReChronoRain/HyperCeiler/files/15059532/LSPosed_2024-04-22T09_04_45.825347.zip)

### 复现步骤

```bash
1. Enable "Disable automatic closing of Mi Share."

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-04-22-09-06-00-625_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/87441738/00d0c518-c980-4746-afc2-f343193464f7)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-22-09-06-56-823_com sevtinge hyperceiler-edit](https://github.com/ReChronoRain/HyperCeiler/assets/87441738/1af8bb77-73b3-4f22-b939-d9f3b96ca809)

**Comment by Horange321** [comment]
[HyperCeiler][W][com.miui.misound][IncreaseSamplingRate]: hook com.miui.misound.mihearingassist.h.a failed by , by: java.lang.ClassNotFoundException: com.miui.misound.mihearingassist.h

**Comment by Vader77Darth** [comment]
It's not fixed though?

**Comment by lingqiqi5211** [comment]
It's fixed, but I forgot to close the issue

**Comment by Vader77Darth** [comment]
> It's fixed, but I forgot to close the issue

It's still broken for me though.

**Comment by Sevtinge** [comment]
@Vader77Darth update

**Comment by Vader77Darth** [comment]
I already installed latest release. It didn't fix it. However, I did notice that whenever I open hyperceiler, it shows the error message saying that the module is not enabled; it is enabled and it's modifications are working (except for mi share)

**Comment by Vader77Darth** [comment]
> @Vader77Darth update

Can we open this again please? It's broken after the latest OS update again...
