### ISSUE TITLE
🐛 [BUG] <桌面点击应用 需要两到三秒才能响应打开>

### ISSUE THREAD

**Issue by kb8023** [ReChronoRain/HyperCeiler#571]
### 须知

- [X] 我确认最新版依然存在此问题.
- [x] #581
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

小米10至尊版 安卓13 澎湃1.0.2.0用的最新版西米露 然后打开软件没反应 要等个两秒才能打开 出现频率很高 试过重置模块设置依然存在这个问题 然后直到把西米露的所有作用域关闭 才没有出现 

### 模块日志

[LSPosed_2024-04-22T17_41_47.778464.zip](https://github.com/ReChronoRain/HyperCeiler/files/15061098/LSPosed_2024-04-22T17_41_47.778464.zip)

### 复现步骤

```bash
1. 前往 '桌面'
2. 点击 '微信'后卡顿三秒后才打开
QQ 文件管理 相册等都有
....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-04-22-18-07-04-274_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/78786364/6f8884f8-a56d-4b2c-afc4-25876ddd3a12)

**Comment by kongbai88** [comment]
求大佬修复

**Comment by mu7220** [comment]
桌面版本是…

**Comment by kongbai88** [comment]
> 桌面版本是…

版本： RELEASE-4.39.12.6887-01231503

**Comment by mu7220** [comment]
或许你该尝试更新一下系统桌面看看
这个有点太老了

https://nmmmea.lanzouq.com/iTe5N1v09y7i

**Comment by kongbai88** [comment]
> 或许你该尝试更新一下系统桌面看看
> 这个有点太老了
> 
> https://nmmmea.lanzouq.com/iTe5N1v09y7i

大佬您好，刚刚按照您提供桌面安装试了下，还是有这个情况 然后我尝试复现 又发现另一个操作每次都能复现 是这样操作的 锁屏后解锁 点击应用就会出现这个卡顿两三秒才启动应用 在lsp框架中不启用憨批露 重复上面操作则没有出现卡顿情况

**Comment by mu7220** [comment]
然后憨批露改用这个版本呢

https://github.com/ReChronoRain/HyperCeiler/actions/runs/8794178136/artifacts/1437907655

有延迟的话，等五一有空的时候再改了

**Comment by kongbai88** [comment]
> 然后憨批露改用这个版本呢
> 
> https://github.com/ReChronoRain/HyperCeiler/actions/runs/8794178136/artifacts/1437907655
> 
> 有延迟的话，等五一有空的时候再改了

刚刚试了 还是有这个情况 等您有空了再看看修复一下 谢谢

**Comment by kb8023** [comment]
![LSPosed_2024-04-23T14_17_25.485222.zip](https://github.com/ReChronoRain/HyperCeiler/files/15072200/LSPosed_2024-04-23T14_17_25.485222.zip)

![LSPosed_2024-04-23T14_17_30.107448.zip](https://github.com/ReChronoRain/HyperCeiler/files/15072205/LSPosed_2024-04-23T14_17_30.107448.zip)

一个模块日志 一个详细日志

**Comment by CyanDragonS** [comment]
这个问题来源于之前的bug（https://github.com/ReChronoRain/HyperCeiler/issues/391），手机管家掌管应用打开（特别是应用锁），解决办法是把手机管家APP后台锁定。已经一个月不更新了，不知道大佬们准备什么时候修复这个很很严重的问题。

**Comment by kb8023** [comment]
> 这个问题来源于之前的bug（https://github.com/ReChronoRain/HyperCeiler/issues/391）
> 手机管家掌管应用打开（特别是有应用锁的），临时解决办法是把手机管家APP后台锁定。已经一个月不更新了，不知道大佬们准备什么时候修复这个很很严重的问题。

作者说五一修复

**Comment by HChenX** [comment]
重复issued
