### ISSUE TITLE
🐛 [BUG] 开启抽屉模糊后在抽屉内打开 app 再用手势回到桌面会导致桌面崩溃 Back to screen with gestures after opening an app in drawer will cause the launcher to crash.

### ISSUE THREAD

**Issue by Keritial** [ReChronoRain/HyperCeiler#572]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

开启 HyperCeiler 的抽屉模糊后，在抽屉内打开 app，再用手势回到桌面会导致桌面崩溃。

Enable drawer blur effects, and then back to screen with gestures, after opening an app in drawer, will cause the launcher to crash.

### 模块日志

[verbose_2024-04-21T22:15:14.22742.log](https://github.com/ReChronoRain/HyperCeiler/files/15065007/verbose_2024-04-21T22.15.14.22742.log)

### 复现步骤

```bash
1. 在 设置 -> 主屏幕 -> 系统导航 中启用 “手势”，
在 设置 -> 主屏幕 -> 主屏幕 中启用 “抽屉”；
2. 在 HyperCeiler -> 系统桌面 -> 抽屉 中启用 “启用所有应用程序容器视图模糊”；
3. 打开抽屉；
4. 随便打开一个 app；
4. 用上滑手势返回主屏幕。

系统桌面会崩溃。

1. Enable "Gesture" in Settings -> Home screen -> System navigation.
Enable "With App Drawer" in Settings -> Home screen -> Home screen.
2. Enable "Enable All Apps Container View Blur" in HyperCeiler -> System launcher -> Drawer.
3. Open app drawer.
4. Open a app.
4. Back to home screen by swiping up.

The system launcher should crash.
```

### 问题截图

![Screenshot_2024-04-22-23-17-05-856_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/50075277/3f4131bc-062d-4a4e-89b9-b31c2ca10c77)
![Screenshot_2024-04-22-23-17-12-941_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/50075277/558617b5-44e8-4e1a-a714-06d4f2430cdd)
![Screenshot_2024-04-22-23-17-26-491_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50075277/f4620958-18a8-4a0f-b368-f8dc840ca941)
![Screenshot_2024-04-22-23-20-58-205_com miui home](https://github.com/ReChronoRain/HyperCeiler/assets/50075277/6a9141b6-0b59-411b-96d2-6e645a675fab)

### HyperCeiler 设备信息

![Screenshot_2024-04-22-22-56-27-550_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50075277/fd2be793-6efe-46c4-9fdc-6f15829fbdbd)

**Comment by mu7220** [comment]
桌面版本是…
目前打算五一把桌面整个模糊层重构一下，尽量使用高级材质来优化模糊

**Comment by HChenX** [comment]
> 桌面版本如下，
> 
> The launcher version is as follows,
> 
> ![Screenshot_2024-04-23-22-22-04-709_com miui securitycenter](https://private-user-images.githubusercontent.com/50075277/324871501-5e7c17e0-7b02-48d8-807d-a799b234ffd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODM0ODQsIm5iZiI6MTcxMzg4MzE4NCwicGF0aCI6Ii81MDA3NTI3Ny8zMjQ4NzE1MDEtNWU3YzE3ZTAtN2IwMi00OGQ4LTgwN2QtYTc5OWIyMzRmZmQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYTNiNzE0MGEzZmNlN2Q5OWM3Yjg5Y2MxMDE1ZWE2ZjAzYTQxNDUxZTY5MTM0MjlkNDBiMGFjNDM4NWExMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHUQNRp-QMiQShbOdVKycRhFcbqNHQ51npqzEeYp6a0)
> 
> 另，所以说不打算修这个bug，而是用高级材质替换模糊吗？那就不用 reopen 这个 issue 了？
> 
> Also, is this bug not going to be fixed, as it is planned to be replaced with Advanced Textures? Does it need to reopen this issue?

miui用原模糊不会崩溃，hyper用高级材质是更好的选择

**Comment by Keritial** [comment]
好的，谢谢。

Understood. Thanks.
