### ISSUE TITLE
干掉自启动优化

### ISSUE THREAD

**Issue by kb8023** [ReChronoRain/HyperCeiler#573]
### 需求内容

![Screenshot_2024-04-23-19-57-14-450_com miui securitycenter-edit](https://github.com/ReChronoRain/HyperCeiler/assets/78786364/8a7935af-f487-43bc-a71d-89b09fe3304a)
如图圈中所示 每次重启 就把我的小米运动健康的自启动给取消了 希望可以增加干掉自启动智能优化

### 实现思路&截图

好吧 我没思路 可以参考以前miui的代码 更新了澎湃才有这玩意

### 简单例子

免得需要的自启动被莫名的关闭了

**Comment by kb8023** [comment]
如果有可以实现的机会 希望增加

**Comment by HChenX** [comment]
重复is

**Comment by Vstory** [comment]
这TM越来越“智能”了，我的手机我自己不能做主了
