### ISSUE TITLE
💡 [需求] <add option to enable folding notification>

### ISSUE THREAD

**Issue by naokoshoto** [ReChronoRain/HyperCeiler#574]
### 需求内容

It was a thing back in MIUI 13 that enables grouping unimportant notification to a single section, unfortunately I don't have any footage of how does it looks inside, and I don't know if it would work on HyperOS

### 实现思路&截图

![IMG_20240423_215839_404](https://github.com/ReChronoRain/HyperCeiler/assets/25972975/e7c2f414-bebf-425a-aee0-ab23ed028e3a)
![IMG_20240423_215901_477](https://github.com/ReChronoRain/HyperCeiler/assets/25972975/66bab896-79a6-4a94-9899-5a104a2e2781)

### 简单例子

Add toggle to enable "Unimportant Notification" grouping / Fold Notification to SystemUI and Notificaiton so it can enable those

Previous known implementation: 

https://t.me/XiaomiEUAppsGroup/268363

**Comment by HChenX** [comment]
视频中修改地方过多，不适合hook，建议自己反编译修改。
