### ISSUE TITLE
🐛 [BUG] 不会自动申请root权限

### ISSUE THREAD

**Issue by newton-miku** [ReChronoRain/HyperCeiler#576]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

不会自动申请root权限，magisk中也无法找到该软件的授权选项（使用magisk为delta，版本26400，hyperceiler版本为2.4.141_1406032）

### 模块日志

[LSPosed_2024-04-24T13_28_50.439940.zip](https://github.com/ReChronoRain/HyperCeiler/files/15088233/LSPosed_2024-04-24T13_28_50.439940.zip)

### 复现步骤

```bash
安装后即出现
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![Screenshot_2024-04-24-13-31-59-490_com sevtinge h](https://github.com/ReChronoRain/HyperCeiler/assets/29966140/7b6d3a89-c072-4a41-8a1d-ef35a4a21400)

**Comment by newton-miku** [comment]
不会自动申请root权限会导致WiFi密码无法查看、无法重启作用域等，所用系统为小米官方推送系统

**Comment by mu7220** [comment]
@newton-miku 确定不是你没给它加 su 请求白名单？

**Comment by newton-miku** [comment]
magisk delta我没有使用sulist模式，仅修改magisk管理器的包名

**Comment by newton-miku** [comment]
已解决，shamiko模块启用了白名单模式，禁用该模块后重启系统即可看到权限请求
