### ISSUE TITLE
💡 [需求] 新增相册编辑插件管理“AI编辑大模型”

### ISSUE THREAD

**Issue by ChocolateSerein** [ReChronoRain/HyperCeiler#577]
### 需求内容

在小米相册-编辑（可能是）中添加插件管理，插件管理中有“AI编辑大模型”

### 简单例子

![Image_1713961907406](https://github.com/ReChronoRain/HyperCeiler/assets/108963981/f0116c81-23c7-4816-ba34-695cd0b62501)
![Image_1713961890050](https://github.com/ReChronoRain/HyperCeiler/assets/108963981/55b8b0d5-67ab-48db-a375-0667171f8c0c)

**Comment by mu7220** [comment]
@ChocolateSerein 不做，受芯片限制，只有对应芯片可正常使用
