### ISSUE TITLE
💡 [需求] <长按「省电模式」磁贴跳转至耗电排行（「省电与电池」页）>

### ISSUE THREAD

**Issue by hrsthrt74** [ReChronoRain/HyperCeiler#580]
### 需求内容

记得很久以前用类原生 Android，电源磁贴的逻辑就是单击切换省电模式，长按跳转耗电排行，在 HyperOS/MIUI 上长按则会跳转到省电模式设置，希望能做到更改此逻辑

### 简单例子

「省电模式」磁贴：
- 单击：切换省电模式
- 长按：跳转至耗电排行（「省电与电池」页，`com.miui.securitycenter/com.miui.powercenter.PowerMainActivity`）

**Comment by HChenX** [comment]
你长按性能模式不就行了）

**Comment by Horange321** [comment]
> 你长按性能模式不就行了）

超级省电也可以
