### ISSUE TITLE
💡 [需求] <为Pad机型去除设置中"应用布局优化"机型限制>

### ISSUE THREAD

**Issue by sothx** [ReChronoRain/HyperCeiler#583]
### 需求内容

已确认Android14下的Hyper OS For Pad的`设置`上均有"应用布局优化"相关UI层代码，但是目前该功能机型写死仅提供给Xiaomi Pad 6 Max(yudi)和Xiaomi Mix Fold 3(babylon)，恳求可以去除该功能的机型限制。(不会写hook QwQ)
以下是应用布局优化的UI界面：
![c538b9897845d6f6eb176dc04b4bf432](https://github.com/ReChronoRain/HyperCeiler/assets/19142616/ade7b4f9-a030-46b9-a687-f1653c790e3d)

### 实现思路&截图

该功能限制可能位于`com.android.settings.utils`下的`SettingsFeatures.java`，有个名叫`shouldShowAutoUIModeSetting`的函数:
```java
public static boolean shouldShowAutoUIModeSetting() {
        String str = Build.DEVICE;
        return SystemProperties.getBoolean("persist.miui.auto_ui_enable", false) && ("yudi".equals(str) || "babylon".equals(str));
}
```
建议可修改为
```java
public static boolean shouldShowAutoUIModeSetting() {
        String str = Build.DEVICE;
        return SystemProperties.getBoolean("persist.miui.auto_ui_enable", false)
}
```
或也可以返回true。

### 简单例子

"应用布局优化"实际能对一部分布局、图片和文字变形严重的应用，在平板下进行适配优化。
例如`酷狗音乐概念版`:
[开启前]
![c321deea9178baa4f179ce8e6e5814fa](https://github.com/ReChronoRain/HyperCeiler/assets/19142616/30e36b33-34df-4182-a421-d2ee3d10421d)
[开启后]
![51c1a97d8336edbe6183ab715da5b0b9_720](https://github.com/ReChronoRain/HyperCeiler/assets/19142616/2d91408d-f7e7-4d94-b6af-5e8207f91c7f)

该功能还需要依赖对应的规则文件才会生效，目前这个规则文件分别位于:
`/product/etc/autoui_rule.xml`(ROM内置规则，目前仅yudi、babylon和sheng有内置该规则)
`/data/system/cloudFeature_autoui_list.xml`(云控规则，任何Android 13/14 下的Hyper OS For Pad存在该文件且`persist.miui.auto_ui_enable`为开启时，都会生效，但是Android 13下的Hyper OS For Pad并没发现设置中有"应用布局优化"的相关UI层代码(米板5/5pro和5pro 5g都是A13的Hyper OS)，不过没影响该功能生效)
因此，我有写单独的Magisk模块在维护这个功能的适配规则:
[https://github.com/sothx/mipad-magic-window](https://github.com/sothx/mipad-magic-window)

**Comment by HChenX** [comment]
如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？

**Comment by sothx** [comment]
> 如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？

解锁入口后，且`persist.miui.auto_ui_enable`为true，设置里面就能正常显示`应用布局优化`，也能正常点开界面，不需要我的面具模块配合。（面具模块只是做填充应用适配规则这样w）

虽然说这个功能也有云控规则的说法，但是找了用6max的朋友，似乎就从未下发过`应用布局优化`的云控规则，如果不自己额外把规则填进去，就只是解锁了UI（大概是这种情况QwQ）

**Comment by HChenX** [comment]
> > 如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？
> 
> 解锁入口后，且`persist.miui.auto_ui_enable`为true，设置里面就能正常显示`应用布局优化`，也能正常点开界面，不需要我的面具模块配合。（面具模块只是做填充应用适配规则这样w） ![a134cbfe4d52b720aaa0ca1d4f7c21a9](https://private-user-images.githubusercontent.com/19142616/326175693-d2c68545-bc80-4f55-b66d-6b72279c947b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTkzNjEsIm5iZiI6MTcxNDIxOTA2MSwicGF0aCI6Ii8xOTE0MjYxNi8zMjYxNzU2OTMtZDJjNjg1NDUtYmM4MC00ZjU1LWI2NmQtNmI3MjI3OWM5NDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDExNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjkxZjE4MGVhMTdjODgzYzA1NTY1MjNhYTNhYzFjZjgzOGU1ODdhOTIwNDAwNGI4MmRkMDNlMDEyMTlhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PSfW9OXakQxa_ldtPCFfoQYQn3jv5sur4EwOA3b_Hwc)
> 
> 虽然说这个功能也有云控规则的说法，但是找了用6max的朋友，似乎就从未下发过`应用布局优化`的云控规则，对于ROM里面没有内置规则的米板，如果不自己手动或者类似我面具模块那样额外把规则填进去，就相当于只是解锁了`应用布局优化`的UI（大概是这种情况QwQ）

我写个pr，你有条件编译吗？拉下来试试

**Comment by sothx** [comment]
> > > 如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？
> > 
> > 
> > 解锁入口后，且`persist.miui.auto_ui_enable`为true，设置里面就能正常显示`应用布局优化`，也能正常点开界面，不需要我的面具模块配合。（面具模块只是做填充应用适配规则这样w） ![a134cbfe4d52b720aaa0ca1d4f7c21a9](https://private-user-images.githubusercontent.com/19142616/326175693-d2c68545-bc80-4f55-b66d-6b72279c947b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTkzNjEsIm5iZiI6MTcxNDIxOTA2MSwicGF0aCI6Ii8xOTE0MjYxNi8zMjYxNzU2OTMtZDJjNjg1NDUtYmM4MC00ZjU1LWI2NmQtNmI3MjI3OWM5NDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDExNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjkxZjE4MGVhMTdjODgzYzA1NTY1MjNhYTNhYzFjZjgzOGU1ODdhOTIwNDAwNGI4MmRkMDNlMDEyMTlhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PSfW9OXakQxa_ldtPCFfoQYQn3jv5sur4EwOA3b_Hwc)
> > 虽然说这个功能也有云控规则的说法，但是找了用6max的朋友，似乎就从未下发过`应用布局优化`的云控规则，对于ROM里面没有内置规则的米板，如果不自己手动或者类似我面具模块那样额外把规则填进去，就相当于只是解锁了`应用布局优化`的UI（大概是这种情况QwQ）
> 
> 我写个pr，你有条件编译吗？拉下来试试

好！

**Comment by HChenX** [comment]
> > > > 如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？
> > > 
> > > 
> > > 解锁入口后，且`persist.miui.auto_ui_enable`为true，设置里面就能正常显示`应用布局优化`，也能正常点开界面，不需要我的面具模块配合。（面具模块只是做填充应用适配规则这样w） ![a134cbfe4d52b720aaa0ca1d4f7c21a9](https://private-user-images.githubusercontent.com/19142616/326175693-d2c68545-bc80-4f55-b66d-6b72279c947b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTkzNjEsIm5iZiI6MTcxNDIxOTA2MSwicGF0aCI6Ii8xOTE0MjYxNi8zMjYxNzU2OTMtZDJjNjg1NDUtYmM4MC00ZjU1LWI2NmQtNmI3MjI3OWM5NDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDExNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjkxZjE4MGVhMTdjODgzYzA1NTY1MjNhYTNhYzFjZjgzOGU1ODdhOTIwNDAwNGI4MmRkMDNlMDEyMTlhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PSfW9OXakQxa_ldtPCFfoQYQn3jv5sur4EwOA3b_Hwc)
> > > 虽然说这个功能也有云控规则的说法，但是找了用6max的朋友，似乎就从未下发过`应用布局优化`的云控规则，对于ROM里面没有内置规则的米板，如果不自己手动或者类似我面具模块那样额外把规则填进去，就相当于只是解锁了`应用布局优化`的UI（大概是这种情况QwQ）
> > 
> > 
> > 我写个pr，你有条件编译吗？拉下来试试
> 
> 好！

已经pr，可以拉下来试试，默认开启。日志过滤ShowAutoUIMode

**Comment by sothx** [comment]
> > > > > 如果解锁了这个“应用布局优化”入口，直接设置会生效吗？还是需要你的面具模块配合？
> > > > 
> > > > 
> > > > 解锁入口后，且`persist.miui.auto_ui_enable`为true，设置里面就能正常显示`应用布局优化`，也能正常点开界面，不需要我的面具模块配合。（面具模块只是做填充应用适配规则这样w） ![a134cbfe4d52b720aaa0ca1d4f7c21a9](https://private-user-images.githubusercontent.com/19142616/326175693-d2c68545-bc80-4f55-b66d-6b72279c947b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTkzNjEsIm5iZiI6MTcxNDIxOTA2MSwicGF0aCI6Ii8xOTE0MjYxNi8zMjYxNzU2OTMtZDJjNjg1NDUtYmM4MC00ZjU1LWI2NmQtNmI3MjI3OWM5NDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDExNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjkxZjE4MGVhMTdjODgzYzA1NTY1MjNhYTNhYzFjZjgzOGU1ODdhOTIwNDAwNGI4MmRkMDNlMDEyMTlhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PSfW9OXakQxa_ldtPCFfoQYQn3jv5sur4EwOA3b_Hwc)
> > > > 虽然说这个功能也有云控规则的说法，但是找了用6max的朋友，似乎就从未下发过`应用布局优化`的云控规则，对于ROM里面没有内置规则的米板，如果不自己手动或者类似我面具模块那样额外把规则填进去，就相当于只是解锁了`应用布局优化`的UI（大概是这种情况QwQ）
> > > 
> > > 
> > > 我写个pr，你有条件编译吗？拉下来试试
> > 
> > 
> > 好！
> 
> 已经pr，可以拉下来试试，默认开启。日志过滤ShowAutoUIMode

谢谢焕晨ww，刚刚试了是可以的，安装pr编译后的debug版，且设置`persist.miui.auto_ui_enable`为true后能正常显示`应用布局优化`。这个prop似乎可以在开启该hook的时候顺便加上？
![b8a97b1b8a9a7a1e881932a5085c627a](https://github.com/ReChronoRain/HyperCeiler/assets/19142616/894bb2b2-966d-455f-be70-7eccba02549d)
