### ISSUE TITLE
💡 [需求] <在小米换机上增加迁移所有数据的开关>

### ISSUE THREAD

**Issue by Mc-user1688** [ReChronoRain/HyperCeiler#591]
### 需求内容

因为部分游戏数据有些压根无法转移，得重新下载就很麻烦
所以能不能在增加一个开关？

### 简单例子

给换机应用添加迁移所有数据开关

**Comment by HChenX** [comment]
一直不知道这种功能如果导致数据损坏了，是找小米还是找我们的事，所以不做
