### ISSUE TITLE
💡 [需求] 希望能恢复短信通知弹窗已读功能按钮

### ISSUE THREAD

**Issue by ghcsd** [ReChronoRain/HyperCeiler#593]
### 需求内容

如题，~~记得MIUI时期~~收到一般消息是有三个按钮的分别是`已读`、`删除`和`回复`，现在只剩下后两个了。

_编辑：卸载短信更新到版本**15.0.0.8**就能恢复了_

### 实现思路&截图
原来显示效果：
![Screenshots](https://github.com/ReChronoRain/HyperCeiler/assets/32384764/7b75b5a2-7403-4af6-b04e-3771e1438865)

### 简单例子

希望能恢复`已读`按钮

**Comment by HChenX** [comment]
用处不大

**Comment by xuangeyouneihan** [comment]
既然作者不准备开发这个功能了，新版rom干脆直接把内置短信的版本升到了不带已读按钮的新版，且15.0.0.8版的短信安装包不太容易找到，那我在这放一下15.0.0.8版短信安装包吧（从红米k50pro的澎湃os1.0.2.0版rom中提取），方便后面看到这个issue的人安装。下载后需要去除后面的txt扩展名保留apk扩展名

[MiuiMms.apk.txt](https://github.com/user-attachments/files/17555135/MiuiMms.apk.txt)

**Comment by xuangeyouneihan** [comment]
既然作者不准备开发这个功能了，新版rom干脆直接把内置短信的版本升到了不带已读按钮的新版，且15.0.0.8版的短信安装包不太容易找到，那我在这放一下15.0.0.8版短信安装包吧（从红米k50pro的澎湃os1.0.5.0版rom中提取），方便后面看到这个issue的人安装。下载后需要去除后面的txt扩展名保留apk扩展名

[MiuiMms.apk.txt](https://github.com/user-attachments/files/17555135/MiuiMms.apk.txt)

**Comment by xuangeyouneihan** [comment]
既然作者不准备开发这个功能了，新版rom干脆直接把内置短信的版本升到了不带已读按钮的新版，且15.0.0.8版的短信安装包不太容易找到，那我在这放一下15.0.0.8版短信安装包吧（从红米k50pro的澎湃os1.0.5.0版rom中提取），方便后面看到这个issue的人安装。下载后需要去除后面的txt扩展名保留apk扩展名

[MiuiMms.apk.txt](https://github.com/user-attachments/files/17555193/MiuiMms.apk.txt)
