### ISSUE TITLE
🐛 [BUG] <Debug日志功能失效>

### ISSUE THREAD

**Issue by LostMyMind** [ReChronoRain/HyperCeiler#604]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

与#535 一致，将日志输出调整为debug后重启软件自动恢复为info，给予ROOT权限后依旧。
关键是我还遇到了随机断网的BUG，需要debug日志来排查，但是现在debug日志调不出来，很难受。

### 模块日志

[LSPosed_2024-05-04T13_23_19.936975.zip](https://github.com/ReChronoRain/HyperCeiler/files/15208031/LSPosed_2024-05-04T13_23_19.936975.zip)

https://github.com/ReChronoRain/HyperCeiler/assets/57167544/566b303c-5eb2-48bb-afa3-2ee31205c6f3

### 复现步骤

```bash
1. 前往 '点击HyperCeiler'
2. 点击 '设置'
3. 选择日志输出等级为'Debug'
4. 重启设备
5. 打开HyperCeiler→设置→日志输出等级仍然是Info
```

### 问题截图

没截图，“模块日志”那里传了视频。

### HyperCeiler 设备信息

![3237eb93c11b68413c6f4803ee533ead](https://github.com/ReChronoRain/HyperCeiler/assets/57167544/36d4473a-99b8-4139-a524-7906508648f1)

**Comment by Sevtinge** [comment]
c3cbb6bdc43e5d3c65dd177e175ddff9f06b7cc1
