### ISSUE TITLE
🔌 [移植] <自定义控制中心磁贴颜色>

### ISSUE THREAD

**Issue by LostMyMind** [ReChronoRain/HyperCeiler#605]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

请求移植米客关于调整控制中心磁贴颜色样式的功能，该功能可以调整控制中心磁贴的前景色和背景色，可以做到不使用修改版系统界面组件或者主题的情况下diy磁贴颜色。
米客功能入口：系统-控制中心-主题样式配置-已启用磁贴。

### 相关描述&截图

第一张图是米客的功能入口，第二张图是功能页面，第三张图是功能生效后的效果（设置为背景色为白色，前景色为黑色）。

![e61ec6809c217e7113c3c42ed8b90c91](https://github.com/ReChronoRain/HyperCeiler/assets/57167544/4c20244c-e9bc-4f86-b28a-e3e3a21e319e)
![36a1545322cae5c51f8cbe3adb9b8bec](https://github.com/ReChronoRain/HyperCeiler/assets/57167544/58eb3e0d-4af2-42be-a0d0-f6ea1c84c5d3)
![5df467110127f7ca9360f856d4d3929e](https://github.com/ReChronoRain/HyperCeiler/assets/57167544/66a85506-aa65-4179-ae55-66be5df9b8a9)

**Comment by HChenX** [comment]
非移植，为自写。
