### ISSUE TITLE
💡 [需求] 增加触发执行焕新存储的按钮

### ISSUE THREAD

**Issue by Choicc** [ReChronoRain/HyperCeiler#610]
### 需求内容

焕新存储功能在满足官方说明(如下图)的条件下还是无法触发,希望增加个手动触发焕新存储的按钮

### 相关截图

![image](https://github.com/ReChronoRain/HyperCeiler/assets/24811393/1ad3f3dc-3ab5-4c16-990e-beaf4b519164)

### 简单例子

焕新存储功能触发条件过于玄学,根据官方说法,如果是夜班用户则难以触发,希望增加个手动触发焕新存储的按钮,让用户可以自主选择在手机空闲时触发

**Comment by HChenX** [comment]
玄学去找小米

**Comment by Choicc** [comment]
> 玄学去找小米

又不是说修小米的bug,提的需求建议是增加手动触发的功能,如果超出提需求的范围可以删

**Comment by mu7220** [comment]
先说一下，issue 不是许愿池
说完了

没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断

总之就是不会帮米米擦屁股，让米米自己修回去

**Comment by Choicc** [comment]
相关需求场景简单例子里也说明了一下,主要是想要一个可以在自己认为的手机空闲时间里触发焕新存储。我不清楚实现方式及难度,如果这个issue都算许愿的话,建议关闭issue提需求功能。

**Comment by Choicc** [comment]
> 先说一下，issue 不是许愿池 说完了
> 
> 没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断
> 
> 总之就是不会帮米米擦屁股，让米米自己修回去

如果你们站开发者角度,认为用户提的需求无法实现或者是给小米修bug就是许愿的话,建议关闭issue提需求的功能

**Comment by heinu123** [comment]
> > 先说一下，issue 不是许愿池 说完了
> > 没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断
> > 总之就是不会帮米米擦屁股，让米米自己修回去
> 
> 如果你们站开发者角度,认为用户提的需求无法实现或者是给小米修bug就是许愿的话,建议关闭issue提需求的功能

为什么一定要帮小米修bug，是小米给开发者们发工资了还是你给开发者发工资了？
真把自己当甲方了

**Comment by HChenX** [comment]
> > 先说一下，issue 不是许愿池 说完了
> > 
> > 没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断
> > 
> > 总之就是不会帮米米擦屁股，让米米自己修回去
> 
> 如果你们站开发者角度,认为用户提的需求无法实现或者是给小米修bug就是许愿的话,建议关闭issue提需求的功能

你提issue不就是希望模块开发者实现小米没有实现的功能吗？这本质上不是许愿吗？那你怎么不去找小米许愿让他加个一键触发？碎片整理不是什么新技术，用处也可能不大，和我们实现的付出不成正比，而且这种逻辑问题本身就是小米考虑欠缺，我们又不拿小米工资为什么帮他完善。你要是建议我们关闭issue那我们直接停更不更好？

**Comment by heinu123** [comment]
> > 先说一下，issue 不是许愿池 说完了
> > 没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断
> > 总之就是不会帮米米擦屁股，让米米自己修回去
> 
> 如果你们站开发者角度,认为用户提的需求无法实现或者是给小米修bug就是许愿的话,建议关闭issue提需求的功能

本模块是让MIUI & HyperOS更好用，而不是再给小米擦屁股或者帮小米添加新功能。如果你有能力你可以自习fork项目开发

**Comment by Choicc** [comment]
> > > 先说一下，issue 不是许愿池 说完了
> > > 没有手动触发的方式，就算逆出来实现，如果发现底层条件没有支持，执行也会中断
> > > 总之就是不会帮米米擦屁股，让米米自己修回去
> > 
> > 
> > 如果你们站开发者角度,认为用户提的需求无法实现或者是给小米修bug就是许愿的话,建议关闭issue提需求的功能
> 
> 你提issue不就是希望模块开发者实现小米没有实现的功能吗？这本质上不是许愿吗？那你怎么不去找小米许愿让他加个一键触发？碎片整理不是什么新技术，用处也可能不大，和我们实现的付出不成正比，而且这种逻辑问题本身就是小米考虑欠缺，我们又不拿小米工资为什么帮他完善。你要是建议我们关闭issue那我们直接停更不更好？

你们这里issue本身就有提需求建议的功能,我提了个需求,我不清楚你们能否实现,不清楚是否为小米的bug。在你们这里我变成了许愿让你们给小米擦屁股了。

**Comment by Sevtinge** [comment]
其实很简单，给开发者每人USDT$1000.00立马帮你实现
