### ISSUE TITLE
💡 [需求] <标题>充电阈值修改

### ISSUE THREAD

**Issue by rangxuefeiyihuier** [ReChronoRain/HyperCeiler#611]
### 需求内容

默认充电到100%停止充电对电池不友好，能不能开发新功能，修改充电阈值，比如充电到80%、85%、90%停止充电，最好能自定义数值，谢谢！

### 简单例子

充到90%停止充电

**Comment by HChenX** [comment]
magisk模块可以做到，scene也可以，本模块不写

**Comment by rangxuefeiyihuier** [comment]
就是不想装两个软件，同时开的软件越多越费电，模块儿没找到。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 下午5:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReChronoRain/HyperCeiler] 💡 [需求] <标题&gt;充电阈值修改 (Issue #611)




 
magisk模块可以做到，scene也可以，本模块不写

**Comment by Sevtinge** [comment]
建议使用scene，暂时没有计划开发此内容

**Comment by Sevtinge** [comment]
其实官方也有这个功能，就在电池保护中，最高80%

**Comment by zjw2017** [comment]
zjw2017 comments shit and says Practice more dishes
