### ISSUE TITLE
💡 [需求] 磁貼高級模糊

### ISSUE THREAD

**Issue by PL7963** [ReChronoRain/HyperCeiler#612]
### 需求内容

能夠讓自訂義磁貼有高級模糊染色效果

### 实现思路&截图

![Screenshot_2024-05-07-07-28-50-971_com miui gallery](https://github.com/ReChronoRain/HyperCeiler/assets/44529370/7f886e0a-7120-48e6-aeb3-63723bdca9c7)

### 简单例子

讓磁貼能夠有類似音量條跟亮度條能依據背景染色

**Comment by HChenX** [comment]
磁贴颜色并不适合高级模糊，如何有其他方法我再写。

**Comment by PL7963** [comment]
> 磁贴颜色并不适合高级模糊，如何有其他方法我再写。

如果把高级模糊独立成一个选项，跟磁贴颜色分开会是一个好主意吗？

**Comment by HChenX** [comment]
> > 磁贴颜色并不适合高级模糊，如何有其他方法我再写。
> 
> 如果把高级模糊独立成一个选项，跟磁贴颜色分开会是一个好主意吗？

颜色是Drawable附加在view上的，应该会覆盖模糊。
