### ISSUE TITLE
🐛 [BUG] <Cannot disable miui core packages>

### ISSUE THREAD

**Issue by KittyArk** [ReChronoRain/HyperCeiler#613]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

手机管家的应用状态控制对某些miui系统应用失效

我在 [Brevent issues](https://github.com/brevent/Brevent/issues/902) 搜索到了同样的问题还有可能的解决方法

### 模块日志

[LSPosed_2024-05-10T11_28_42.712955.zip](https://github.com/ReChronoRain/HyperCeiler/files/15270243/LSPosed_2024-05-10T11_28_42.712955.zip)

[ 2024-05-10T11:24:41.224    10257: 30429: 30429 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-05-10T11:24:42.301    10257: 30429: 30429 I/LSPosed-Bridge  ] [HyperCeiler][I][com.android.providers.downloads.ui]: versionName = 123.05.19.806008, versionCode = 1230519608
[ 2024-05-10T11:24:46.758     1000: 26034: 26034 I/LSPosed-Bridge  ] [HyperCeiler][W][][AppDisable]: java.lang.SecurityException: Cannot disable miui core packages.
[ 2024-05-10T11:24:47.761     1000:  3581:  5592 I/LSPosed-Bridge  ] [ INFO] 05-10 11:24:47 (ZygoteArgsHook) @startViaZygote force mount data: 10211 com.miui.core
[ 2024-05-10T11:24:48.332     1000:  3581:  5592 I/LSPosed-Bridge  ] [ INFO] 05-10 11:24:48 (ZygoteArgsHook) @startViaZygote force mount data: 10151 com.miui.greenguard

### 复现步骤

```bash
1. 前往 '设置→应用管理→应用商店'
2. 点击 '停用'
出现问题
```

### 问题截图

无

### HyperCeiler 设备信息

![Screenshot_2024-05-10-12-16-12-691_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/41221702/c4aaf00b-4afe-483b-ab87-11c3722a3333)

**Comment by HChenX** [comment]
功能使用了小米自带的核心应用白名单，被小米认为是核心应用的软件不会被禁用。

**Comment by HChenX** [comment]
系统框架有一个 禁用是否运行禁用app校验  功能打开应该就可以了。
