### ISSUE TITLE
💡 [需求] 部分应用的国内/国际版标识切换

### ISSUE THREAD

**Issue by YukieMiona** [ReChronoRain/HyperCeiler#617]
### 需求内容

为部分应用单独添加国内/国际版标识相互切换，以（有可能地）增加功能/减少广告。通过修改 prop 全局切换成国内/国际版的影响较大。

### 实现思路&截图

IS_INTERNATIONAL_BUILD，这个值或许可以随着选择进行切换？hook 系统设置的 InternationalBuild.java 只有简单的国内版标识向国际版的转换。我一年前曾经手动将 true 改成 false 就实现了从国际版设置界面变成国内版。
抱歉如果我的记忆出错，但总之，由此，我预计大概率存在很简单的按钮切换的实现方法。我希望所需要的精力会比我写下这则 issue 所花费的少。

### 简单例子

对于系统设置：使“国际版本设置界面”变为“国内/国际版本设置界面切换”。界面UI、功能图标有些许变化。
对于小米账号：国际版标识限制了 查找设备 的使用。
其他未知。

**Comment by Sevtinge** [comment]
这个很好写，你想要哪些应用存在此功能？

**Comment by FurryRbl** [comment]
想法不错，但是感觉作为一个新的模块而不是包含到西米露也许会更好🤔？

**Comment by Sevtinge** [comment]
> 想法不错，但是感觉作为一个新的模块而不是包含到西米露也许会更好🤔？

好像也是，需要的话直接激活作用域就行

**Comment by FurryRbl** [comment]
应该直接Hook这边的就可以了，但是怎么感觉哪里不对劲。。。：
https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/util/Locale.java;l=1374;drc=07094b1b11172ef1041a0c4a7ad6fd0193f0989f

**Comment by Sevtinge** [comment]
已经完成了，如果你需要国际版标识切换中国版，再call我就行，我帮你打包一份。https://github.com/Sevtinge/Vojazento/releases/tag/100
