### ISSUE TITLE
🐛 [BUG] 禁用风险检测功能异常

### ISSUE THREAD

**Issue by scruel** [ReChronoRain/HyperCeiler#637]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

1. 启用“禁用风险检测”后尝试安装应用
2. 仍然会显示风险检测中，其他包管理组件的功能目测正常

### 模块日志

无日志版 LSP

**Comment by lightsummer233** [comment]
@scruel ？6

**Comment by lightsummer233** [comment]
@scruel no log no fix
