### ISSUE TITLE
💡 [需求] 在HyperOS上使用MIUI的小窗手势

### ISSUE THREAD

**Issue by XingLiAl** [ReChronoRain/HyperCeiler#642]
### 需求内容

在HyperOS上使用MIUI的小窗手势

### 简单例子

比如小窗和贴边小窗的切换，MIUI的逻辑是把小窗拖到边角变为贴边小窗，而新版系统的逻辑则是对小窗进行缩放，感觉旧版本的逻辑会比较好一些

**Comment by HChenX** [comment]
直接回退Miui不就行了？
