### ISSUE TITLE
🐛 [BUG]  不知道哪个开关 会影响到通知权限弹窗回归原生样式。

### ISSUE THREAD

**Issue by rainalong** [ReChronoRain/HyperCeiler#649]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

一开始以为是第三方rom的问题，然后三清换过了个第三方rom，问题依旧，再排查，发现是hyperceiler模块导致的，情况如下：
通知权限弹窗会从hyperos的风格样式变回到安卓原生风格样式，就像关掉了开发者选项里的系统优化一样，但是只有通知权限的弹窗会变，其它的没有发现有问题。手机重启后，弹窗界面恢复正常，等待一段时间或使用一段时间后（观测了一次大概是30分钟出现，但不确定是否每次都是这个时间），弹窗又会变回原生安卓风格，在变换的一瞬间如果开着微信，微信会闪退，再去开个有通知权限弹窗的app，就变回原生了。把hyperceiler模块禁用再重启手机，无论过多久弹窗依旧正常。

### 模块日志

[LSPosed_2024-05-27T10_02_38.961896.zip](https://github.com/ReChronoRain/HyperCeiler/files/15449998/LSPosed_2024-05-27T10_02_38.961896.zip)
[LSPosed_2024-05-27T10_02_47.351403.zip](https://github.com/ReChronoRain/HyperCeiler/files/15449999/LSPosed_2024-05-27T10_02_47.351403.zip)
[HyperCeiler_settings_backup_2024-05-27-10_05_00.json](https://github.com/ReChronoRain/HyperCeiler/files/15450003/HyperCeiler_settings_backup_2024-05-27-10_05_00.json)
一份模块日志 一份详细日志 一份配置备份文件

### 复现步骤

```bash
1. 导入配置
2. 等待30分钟左右即可

....
出现问题
```

### 问题截图

![2c5d5fe11c3ceb1da3b16e2bee04890](https://github.com/ReChronoRain/HyperCeiler/assets/40189764/fd3e0055-988e-448e-b55e-433eacd18f52)

### HyperCeiler 设备信息

![6f1a8b238e8b4f982ce8bcf9b196abe](https://github.com/ReChronoRain/HyperCeiler/assets/40189764/86b9e995-e09a-48c4-b895-99f396e00c94)

**Comment by HChenX** [comment]
重新设置模块配置

**Comment by rainalong** [comment]
> 重新设置模块配置
找到了，是系统框架  显示   允许所有APP使用深色模式   这个开关会影响。  关了就好了。

**Comment by rainalong** [comment]
> 重新设置模块配置

找到了，是系统框架 显示 允许所有APP使用深色模式 这个开关会影响。 关了就好了。
