### ISSUE TITLE
小米互传禁止10分钟关闭失效🐛 [BUG] <问题标题>

### ISSUE THREAD

**Issue by fearlessTH** [ReChronoRain/HyperCeiler#650]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

小米互传通过控制中心打开时，禁止10分钟关闭功能失效，仅在设置界面打开可以成功触发。另外提一个小小建议，重启后也自动关闭，是否可以自动hook打开开关。

### 模块日志

抱歉禁用了日志，但至今仍然存在这个问题。

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![Screenshot_2024-05-27-18-51-14-705_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/75261077/13afe9be-f033-4706-ba68-76e7f3ef846d)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by mu7220** [comment]
目前我用得没问题，也没被自动关闭(2.21.6)，控制中心有提示可以忽略

至于另一个不打算做

另外你 hyperceiler 的截图怎么没放
