### ISSUE TITLE
🐛 [BUG] <输入法全面屏优化适配百度输入法有各部件乱飞的bug>

### ISSUE THREAD

**Issue by z13949043491** [ReChronoRain/HyperCeiler#662]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

当使用hyperceiler开启输入法全面屏优化时将百度输入法加入作用域后，就出现了百度输入法的工具栏飘到非常上面的地方，经我观察，飘上去的高度与打开输入方式/编辑工具时的工具栏高度对应，并且，在打字时还会突然上移，从输入法的全面屏功能栏开始上移。

### 模块日志

[LSPosed_2024-06-03T00_53_00.140371.zip](https://github.com/user-attachments/files/15526153/LSPosed_2024-06-03T00_53_00.140371.zip)

### 复现步骤

```bash
1. 前往 hyperceiler
2. 点击 输入法全面屏优化
3. 打开lsposed
4. 将百度输入法加入作用域
5. 重启
6. 百度输入法的全面屏模式出现问题
```

### 问题截图

![图片注释](图片链接)
![输入法工具栏上移，不排除最下面也已经上移的可能，因为颜色一致所以看不出来](https://github.com/ReChronoRain/HyperCeiler/assets/75197326/75f08bbc-865e-4987-b7ac-8225dffa092f)
![在打字的时候突然进行上移](https://github.com/ReChronoRain/HyperCeiler/assets/75197326/b82e424a-2a9b-4550-8f2c-312d0889f4f4)
![上移高度与输入方式的工具栏高度相当](https://github.com/ReChronoRain/HyperCeiler/assets/75197326/0ab1c257-18a8-4e4c-a5f3-30a570a3ed18)
![上移高度与编辑工具的工具高度相当](https://github.com/ReChronoRain/HyperCeiler/assets/75197326/a7ffa2ba-aa8f-4404-abae-20c37e82cc8d)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-06-03-01-07-06-438_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/75197326/c2baa47a-ea69-462b-9bb5-2f51a54ddbfc)

**Comment by HChenX** [comment]
找百度
