### ISSUE TITLE
💡 [需求] 系统桌面增加标题自动换行功能

### ISSUE THREAD

**Issue by Xieansecn** [ReChronoRain/HyperCeiler#67]
### 需求内容

在Cemiuiler> 系统桌面> 图标与标题> 标题 分类里添加一个名为**换行显示**的开关，描述为“过长的应用名称以换行显示”,并将标题分类里**文字滚动**的描述删去“，不再使用换行”。

### 实现思路&截图

![省略样式](https://github.com/saraSakuHj/HyperCeiler/assets/97814927/65cd1d0e-be58-4e53-9581-9296ff5fe0ae)
![滚动样式](https://github.com/saraSakuHj/HyperCeiler/assets/97814927/df0ff81f-1d36-4bc2-8bb6-492af69cd6cd)
![换行样式](https://github.com/saraSakuHj/HyperCeiler/assets/97814927/7ada28f2-c874-47be-a071-c0f084d2f223)

### 简单例子

当我打开**换行显示**的开关时，在正常切换后会改变为[换行样式]
当我打开**文字滚动**的开关时，在正常切换后会改变为[滚动样式]
(以上两个开关不可同时打开，仅可使用一个样式）
当以上两个开关全部关闭时，在正常切换后会改变为[省略样式]

**Comment by Xieansecn** [comment]
图一为[省略样式]
图二为[滚动样式]
图三为[换行样式]

**Comment by HChenX** [comment]
有代码额可以抄吗

**Comment by Xieansecn** [comment]
[MiuiHome_R](https://github.com/qqlittleice/MiuiHome_R)
MiuiHome_R中应该有，但是在软件内没注明这个标题换行功能

**Comment by HChenX** [comment]
> [MiuiHome_R](https://github.com/qqlittleice/MiuiHome_R) MiuiHome_R中应该有，但是在软件内没注明这个标题换行功能

无，你例图是怎么实现的？

**Comment by Xieansecn** [comment]
我仅启用了MiuiHome_R，并未勾选其他模块作用于桌面，MiuiHome模块界面内没有设置和说明，但勾选后就能达到例图[换行样式]效果

**Comment by HChenX** [comment]
> Author

似乎，本来就是换行的。我这边太长标题是会自动换行的，没用修改任何东西。

**Comment by Xieansecn** [comment]
我再传一张图，你看一下![开启MiuiHome模块的标题过长样式](https://github.com/ReChronoRain/HyperCeiler/assets/97814927/bcf0b2ab-1d08-4962-bf50-470a38604a23)

这是一个标题内容比较长的例子，图片中标题换了一行并把后面内容省略

![小米官方桌面正常样式_无模块](https://github.com/ReChronoRain/HyperCeiler/assets/97814927/16688ae9-7484-4b7d-ba00-89c90b373d60)

所以我猜测，也许是Cemiuiler与MiuiHome对于桌面图标标题显示范围做了限制才有了这样的效果。正常的官方桌面对于我现在设置的字体大小只显示了一行标题，Cemiuiler也是。我再猜测，我的提议可能是一个全新的功能，桌面是通过显示范围与文字大小测算出是否会换行的，这几张图我的字体大小是没有改变的

**Comment by HChenX** [comment]
> 我再传一张图，你看一下![开启MiuiHome模块的标题过长样式](https://user-images.githubusercontent.com/97814927/283983420-bcf0b2ab-1d08-4962-bf50-470a38604a23.jpg)
> 
> 这是一个标题内容比较长的例子，图片中标题换了一行并把后面内容省略
> 
> ![小米官方桌面正常样式_无模块](https://user-images.githubusercontent.com/97814927/283983567-16688ae9-7484-4b7d-ba00-89c90b373d60.jpg)
> 
> 所以我猜测，也许是Cemiuiler与MiuiHome对于桌面图标标题显示范围做了限制才有了这样的效果。正常的官方桌面对于我现在设置的字体大小只显示了一行标题，Cemiuiler也是。我再猜测，我的提议可能是一个全新的功能，桌面是通过显示范围与文字大小测算出是否会换行的，这几张图我的字体大小是没有改变的

系统默认最大2行，再多会省略，如果强行改变换会导致布局错乱。所以不建议更改

**Comment by HChenX** [comment]
虽然不能换行，但是新加入的自定义应用标题可以帮助你自行修改标题
