### ISSUE TITLE
增加 系统界面-通知与控制中心-隐藏运营商名称

### ISSUE THREAD

**Issue by yueqingyou** [ReChronoRain/HyperCeiler#68]
### 需求内容

看到最新更新 可以隐藏分割线 希望也出一个直接隐藏全部运营商文本的功能

### 实现思路&截图

![Screenshot_2023-11-18-17-46-44-473_com android chrome](https://github.com/ReChronoRain/HyperCeiler/assets/70048863/ab122e5f-4ce2-4123-8f2d-505c1323149a)

隐藏 中国联通 四个字

### 简单例子

![Screenshot_2023-11-18-17-46-44-473_com android chrome](https://github.com/ReChronoRain/HyperCeiler/assets/70048863/527dea7a-5584-4853-b0be-f294fd1e860d)

同上 隐藏 中国联通 四个字

**Comment by HChenX** [comment]
已经添加
