### ISSUE TITLE
💡 [需求] 状态栏线型电池

### ISSUE THREAD

**Issue by by123456by** [ReChronoRain/HyperCeiler#70]
### 需求内容

顶部以一条线显示电池电量

### 实现思路&截图

![IMG_20231119_231651](https://github.com/ReChronoRain/HyperCeiler/assets/15666692/8a36b7be-50fb-4d56-b064-9dd54f9e8be1)

### 简单例子

顶部以一条线显示电池电量

**Comment by mu7220** [comment]
不搞，OLED容易烧屏

**Comment by by123456by** [comment]
> 不搞，OLED容易烧屏

这么说的话，状态栏的图标不也烧屏吗

**Comment by HChenX** [comment]
> > 不搞，OLED容易烧屏
> 
> 这么说的话，状态栏的图标不也烧屏吗

你说得对，但是我们不做
