### ISSUE TITLE
🐛 [BUG] <淘寶app無法使用>

### ISSUE THREAD

**Issue by iamdsilver** [ReChronoRain/HyperCeiler#706]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

手機 小米11T ,MIUI 14.0.5
zygisk1.9.2
淘寶版本10.35到 10.37.1
進入淘寶app後，都無法觸控

交叉測試後
確定是此模組的問題
改回使用Cemiuiler，
重開機多次
一樣無法觸控
問題持續2個多月

### 模块日志

[LSPosed_2024-06-26T16_21_05.834859.zip](https://github.com/user-attachments/files/15984705/LSPosed_2024-06-26T16_21_05.834859.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
藍色都是無法觸控
橘色可以觸控
![Screenshot_2024-06-26-16-21-37-533_com taobao taobao-edit](https://github.com/ReChronoRain/HyperCeiler/assets/33306888/c886bfef-c4e5-4bfb-be57-939ba5d27cdd)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-06-26-16-20-12-699_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/33306888/4e15245e-1bb8-4cd9-9531-f8b196677a49)

**Comment by Sevtinge** [comment]
为淘宝开发不规范导致，在「清理分享菜单」和「清理打开方式菜单」中取消勾选淘宝即可
