### ISSUE TITLE
🐛 [BUG] <问题标题>更换第三方主题，充电显示失效

### ISSUE THREAD

**Issue by turn-0** [ReChronoRain/HyperCeiler#712]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

更换了第三方主题后，充电显示就会失效

### 模块日志

1

### 复现步骤

```bash
1
```

### 问题截图

![Screenshot_2024-06-28-10-40-10-888_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/174077103/9eea4447-6cfc-4158-ab07-f98ef49be794)

### HyperCeiler 设备信息

澎湃os

**Comment by Horange321** [comment]
HyperCeiler 对大部分第三方主题无效

**Comment by Sevtinge** [comment]
不需要的眼睛可以捐给有需要的人
