### ISSUE TITLE
🐛 [BUG] [系统桌面-抽屉] 移除“全部”分页不生效

### ISSUE THREAD

**Issue by limstash** [ReChronoRain/HyperCeiler#715]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在系统桌面-抽屉中，启用移除“全部”分页功能，在抽屉中仍出现“All”分页

### 模块日志

[LSPosed_2024-06-28T22_24_28.175672.zip](https://github.com/user-attachments/files/16032011/LSPosed_2024-06-28T22_24_28.175672.zip)

### 问题截图

![351ad7ff28cce197361e8b38ffdafbe](https://github.com/ReChronoRain/HyperCeiler/assets/8623449/d31d1e1d-0c43-4dbc-9fac-f74e88cbe8c9)

![85b9203fadb324e90d8a3c8ff0ee72a](https://github.com/ReChronoRain/HyperCeiler/assets/8623449/fb8c3799-a6e0-41cf-89f8-7e7eb175470b)

![5ef2c46f2ef6e03f9871d22d0797f26](https://github.com/ReChronoRain/HyperCeiler/assets/8623449/6f28368f-6989-44a3-b8aa-ee8a54260c38)

### HyperCeiler 设备信息

```
Debug Info by HyperCeiler

VersionName = 2.4.147_3d351594_r3188
VersionCode = 147
BuildTime = (UTC+0:00) 2024-06-28 09:49:46
BuildType = canary
GitHash = 3d35159428bf81ca4a3471d474fa4d60e61c1c68
GitCode = 3188
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Redmi K40 Pro
DeviceName = haydn
Model = M2012K11C
Brand = Redmi
Manufacture = Xiaomi
Board = haydn
Soc = SM8350
ModDevice = haydn
Characteristics = nosdcard
Pad = false
FingerPrint = Redmi/haydn/haydn:14/UKQ1.231207.002/V816.0.1.0.UKKCNXM:user/release-keys
Locale = zh-CN
Language = en_US
AndroidId = eb97fbaef7d98cec

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.1.0.UKKCNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = pangu-build-component-system-283500-wfr43-0lhq4-bh6wn
BuildDate = Fri Mar 29 10:04:01 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true
```

**Comment by lingqiqi5211** [comment]
移除全部分页需要你有至少一个以上的其他分类
