### ISSUE TITLE
🐛 [BUG] 状态栏时钟显秒但不刷新

### ISSUE THREAD

**Issue by Eternityioi** [ReChronoRain/HyperCeiler#716]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

小米14Pro OS1.0.45.0.UNBCNXM 状态栏时钟显秒但不刷新

### 模块日志

无崩溃日志

### 复现步骤

```bash
无复现步骤
```

### 问题截图

无截图，有录屏

### HyperCeiler 设备信息

Debug Info by HyperCeiler

VersionName = 2.4.148_20240629
VersionCode = 148
BuildTime = (UTC+0:00) 2024-06-29 14:36:57
BuildType = release
GitHash = 489191ce
GitCode = 3194
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Xiaomi 14 Pro
DeviceName = shennong
Model = 23116PN5BC
Brand = Xiaomi
Manufacture = Xiaomi
Board = shennong
Soc = SM8650
ModDevice = shennong
Characteristics = nosdcard
Pad = false
FingerPrint = Xiaomi/shennong/shennong:14/UKQ1.230804.001/V816.0.45.0.UNBCNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = 10a5ea287df3d13d

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.45.0.UNBCNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = pangu-build-component-system-113946-qqt0j-h824z-k3drl
BuildDate = Tue Jun 25 08:20:01 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true

**Comment by lingqiqi5211** [comment]
@Eternityioi 状态栏时钟多了一个 “允许时钟以秒刷新” 的开关
开了就行
下次反馈前建议看全所有选项再提
