### ISSUE TITLE
🐛 [BUG] Hook小米应用商店崩溃

### ISSUE THREAD

**Issue by woshigenm** [ReChronoRain/HyperCeiler#717]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

升级至HyperCeiler 最新release版-2.4.148_20240629
Hook应用商店

应用商店崩溃出现问题

### 模块日志

[LSPosed_2024-06-30T14_15_48.896346.zip](https://github.com/user-attachments/files/16043446/LSPosed_2024-06-30T14_15_48.896346.zip)

### 复现步骤

```bash
1. 升级至HyperCeiler 最新release版-2.4.148_20240629
2. 点击小米应用商店

小米应用商店崩溃，出现问题
```

### HyperCeiler 设备信息

![Screenshot_2024-06-30-14-22-22-970_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/99122353/aaf13a43-91b3-4466-b83d-134c5515bade)

**Comment by Sevtinge** [comment]
log无明显异常 尝试重新优化应用商店
