### ISSUE TITLE
💡 [需求] <标题>禁用小窗功能

### ISSUE THREAD

**Issue by MinierPlus** [ReChronoRain/HyperCeiler#718]
### 需求内容

在一些特殊情况下需要仅禁用小窗的功能，在不需要时可以通过设置里重新启用小窗功能

### 实现思路&截图

通过一个禁用所有应用变为小窗状态（将全部应用加入小窗黑名单）的代码来实现禁用小窗功能

### 简单例子

在一些特殊情况下需要仅禁用小窗的功能，在不需要时可以通过设置里重新启用小窗功能

**Comment by Sevtinge** [comment]
暂时无计划
