### ISSUE TITLE
圆角柜型磁贴失效

### ISSUE THREAD

**Issue by 511xy** [ReChronoRain/HyperCeiler#73]
### 问题描述

最新版hyper的日志有修复，但是还是失效状态。

### 模块日志

最新版hyper的日志有修复，但是还是失效状态。

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-11-20-15-46-50-872_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50691422/a4cdc744-7498-46ec-9878-375ec84edb9c)
![Screenshot_2023-11-20-15-46-48-177_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/50691422/6b660f1d-bdd9-44b8-bb83-d3cd11259ed7)

### 机型

小米13

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132-20231120

**Comment by HChenX** [comment]
发日志谢谢

**Comment by 511xy** [comment]
> 发日志谢谢

https://511i.lanzoum.com/iHAbf1g5ronc
https://511i.lanzoum.com/i5NHO1g5rofe

你好，日志来迟了

**Comment by Sevtinge** [comment]
日志无效 重启一遍系统界面后再给个日志

**Comment by Sevtinge** [comment]
这个日志包是坏的

**Comment by 511xy** [comment]
> 这个日志包是坏的

最新版可以调节弧度，已经修复啦
