### ISSUE TITLE
🐛 [BUG] 升级澎湃1.0.2后闪退

### ISSUE THREAD

**Issue by Alpha-Qian** [ReChronoRain/HyperCeiler#734]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述
Miui14.0.10时没有闪退现象
升级澎湃1.0.2后：
1.重启键一点就闪退，无法重启对应应用。
2.开发者选项中调试kill功能闪退
3.开发者选项中还有一个功能闪退
4.触发3后软件彻底无法进入（试过重启，重装软件，禁用模块，更换kitsune到apatch，重新刷入系统完整包）所以问题23现在都录不到日志，问题3怎么触发的忘了

### 模块日志

1的日志：
[LSPosed_2024-07-06T12_04_39.042360.zip](https://github.com/user-attachments/files/16114851/LSPosed_2024-07-06T12_04_39.042360.zip)

4的日志：
[LSPosed_2024-07-25T05_33_44.940071.zip](https://github.com/user-attachments/files/16367702/LSPosed_2024-07-25T05_33_44.940071.zip)

![Screenshot_2024-07-23-05-19-48-774_com sevtinge hyperceiler-edit](https://github.com/user-attachments/assets/b28bbb35-3a47-4d45-80f8-00057014fd17)

**Comment by lingqiqi5211** [comment]
@Alpha-Qian 重启闪退一般是你 root 没给
或者重启一下应用后就行了

**Comment by Alpha-Qian** [comment]
> @Alpha-Qian 重启闪退一般是你 root 没给 或者重启一下应用后就行了

试了没有用
