### ISSUE TITLE
💡 [小米浏览器强制翻译网页] <浏览器开启强制翻译>

### ISSUE THREAD

**Issue by AEDELSTAN** [ReChronoRain/HyperCeiler#76]
### 需求内容

使用小米官方浏览器，有些网页不能进行翻译，不知道能否强制开启

（就在刚刚打字的时候，发现网页加载完很久之后就能按翻译了，但是别的网站等了很久都不能翻译，我也不清楚是什么原因）

### 实现思路&截图

最下面的按钮
![Screenshot_2023-11-21-13-33-46-887_com android br](https://github.com/ReChronoRain/HyperCeiler/assets/73707517/2ef00ba3-18c6-48a9-80e3-2d144362925f)

### 简单例子

为小米浏览器，添加强制网页翻译

**Comment by HChenX** [comment]
不做
