### ISSUE TITLE
🐛 [BUG] <Bootloop on Redmi Note 12 Pro 5G>

### ISSUE THREAD

**Issue by Gleb2372372** [ReChronoRain/HyperCeiler#761]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

Android 14 Hyper OS 1.0.4.0
LSPosed (Have Pengeek)
Magisk Kitsune 

### 模块日志

Can't get it.

### 复现步骤

```bash
1. Download
2. Enable in LSPosed 
3. Restart the phone
```

### 问题截图

-

### HyperCeiler 设备信息

-

**Comment by gyrorayo** [comment]
I believe that is a problem with your setup, I mean: **root solution/LSPosed version/Zygisk implementation.**
What version of LSPosed are you using? More importantly, why are you using something as "Magisk Kitsune" when  there are more solid and reliable alternatives such as APatch and KernelSu are available? Anyway... I've managed to run this module on a RMN134G using the following setup, I'll suggest you to give it a try.

APatch/KernelSu: 
LSPosed_mod: https://github.com/mywalkb/LSPosed_mod/releases
ZygiskNext: https://github.com/Dr-TSNG/ZygiskNext

**Comment by Gleb2372372** [comment]
I haven't. But I think it's unlikely to be because of the environment because everything ran without problems before.

**Comment by Gleb2372372** [comment]
Hello again checked again without modules and Pengeek everything worked but when I turn on other modules in Magisk bootloop starts. Can you tell me which module is interfering with the work?

**Comment by Gleb2372372** [comment]
![Screenshot_2024-08-13-13-09-48-001_miuw ha](https://github.com/user-attachments/assets/c482f1be-9c2f-419e-8613-b814b4351817)
![Screenshot_2024-08-13-13-09-46-052_miuw ha](https://github.com/user-attachments/assets/09807d95-6e73-4f19-b48d-0a1d03e10b92)
![Screenshot_2024-08-13-13-09-38-971_miuw ha](https://github.com/user-attachments/assets/880f674e-7b01-46b9-b419-dd0403c711e4)
![Screenshot_2024-08-13-13-09-31-847_miuw ha](https://github.com/user-attachments/assets/08e5fca8-5704-47f7-9787-03711ea94d88)
![Screenshot_2024-08-13-13-09-28-294_miuw ha](https://github.com/user-attachments/assets/f350fa28-f60f-4f16-9906-888b619188c1)
![Screenshot_2024-08-13-13-09-24-725_miuw ha](https://github.com/user-attachments/assets/c3cd10e6-2806-4ef1-8480-20ef79bbb4f3)

**Comment by Gleb2372372** [comment]
I found the cause of the failures, it turned out to be a module called DisableFlagSecure https://xdaforums.com/t/module-disable-flag-secure-v10-0-by-mehedi-h-joy.4490475/. It somehow produces a bootloop together with HyperCeiler.

**Comment by Gleb2372372** [comment]
I also learned that Pengeek(CustoMIUIzer) does not interfere with HyperCeiler in any way. They work perfectly well in parallel.
