### ISSUE TITLE
🐛 [BUG] <模块更新版本后状态栏网速异常>

### ISSUE THREAD

**Issue by CuSO4with5H2O** [ReChronoRain/HyperCeiler#765]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

将模块更新版本，状态栏网速表示速度的K，会变成“网”字（或其他字）

### 模块日志

[LSPosed_2024-07-21T17_23_51.399650.zip](https://github.com/user-attachments/files/16323712/LSPosed_2024-07-21T17_23_51.399650.zip)

### 复现步骤

```bash
1. 将模块从2.4.149_ebe0b5f7_r3254更新到2.4.149_2e2db1f4_r3259
2. 观察状态栏实时网速
出现问题

注：本问题会在绝大多数更新模块版本时出现（不仅针对以上的版本），重启系统界面即可解决，但每次更新模块版本都需要重启系统界面有点太麻烦了
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-07-21-17-24-38-725_com miui home-edit](https://github.com/user-attachments/assets/d878fbec-a86f-42d7-937f-5fe951c90d56)

### HyperCeiler 设备信息

Debug Info by HyperCeiler

VersionName = 2.4.149_2e2db1f4_r3259
VersionCode = 149
BuildTime = (UTC+0:00) 2024-07-21 06:29:56
BuildType = canary
GitHash = 2e2db1f44a054e865f30404a9d5193b2c59a32f8
GitCode = 3259
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Redmi Note 12 Turbo
DeviceName = marble
Model = 23049RAD8C
Brand = Redmi
Manufacture = Xiaomi
Board = marble
Soc = SM7475
ModDevice = marble
Characteristics = nosdcard
Pad = false
FingerPrint = Redmi/marble/marble:14/UKQ1.230804.001/V816.0.24.7.15.DEV:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = c6dff78e1289241a
DeviceToken = c309995914689f5702e99c7451f21e6d2e74a4954aae44ecdcb2a39f0e726580

AndroidSdkVersion = 34
MiuiVersion = 816.0
HyperOsVersion = 1.0
SystemVersion = OS1.0.24.7.15.DEV
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = builder-system-44887-413441922783793152
BuildDate = Mon Jul 15 13:20:22 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true
WhoAmI = root
LoggerStatus = true, SUCCESS

**Comment by Sevtinge** [comment]
更新后建议重启系统
