### ISSUE TITLE
💡 [需求] 通知与控制中心“5G网络开关”图标重绘

### ISSUE THREAD

**Issue by yukineko2233** [ReChronoRain/HyperCeiler#77]
### 需求内容

“5G网络开关”现图标认为与HyperOS的设计不和谐，因此希望可以重绘该图标。

### 简单例子

此为使用了"MIUI 5G开关"图标的效果。
![fba7275928a523a7752afe6544812a4a](https://github.com/ReChronoRain/HyperCeiler/assets/112458531/3a92bb54-dde2-40a8-a117-8d24e4c11f39)

**Comment by HChenX** [comment]
![IMG_20231121_151500_662.jpg](https://github.com/ReChronoRain/HyperCeiler/assets/123531821/ea0351cd-bd28-44eb-ac95-69a83f428cb8)
