### ISSUE TITLE
增加复原功能

### ISSUE THREAD

**Issue by Li-Xiaohan** [ReChronoRain/HyperCeiler#772]
### 需求内容

在使用HyperCeiler的功能时，难免会修改过度。因此希望可以有重置各个部分修改的功能

### 简单例子

例如，在修改状态栏时，有时会错误修改

**Comment by Sevtinge** [comment]
默认值即为不hook

**Comment by Li-Xiaohan** [comment]
但是不在lsposed作用域里面勾选只是自欺欺人。就好比水管漏水，你却关闭了水闸，后期如果想要继续用水只能忍受漏水，直到恢复默认值（即找到水管漏水的地方）

从 Windows 版邮件发送

发件人: 绀漓丨Sevtinge
发送时间: 2024年8月12日 18:35
收件人: ReChronoRain/HyperCeiler
抄送: Li Xiaohan; Author
主题: Re: [ReChronoRain/HyperCeiler] 增加复原功能 (Issue #772)

默认值即为不hook

**Comment by Sevtinge** [comment]
默认值不会激活任何hook，和没开一样

**Comment by Li-Xiaohan** [comment]
关键是我不知道默认值啊

从 Windows 版邮件发送

发件人: 绀漓丨Sevtinge
发送时间: 2024年8月14日 0:30
收件人: ReChronoRain/HyperCeiler
抄送: Li Xiaohan; Author
主题: Re: [ReChronoRain/HyperCeiler] 增加复原功能 (Issue #772)

默认值不会激活任何hook，和没开一样
