### ISSUE TITLE
🐛 [BUG] 使用官方rom，提示使用非官方rom

### ISSUE THREAD

**Issue by Lynn-Becky** [ReChronoRain/HyperCeiler#773]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

此提示为近期出现

### 模块日志

----part 1 start----

Resetting log settings
[ 2024-07-26T12:57:36.890     1000:  2195:  2195 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:57:36.901     1000:  2195:  2195 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:57:36.905     1000:  2195:  2195 I/LSPosed-Bridge  ] Loading legacy module com.tsng.hidemyapplist from /data/app/~~syUzbahtEd2DsBcbA6Rr3w==/com.tsng.hidemyapplist-EYe7-BdJEurdFbeXSocFiw==/base.apk
[ 2024-07-26T12:57:36.918     1000:  2195:  2195 I/LSPosed-Bridge  ]   Loading class icu.nullptr.hidemyapplist.xposed.XposedEntry
[ 2024-07-26T12:57:36.935     1000:  2195:  2195 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:36.944     1000:  2195:  2195 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:37.711     1000:  2195:  2195 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:37 (HMA-XposedEntry) Hook entry
[ 2024-07-26T12:57:37.733     1000:  2195:  2195 I/LSPosed-Bridge  ] [HyperCeiler][E][android][RemoveSmallWindowRestrictions]: Hook isResizeable failed by: java.lang.IllegalArgumentException: Sequence has more than one element.
[ 2024-07-26T12:57:37.748     1000:  2195:  2195 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-07-26T12:57:41.869     1000:  2195:  2195 I/LSPosed-Bridge  ] [DEBUG] 07-26 12:57:41 (HMA-XposedEntry) Got pms: com.android.server.pm.PackageManagerService$IPackageManagerImpl@6b01767
[ 2024-07-26T12:57:41.871     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-UserService) Initialize HMAService - Version 96
[ 2024-07-26T12:57:41.883     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-Service) Data dir: /data/system/hide_my_applist_omkegsnqvquogjvb
[ 2024-07-26T12:57:41.900     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-Service) Config loaded
[ 2024-07-26T12:57:41.908     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (PmsHookTarget33) Load hook
[ 2024-07-26T12:57:41.942     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (ZygoteArgsHook) Load hook
[ 2024-07-26T12:57:41.942     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (ZygoteArgsHook) App data isolation enabled: true
[ 2024-07-26T12:57:41.942     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (ZygoteArgsHook) Vold app data isolation enabled: false
[ 2024-07-26T12:57:41.943     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-Service) Hooks installed
[ 2024-07-26T12:57:41.943     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-Service) HMA service initialized
[ 2024-07-26T12:57:41.967     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-UserService) Register observer
[ 2024-07-26T12:57:41.969     1000:  2195:  3903 I/LSPosed-Bridge  ] [ INFO] 07-26 12:57:41 (HMA-XposedEntry) User service started
[ 2024-07-26T12:57:42.099     1000:  2195:  2195 I/LSPosed-Bridge  ] [HyperCeiler][E][getAppsUsingInputMethod]: have e: java.lang.IllegalStateException: IInputMethodManager is not available
[ 2024-07-26T12:57:45.263     1000:  5460:  5460 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:45.269    10141:  4950:  4950 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:57:45.278     1000:  5460:  5460 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:45.295    10141:  4950:  4950 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:57:45.300    10141:  4950:  4950 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:45.314    10141:  4950:  4950 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:45.491     1000:  5460:  5460 I/LSPosed-Bridge  ] [HyperCeiler][E][com.android.systemui][GmsTile]: Don't Have handleShowStateMessage: java.lang.NoSuchMethodException: com.android.systemui.qs.tiles.ScreenLockTile.handleShowStateMessage []
[ 2024-07-26T12:57:45.494     1000:  5460:  5460 I/LSPosed-Bridge  ] [HyperCeiler][E][com.android.systemui][ReduceBrightColorsTile]: Don't Have handleSetListening: java.lang.NoSuchMethodException: com.android.systemui.qs.tiles.ReduceBrightColorsTile.handleSetListening [boolean]
[ 2024-07-26T12:57:45.494     1000:  5460:  5460 I/LSPosed-Bridge  ] [HyperCeiler][E][com.android.systemui][ReduceBrightColorsTile]: Don't Have handleLongClick: java.lang.NoSuchMethodException: com.android.systemui.qs.tiles.ReduceBrightColorsTile.handleLongClick [class android.view.View]
[ 2024-07-26T12:57:45.497     1000:  5460:  5460 I/LSPosed-Bridge  ] [HyperCeiler][E][com.android.systemui][FiveGTile]: Don't Have handleLongClick: java.lang.NoSuchMethodException: com.android.systemui.qs.tiles.MiuiNfcTile.handleLongClick [class android.view.View]
[ 2024-07-26T12:57:45.687     1000:  5708:  5708 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:57:45.738     1000:  5708:  5708 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:57:45.744    10141:  4950:  4950 I/LSPosed-Bridge  ] [HyperCeiler][E][ShowAllHideApp]: failed to create mkdirs: /data/user/0/com.miui.home/cache/dexkit/ cant use dexkit cache!!
[ 2024-07-26T12:57:45.746     1000:  5708:  5708 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:45.777    10141:  4950:  4950 I/LSPosed-Bridge  ] [HyperCeiler][E][com.miui.home][ShowAllHideApp]: Hook Failed: B3.a: No result found for query
	at H3.f.b(Unknown Source:75)
	at Y1.a.a(Unknown Source:71)
	at com.sevtinge.hyperceiler.module.base.dexkit.h.i(Unknown Source:7)
	at com.sevtinge.hyperceiler.module.base.dexkit.h.f(Unknown Source:30)
	at com.sevtinge.hyperceiler.module.base.dexkit.h.e(Unknown Source:1)
	at com.sevtinge.hyperceiler.module.hook.home.other.ShowAllHideApp.I0(Unknown Source:16)
	at D0.a.J0(Unknown Source:4)
	at com.sevtinge.hyperceiler.module.base.BaseModule.initHook(SourceFile:2)
	at com.sevtinge.hyperceiler.module.app.Home.Phone.HomeT.handleLoadPackage(Unknown Source:2460)
	at com.sevtinge.hyperceiler.module.base.BaseModule.init(Unknown Source:366)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.sevtinge.hyperceiler.XposedInit.handleLoadPackage(Unknown Source:650)
	at sQxp.RcMoK.UyIfh.RR.oI.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at sQxp.RcMoK.UyIfh.RR.oI.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at sQxp.RcMoK.UyIfh.RR.oI.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1141)
	at android.app.LoadedApk.getResources(LoadedApk.java:1400)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3335)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3327)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7298)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2367)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8711)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[ 2024-07-26T12:57:45.785     1000:  5708:  5708 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:46.602     1000:  6186:  6186 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:57:46.631     1000:  6186:  6186 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:57:46.640     1000:  6186:  6186 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:46.656     1000:  6186:  6186 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:47.924     1000:  6670:  6670 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:47.933     1000:  6670:  6670 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:49.533     1000:  7342:  7342 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:49.545     1000:  7342:  7342 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:49.221     1000:  7342:  7342 I/LSPosed-Bridge  ] [HyperCeiler][E][DisableReport]: failed to create mkdirs: /data/user/0/com.miui.securitycenter/cache/dexkit/ cant use dexkit cache!!
[ 2024-07-26T12:57:53.377     1000: 10044: 10044 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:53.389     1000: 10044: 10044 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:54.131    10257: 10592: 10592 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:57:54.195    10257: 10592: 10592 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:57:57.538     1000: 12850: 12850 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:57.586     1000: 12850: 12850 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:57:58.425    10158: 13328: 13328 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:57:58.596    10158: 13328: 13328 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:58:00.744    10265: 14610: 14610 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:58:00.815    10265: 14610: 14610 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:58:04.911     1000:  2195:  4364 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:04 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T12:58:04.915     1000:  2195:  4364 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:04 (PmsHookTarget33) @shouldFilterApplication: query from com.byxiaorun.detector
[ 2024-07-26T12:58:04.992     1000:  2195: 11837 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:04 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T12:58:04.993     1000:  2195: 11837 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:04 (PmsHookTarget33) @shouldFilterApplication: query from com.byxiaorun.detector
[ 2024-07-26T12:58:05.127     1000:  2195: 11976 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:05 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T12:58:05.127     1000:  2195: 11976 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:05 (PmsHookTarget33) @shouldFilterApplication: query from com.byxiaorun.detector
[ 2024-07-26T12:58:06.440    10164: 17908: 17908 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:58:06.478    10164: 17908: 17908 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:58:07.660     1000:  2195:  2409 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:07 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T12:58:07.661     1000:  2195:  2409 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:07 (PmsHookTarget33) @shouldFilterApplication: query from com.byxiaorun.detector
[ 2024-07-26T12:58:18.581     1000:  2195:  2409 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:18 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T12:58:18.582     1000:  2195:  2409 I/LSPosed-Bridge  ] [ INFO] 07-26 12:58:18 (PmsHookTarget33) @shouldFilterApplication: query from com.byxiaorun.detector
[ 2024-07-26T12:58:44.526    10264: 18588: 18588 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:58:44.550    10264: 18588: 18588 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:58:44.697    10264: 18588: 18588 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-07-26T12:58:45.155     1000: 21330: 21330 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:58:45.179     1000: 21330: 21330 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:58:45.186     1000: 21330: 21330 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:58:45.200     1000: 21330: 21330 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T12:59:27.534     1000: 22785: 22785 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~eaU2chIPK1k2CXB0i-WXig==/com.omarea.vtools-Tu2jrHu21DRRx4MwDK9X7A==/base.apk
[ 2024-07-26T12:59:27.549     1000: 22785: 22785 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-07-26T12:59:27.554     1000: 22785: 22785 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T12:59:27.567     1000: 22785: 22785 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T13:00:22.052    10281: 19984: 19984 I/LSPosed-Bridge  ] Loading legacy module com.tsng.hidemyapplist from /data/app/~~syUzbahtEd2DsBcbA6Rr3w==/com.tsng.hidemyapplist-EYe7-BdJEurdFbeXSocFiw==/base.apk
[ 2024-07-26T13:00:22.082    10281: 19984: 19984 I/LSPosed-Bridge  ]   Loading class icu.nullptr.hidemyapplist.xposed.XposedEntry
[ 2024-07-26T13:00:22.208     1000:  2195:  2347 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:22 (HMA-UserService) Send binder to app
[ 2024-07-26T13:00:43.984     1000:  2195:  2409 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:43 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-07-26T13:00:44.797    10158: 25107: 25107 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~pHmMikTZBF-yfs61IkBOcg==/com.sevtinge.hyperceiler-gTboFXnuPtqUr-kj9db4_w==/base.apk
[ 2024-07-26T13:00:44.832    10158: 25107: 25107 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-07-26T13:00:54.003     1000:  2195:  2374 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:54 (PmsHookTarget33) @shouldFilterApplication: query from com.czbank.mbank
[ 2024-07-26T13:00:54.003     1000:  2195:  2374 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:54 (PmsHookTarget33) @shouldFilterApplication: query from cn.gov.pbc.dcep
[ 2024-07-26T13:00:54.004     1000:  2195:  2374 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:54 (PmsHookTarget33) @shouldFilterApplication: query from com.chinamworld.bocmbci
[ 2024-07-26T13:00:54.005     1000:  2195:  2374 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:54 (PmsHookTarget33) @shouldFilterApplication: query from cmb.pb
[ 2024-07-26T13:00:54.007     1000:  2195:  2374 I/LSPosed-Bridge  ] [ INFO] 07-26 13:00:54 (PmsHookTarget33) @shouldFilterApplication: query from cn.com.shbank.mper

### 问题截图

![Screenshot_2024-07-26-12-51-28-307_com sevtinge hyperceiler](https://github.com/user-attachments/assets/dec2e7f6-486c-4859-b17c-a5b938ac96db)
使用的模块：
![Screenshot_2024-07-26-13-07-36-807_nnpn kchw](https://github.com/user-attachments/assets/7aa7d1bd-13ef-4eff-af61-72a0ae8a2c25)

### HyperCeiler 设备信息

Debug Info by HyperCeiler

VersionName = 2.4.148_20240629
VersionCode = 148
BuildTime = (UTC+0:00) 2024-06-29 14:36:57
BuildType = release
GitHash = 489191ce
GitCode = 3194
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Xiaomi 14 Pro
DeviceName = shennong
Model = 23116PN5BC
Brand = Xiaomi
Manufacture = Xiaomi
Board = shennong
Soc = SM8650
ModDevice = shennong
Characteristics = nosdcard
Pad = false
FingerPrint = Xiaomi/shennong/shennong:14/UKQ1.230804.001/V816.0.24.7.20.DEV:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = 6afcbf66c806d63f

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.24.7.20.DEV
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = builder-system-33569-415246667471163392
BuildDate = Sat Jul 20 12:48:00 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true

**Comment by Sevtinge** [comment]
已修等发
