### ISSUE TITLE
加入相机35mm快捷焦段

### ISSUE THREAD

**Issue by aacginw** [ReChronoRain/HyperCeiler#774]
### 需求内容

加入14ultra移植的这个功能：
新增 拍照模式主摄默认焦段，相机设置中可以选择23mm/28mm/35mm作为默认焦段
优化 升级拍照模式变焦组件，轻触变焦组件实现快捷变焦，主摄支持快速切换28mm/35mm，5x支持快速切换10x/30x/60x

### 实现思路&截图

通过hook等方式加入该功能

### 简单例子

新增 拍照模式主摄默认焦段，相机设置中可以选择23mm/28mm/35mm作为默认焦段
优化 升级拍照模式变焦组件，轻触变焦组件实现快捷变焦，主摄支持快速切换28mm/35mm，5x支持快速切换10x/30x/60x
以便于更好的拍摄体验

**Comment by Sevtinge** [comment]
无法反混淆
