### ISSUE TITLE
🐛 [BUG] <问题标题>显示亮度百分比失效

### ISSUE THREAD

**Issue by DaRouBang2** [ReChronoRain/HyperCeiler#784]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

打开显示亮度百分比选项无效

### 模块日志

[LSPosed_2024-07-30T00_19_42.512813.zip](https://github.com/user-attachments/files/16416138/LSPosed_2024-07-30T00_19_42.512813.zip)

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Uploading Screenshot_2024-07-30-00-19-15-447_com.sevtinge.hyperceiler.jpg…]()

**Comment by Sevtinge** [comment]
其实 hyper不打算修了（逃

**Comment by DaRouBang2** [comment]
绷不住了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReChronoRain/HyperCeiler] 🐛 [BUG] <问题标题&gt;显示亮度百分比失效 (Issue #784)




 
其实 hyper不打算修了（逃
