### ISSUE TITLE
🐛 [BUG] 安全服务-跳过倒计时限制在部分场景无法生效

### ISSUE THREAD

**Issue by yyk725** [ReChronoRain/HyperCeiler#788]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

安全服务-其他-跳过倒计时限制无法对开发者设置-usb调试（安全设置）生效，另外打开跳过倒计时限制-直接跳过警告无法达到预期效果，仍需手动点击

### 模块日志

无

### 问题截图

![Screenshot_2024-08-01-10-49-53-391_com miui securitycenter](https://github.com/user-attachments/assets/cc16f7b0-f7b4-4d85-90b5-e5cf59f24d2e)

### HyperCeiler 设备信息

![Screenshot_2024-08-01-16-37-54-603_com sevtinge hyperceiler-edit](https://github.com/user-attachments/assets/09321d12-fb13-4661-b4f4-4c2b4e0f8aac)

**Comment by Sevtinge** [comment]
no log no fix
