### ISSUE TITLE
🐛 [BUG] xaga 1.0.3版本提示非官方包

### ISSUE THREAD

**Issue by YantengL** [ReChronoRain/HyperCeiler#791]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

版本提示异常

### 模块日志

[kmsg.log](https://github.com/user-attachments/files/16479449/kmsg.log)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-08-03-19-11-20-807_com sevtinge hyperceiler](https://github.com/user-attachments/assets/f4a440d6-7f01-4fb2-a406-60797ae45cc9)

### HyperCeiler 设备信息

![图片注释](图片链接)
Debug Info by HyperCeiler

VersionName = 2.4.148_20240629
VersionCode = 148
BuildTime = (UTC+0:00) 2024-06-29 14:36:57
BuildType = release
GitHash = 489191ce
GitCode = 3194
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Redmi Note 11T Pro
DeviceName = xaga
Model = 22041216C
Brand = Redmi
Manufacture = Xiaomi
Board = xaga
Soc = MT6895Z/TCZA
ModDevice = xaga
Characteristics = nosdcard
Pad = false
FingerPrint = Redmi/xaga/xaga:14/UP1A.231005.007/V816.0.3.0.ULOCNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = ca0be650b4d77263

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.3.0.ULOCNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = builder-system-38281-414527569204383744
BuildDate = Thu Jul 18 13:11:13 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true

**Comment by dandandedd** [comment]
我也遇到了这个问题 同型号手机
系统是Hyper OS1.0.3

**Comment by Sevtinge** [comment]
已修等发
