### ISSUE TITLE
💡 [需求] 系统界面 - 锁屏 - 相机和负一屏按钮模糊 模糊背景半径自定义

### ISSUE THREAD

**Issue by hrsthrt74** [ReChronoRain/HyperCeiler#792]
### 需求内容

（标题不是`模糊半径`，而是`模糊背景半径`）
在不同设备上，背景半径显示不一样，在部分设备上会过大，所以请求可以自定义半径大小

### 实现思路&截图

https://github.com/ReChronoRain/HyperCeiler/blob/main/app/src/main/java/com/sevtinge/hyperceiler/module/hook/systemui/lockscreen/BlurButton.kt
应该是位于这里的代码，在 HyperOS 上通过反编译修改本类里所有的`40`（`0x28`）后发现，值越大半径越小
但因为是反编译修改的结果，不确定修改源代码是是否也是值越大半径越小；此外也没确定 oldBlur 是否同样（我懒XD）

### 简单例子

![Screenshot_2024-08-04-13-08-58-224_lockscreen](https://github.com/user-attachments/assets/cd2b3c07-f58d-4de0-9eff-9a7d59e8b394)
↑`10`（`0xa`）
![Screenshot_2024-08-04-13-10-35-537_lockscreen](https://github.com/user-attachments/assets/17b2e73b-99b5-4cca-829d-f3da33e1ba68)
↑`60`（`0x3c`）

**Comment by Liden-3028722843** [comment]
支持
