### ISSUE TITLE
💡 [需求] 负一屏隐藏推荐卡片

### ISSUE THREAD

**Issue by yqs112358** [ReChronoRain/HyperCeiler#794]
### 需求内容

如题，负一屏推荐卡片无法禁用
![Screenshot_2024-08-06-17-53-16-809_com miui home-edit](https://github.com/user-attachments/assets/b20e62d8-c985-4807-956e-d034f790eba5)

### 实现思路&截图

Hook智能助理中相关方法，禁止其显示

### 简单例子

为负一屏禁用推荐卡片

**Comment by Sevtinge** [comment]
智能助理自己就能关啊
