### ISSUE TITLE
🐛 [BUG] 无障碍等敏感授权 跳过警告倒计时功能失效

### ISSUE THREAD

**Issue by yqs112358** [ReChronoRain/HyperCeiler#795]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

升级最新hyperos1.0.10.0后，安全中心→其他→跳过倒计时限制、直接跳过警告 两者不再有效。图见下方截图栏目

### 模块日志

[LSPosed_2024-08-06T20_26_08.043991.zip](https://github.com/user-attachments/files/16510212/LSPosed_2024-08-06T20_26_08.043991.zip)

### 复现步骤

```bash
1. 升级HyperOS到最新1.0.10.0
2. 在ceiler中打开这两个选项
3. 给一个新应用无障碍授权
4. 警告页面和倒计时仍然出现
```

### 问题截图

![IMG_20240806_202136](https://github.com/user-attachments/assets/54482bf1-e308-413d-9d5d-d9d77794047b)
![Screenshot_2024-08-06-19-16-43-391_com miui securitycenter](https://github.com/user-attachments/assets/fc0cf906-1722-44dd-8a34-70f5c5b929fd)

### HyperCeiler 设备信息

![Screenshot_2024-08-06-20-29-27-431_com sevtinge hyperceiler](https://github.com/user-attachments/assets/43c96fd6-de5c-42bf-a8e9-5d773b98c2a2)

**Comment by Sevtinge** [comment]
更新了 检查开关
