### ISSUE TITLE
🐛 [BUG] 网速指示器启用自定义导致system UI卡死

### ISSUE THREAD

**Issue by QianYuChan** [ReChronoRain/HyperCeiler#80]
### 问题描述

打开网速指示器自定义，
启用显示上下行网速，
指示器图标调为第三个（小三角形）后，
systemUI崩溃。
具体表现为只显示一个壁纸，
按下电源键黑屏，
再按电源键继续显示壁纸。
电源键长按菜单变为原生安卓样式。

### 模块日志

[LSPosed_2023-11-22T14_49_58.213317_025037.zip](https://github.com/ReChronoRain/HyperCeiler/files/13434625/LSPosed_2023-11-22T14_49_58.213317_025037.zip)

### 复现步骤

```bash
1.打开Cemiuiler
2.打开系统界面-状态栏-网速指示器选项
3.打开启用自定义
4.打开显示上下行网速
5.指示器图标选为菜单第三个选项
6.重启SystemUI
```

### 问题截图

![图
![IMG_20231122_144426](https://github.com/ReChronoRain/HyperCeiler/assets/76060243/aea42dee-2991-419e-8365-bc179fb5bbce)
![IMG_20231122_144434](https://github.com/ReChronoRain/HyperCeiler/assets/76060243/485d8cf9-7ed6-48a7-9ec1-c3340edd6faa)
片注释](图片链接)

### 机型

Redmi K60 Ultra

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

1.3.130_20231101

**Comment by HChenX** [comment]
模块日志请调至debug，并且发送你系统界面的安装包。

**Comment by HChenX** [comment]
> 模块日志请调至debug，并且发送你系统界面的安装包。

建议发送至tg，另外我测试正常

**Comment by mu7220** [comment]
暂时屏蔽新版网速修改来防止崩溃
