### ISSUE TITLE
🐛 [BUG] <问题标题>hyperOS的经典控制中心的上午下午等时间粗细不一致

### ISSUE THREAD

**Issue by freedomspiritJohn** [ReChronoRain/HyperCeiler#805]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

直接上传图片
![Screenshot_2024-08-12-15-03-06-553_com miui home-edit](https://github.com/user-attachments/assets/a93218c4-702d-421a-b80c-4c46083bd787)
![Screenshot_2024-08-12-15-03-19-426_com miui home-edit](https://github.com/user-attachments/assets/813a75f2-7fdc-4427-a26c-aead23dc3dbe)
状态栏的上午下午等时间粗细显示一致，但是经典控制中心的上午下午显示的比较细，而且也没有找到调节的选项。

### 模块日志

太多了，需要的话我再上传吧

### 复现步骤

```bash
设置状态栏时间为aa h：mm
....
出现问题
```

### 问题截图

![图片注释](图片链接)
在第一步

### HyperCeiler 设备信息

![图片注释](图片链接)
![Screenshot_2024-08-12-15-25-08-965_com sevtinge hyperceiler-edit](https://github.com/user-attachments/assets/b77baec1-aa89-4151-8f12-e5bd9c7f2a5f)
![Screenshot_2024-08-12-15-29-57-310_com sevtinge hyperceiler-edit](https://github.com/user-attachments/assets/c84f279b-39a8-4123-bf7b-53a0d87b122e)

**Comment by Sevtinge** [comment]
经典控制中心不再维护

**Comment by freedomspiritJohn** [comment]
> 经典控制中心不再维护

在哪里可以修改系统文件改变这里的字体啊，看着挺别扭的。
