### ISSUE TITLE
🐛 [BUG] <HyperOS每次重启开机后，添加的5G网络开关80%概率掉了>

### ISSUE THREAD

**Issue by momoanonyman** [ReChronoRain/HyperCeiler#807]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

1，在Hyperceiler“系统界面”-“通知与控制中心”-“5G网络开关”，选择样式一，将5G网络开关调整到合适位置后，几乎每次重启后，5G网络开关都跑到了备选的位置上，需要重新调整，很麻烦，怀疑是刚开机Hyperceiler没有过得Root或者Lsp权限，然后失效？

2，手机是红米Note12T Pro，系统是Hyperceiler最新7月安全补丁版本系统。

3，使用的最新的27006版本Magisk alpha与LSPosed 1.9.2 7024正式版

### 模块日志

[LSPosed_2024-08-12T18_13_11.324466.zip](https://github.com/user-attachments/files/16580304/LSPosed_2024-08-12T18_13_11.324466.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![IMG_20240812_182259](https://github.com/user-attachments/assets/23247be9-97ad-47b9-bf33-01808c09e8c3)
![Screenshot_2024-08-12-18-21-46-567_mark via-edit](https://github.com/user-attachments/assets/ffe4f0c2-8096-4528-b698-72ccfa27fb53)
![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Uploading Screenshot_2024-08-12-18-24-47-136_com.sevtinge.hyperceiler.jpg…]()

**Comment by momoanonyman** [comment]
![Screenshot_2024-08-12-18-24-47-136_com sevtinge hyperceiler](https://github.com/user-attachments/assets/86080826-8541-4177-b463-d47631dad496)

**Comment by Sevtinge** [comment]
这得去检查你的模块挂载逻辑，有一段时间出现了没hook上，不是HyperCeiler的问题

**Comment by momoanonyman** [comment]
我也以为是我的问题，我重装了官方系统，在仅安装LSPosed（7024正式版）、官方面具27001、Hyperceiler0629正式版的情况下，重启后5G磁铁还掉，我尝试使用了米客，发现没有掉磁铁的问题，大佬帮忙看下吧，真的很喜欢西米露
