### ISSUE TITLE
💡 [需求] 加入修改手机名称校验绕过功能

### ISSUE THREAD

**Issue by gjmhmm8** [ReChronoRain/HyperCeiler#809]
### 需求内容

加入修改手机名称校验绕过功能

### 实现思路&截图

![Screenshot_2024-08-12-20-56-12-742_com android settings](https://github.com/user-attachments/assets/fd375229-09c4-47e0-9bd1-2f6c4a9f1931)

### 简单例子

加入修改手机名称校验绕过功能，跳过联网检查

**Comment by Sevtinge** [comment]
你是完全不看回复的吗
