### ISSUE TITLE
🐛 [BUG] 名称校验去除不彻底

### ISSUE THREAD

**Issue by gjmhmm8** [ReChronoRain/HyperCeiler#810]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

wifi热点名称依然存在强制联网校验
版本2.4.149_a823ef7c_r3291

### 模块日志

。

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-08-13-01-02-48-385_com android settings](https://github.com/user-attachments/assets/8b01f9e2-d5f0-49fb-bce0-203b57e53cbc)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by Sevtinge** [comment]
现在可以了
