### ISSUE TITLE
🐛 [BUG] 全局侧边栏无法打开，在游戏中开启

### ISSUE THREAD

**Issue by msccreater** [ReChronoRain/HyperCeiler#814]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

想要使用全局侧边栏的游戏工具箱，勾选了游戏app，然后勾选在游戏中打开，返回后再打开全局侧边栏，发现刚才打勾的再游戏中开启是没有勾选的状态,，也无法使用游戏工具箱

### 模块日志

。。。

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
。。。
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by lingqiqi5211** [comment]
未上传任何信息是虚空问诊，将被无条件关闭
