### ISSUE TITLE
堆叠桌面

### ISSUE THREAD

**Issue by BanZhuanQN** [ReChronoRain/HyperCeiler#817]
### 需求内容

系统桌面最近任务堆叠

### 实现思路&截图

![Uploading Screenshot_2024-08-16-21-21-28-879_com.miui.home.jpg…]()

### 简单例子

![Screenshot_2024-08-16-21-21-28-879_com miui home](https://github.com/user-attachments/assets/d59ac02e-88b3-4ab4-8475-1c2a25a5ab50)

**Comment by Sevtinge** [comment]
你杀了我吧

**Comment by lingqiqi5211** [comment]
@Sevtinge 乐
