### ISSUE TITLE
🐛 [BUG] 关于更改省电策略UI没有刷新的反馈与优化建议

### ISSUE THREAD

**Issue by sbmatch** [ReChronoRain/HyperCeiler#82]
### 问题描述

启用 《禁止恢复电池优化白名单》功能后，在系统应用管理页手动修改应用的省电策略时 出现第一次修改UI没有刷新的问题，后续则正常刷新UI 建议可以尝试手动调用一下com.miui.powerkeeper.ui.HiddenAppsConfigFragment 类的void refreshView()方法通知系统刷新设置项UI

### 模块日志

无

### 复现步骤

```bash
1. 前往 '电量与性能'
2. 点击 '禁止恢复电池优化白名单'
3. 前往应用详情页修改省电策略

....
出现问题
第一次修改省电策略 设置项UI不会刷新，但是实际是已经修改成功，后续可以正常刷新
```

### 机型

Redmi K40S

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

2.3.132_20231122_b 8 b517bd | canary

**Comment by HChenX** [comment]
无伤大雅的东西就不搞了
