### ISSUE TITLE
🐛 [BUG] <问题标题>从左上角下滑状态栏系统桌面会黑屏重启 百分百触发

### ISSUE THREAD

**Issue by Tang121337** [ReChronoRain/HyperCeiler#820]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

状态栏功能出现异常
从左上角下拉状态栏稳定触发黑屏重启桌面（应该是通话靠近黑屏那个）

### 模块日志

[LSPosed_2024-08-17T13_56_20.634998.zip](https://github.com/user-attachments/files/16643643/LSPosed_2024-08-17T13_56_20.634998.zip)

### 复现步骤

```bash
从左上角下拉状态栏稳定触发黑屏重启桌面 多重启几次状态栏修改状态就会恢复系统默认 同时无此bug
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![Uploading Screenshot_2024-08-17-14-01-09-658_com.sevtinge.hyperceiler.jpg…]()

**Comment by Sevtinge** [comment]
已知不会修

**Comment by Tang121337** [comment]
> 已知不会修

是不会修还是不会修哈哈哈哈额哈哈哈

**Comment by Sevtinge** [comment]
@Tang121337 不会修，我没这个石粒（

**Comment by Tang121337** [comment]
> @Tang121337 不会修，我没这个石粒（

凸(艹皿艹 )哈哈哈辛苦了
