### ISSUE TITLE
💡 [需求] 建议加入小米社区伪装机型的功能

### ISSUE THREAD

**Issue by jyf7852** [ReChronoRain/HyperCeiler#821]
### 需求内容

很多小米的内测需要用指定的机型才能报名内测 不是指定的机型想报名暂时只能通过其他伪装机型的magisk模块很不方便

### 简单例子

建议小米社区也能想应用商店一样有伪装机型的功能

**Comment by Sevtinge** [comment]
@jyf7852 guise
