### ISSUE TITLE
💡 [需求] 在阉割系统上启用小窗

### ISSUE THREAD

**Issue by zty012** [ReChronoRain/HyperCeiler#823]
### 需求内容

在redmi 13c 5g（air）上，小窗功能被阉割，可以加一个启用小窗的选项

### 简单例子

添加一个选项，强制启用系统小窗

**Comment by Wu-HZ** [comment]
试试非官方小窗吧，既然被阉割了 还怎么能开启呢

**Comment by zty012** [comment]
解决了，把系统桌面->其他->小窗模式和强制识别为高端机型打开就可以了
