### ISSUE TITLE
🐛 [BUG] 网速设置失效了，改不了大小位置

### ISSUE THREAD

**Issue by 500750** [ReChronoRain/HyperCeiler#824]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

网速调节功能失效

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![图片注释](图片链接)

**Comment by lingqiqi5211** [comment]
未上传任何信息是虚空问诊，将被无条件关闭
