### ISSUE TITLE
💡 [需求] 能否使得下载管理程序修改下载目录以及禁止更新

### ISSUE THREAD

**Issue by warglaive6046** [ReChronoRain/HyperCeiler#827]
### 需求内容

如题
![Screenshot_2024-08-22-17-03-01-857_com android providers downloads ui](https://github.com/user-attachments/assets/669489f8-9c9d-4d60-afb6-871467f7db5f)

### 简单例子

将下载目录修改为指定目录方便管理，比如从/storage/emulated/0/Download/DLManager修改为系统默认/storage/emulated/0/Download

**Comment by Sevtinge** [comment]
@warglaive6046 好想法 等我看看

**Comment by warglaive6046** [comment]
> @warglaive6046 好想法 等我看看

秒回的吗？辛苦了 感谢您与整个项目成员组的努力与付出

**Comment by Wu-HZ** [comment]
我的下载管理默认下载至/storage/emulated/0/Download/，我需要修改至/storage/emulated/0/Download/DLManager/
我想，通过"质感清理"app可以实现

**Comment by Sevtinge** [comment]
@warglaive6046 看了下 SDK29后写不了 由于若智Android限制 任务创建会失败
