### ISSUE TITLE
🐛 [BUG] 开启圆角矩形磁贴，部分图标点击后变回圆形

### ISSUE THREAD

**Issue by zym013579** [ReChronoRain/HyperCeiler#84]
### 问题描述

开启圆角矩形磁贴后，点击黄色图标（例如手电筒、省电模式等），图标会变成圆形，再点一下关掉也还是圆形

### 模块日志

[LSPosed_2023-11-23T09_35_05.745110.zip](https://github.com/ReChronoRain/HyperCeiler/files/13445429/LSPosed_2023-11-23T09_35_05.745110.zip)

### 复现步骤

```bash
1. 开启圆角矩形磁贴
2. 点击黄色图标（例如手电筒、省电模式等）
3. 图标变成圆形
再点一下关掉也还是圆形
```

### 问题截图

![初始](https://github.com/ReChronoRain/HyperCeiler/assets/18380161/0dff4fa9-0a4c-420c-8783-3aed9977ffcc)
![点击](https://github.com/ReChronoRain/HyperCeiler/assets/18380161/ffaea578-ea37-4bba-8e39-5d786be7c938)
![再次点击](https://github.com/ReChronoRain/HyperCeiler/assets/18380161/79a2feb3-44e4-4839-82ac-20955e1c12d1)

### 机型

Xiaomi 13 Ultra

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.12_20231122_b8b517bd

**Comment by Sevtinge** [comment]
待修

**Comment by HChenX** [comment]
is重复
