### ISSUE TITLE
💡 [需求]已经两个多月没更新了，很多东西都失效了

### ISSUE THREAD

**Issue by CyanDragonS** [ReChronoRain/HyperCeiler#853]
### 需求内容

感谢各位开发者的付出，可否考虑每修复一些就出一个preRelease或者小版本，而非积攒很多以后更新一次？

### 简单例子

0

**Comment by lingqiqi5211** [comment]
@CyanDragonS 不打算直接发版，请自行到 github actions 构建自助下载 canary 版本

https://github.com/ReChronoRain/HyperCeiler/actions

**Comment by CyanDragonS** [comment]
> @CyanDragonS 不打算直接发版，请自行到 github actions 构建自助下载 canary 版本
> 
> https://github.com/ReChronoRain/HyperCeiler/actions

感谢，之前没有看到这里有，抱歉
