### ISSUE TITLE
💡 [需求] <增加(忽略mipush注册时的签名验证)作用域:小米服务框架>

### ISSUE THREAD

**Issue by psychosispy** [ReChronoRain/HyperCeiler#86]
### 需求内容

让非官方签名的, 支持mipush的软件, 可以被小米服务框架注册mipush

### 简单例子

小米服务框架作为mipush的推送组件, 会验证应用的签名是否为官方, 进行推送注册, 或许可以对小米服务框架进行hook, 让非官方签名的软件也可以注册mipush

**Comment by HChenX** [comment]
不做
