### ISSUE TITLE
💡 [需求] <移除未知来源授权限制>

### ISSUE THREAD

**Issue by weixiansen574** [ReChronoRain/HyperCeiler#862]
### 需求内容

就是那个

移除安装器的安装未知来源权限检查：`出于安全考虑，目前已禁止您的手机安装来自此来源的未知应用。您可以在“设置”中对此进行更改。`，参考我的模块，hook系统框架，使其不要检查这个权限，原生安卓也可用。这个授权纯纯恶心人，到MIUI这里还多了个十秒倒计时😅

### 简单例子

有代码实现了，希望可以整合进去
https://github.com/weixiansen574/FuckUnknownSourcesRestrictions

**Comment by Sevtinge** [comment]
7c288f9ea55a8db162ad217b545119d0038deccb
