### ISSUE TITLE
模块添加故障自检

### ISSUE THREAD

**Issue by DreammStill** [ReChronoRain/HyperCeiler#869]
### 需求内容

可以在模块中显示hook失败的项目以便了解可用的功能

### 实现思路&截图

通过获取错误日志定位到出问题的功能上，并用不同颜色标注出来？

### 简单例子

比如某个功能不能用，日志中会报错，获取报错的功能，显示出来

**Comment by Sevtinge** [comment]
@DreammStill 杀了我吧

**Comment by DreammStill** [comment]
> @DreammStill 杀了我吧

😂😂😂实在不好实现的话也不用勉强，我可以自己去日志找那些功能不生效的
