### ISSUE TITLE
🐛 [BUG] <无故提示log服务异常>

### ISSUE THREAD

**Issue by mrliguo** [ReChronoRain/HyperCeiler#873]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

未安装禁log版本的lsp，也未安装禁log到相关模块，但西米露提示log服务异常，修复后可在重启前正常，设备重启后仍会提示log服务异常

### 模块日志

此为lsp内log，为空
![Screenshot_2024-09-29-22-56-05-600_com android shell](https://github.com/user-attachments/assets/235df5e9-ae0e-46a8-8d0a-ac0fa146a372)

### 复现步骤

```bash
重启设备后即提示异常
```

### 问题截图

此为西米露内截图
![Screenshot_2024-09-29-22-56-05-600_com android shell](https://github.com/user-attachments/assets/c46f38e6-1183-4640-a86d-ad34e5f21d28)

### HyperCeiler 设备信息

虽然为安卓15，但在安卓14时也出现了相同问题
![Screenshot_2024-09-29-19-48-17-483_com android settings](https://github.com/user-attachments/assets/8360dfcf-4c8e-44a6-b2cf-b3a91864133b)

![Uploading Screenshot_2024-09-29-23-00-15-147_com.sevtinge.hyperceiler.jpg…]()

**Comment by mrliguo** [comment]
西米露内截图上传错了，这个才是
![Uploading Screenshot_2024-09-29-22-45-27-617_com.sevtinge.hyperceiler.jpg…]()

**Comment by mrliguo** [comment]
格机后恢复正常

**Comment by JSCSZZSS** [comment]
所以这是啥情况，我今天也突然报错log服务异常

**Comment by mrliguo** [comment]
不清楚，如果在西米露里面修复root，但是重启之后还是这样的话，把手机恢复出厂设置就可以解决




李果君
***@***.***

**Comment by mrliguo** [comment]
> 只能恢复出厂设置吗…… 弄了好多app设置不想再弄了……

备份之后恢复吧

**Comment by p88oo** [comment]
> > 只能恢复出厂设置吗…… 弄了好多app设置不想再弄了……
> 
> 备份之后恢复吧

已经在恢复资料了😭折磨
