### ISSUE TITLE
修改未读通知角标颜色

### ISSUE THREAD

**Issue by Tempzxxx** [ReChronoRain/HyperCeiler#875]
### 需求内容

希望下下一版可以增加这个功能。目前系统默认红色，太显眼，和有些壁纸色系不搭配。希望可以修改。。多谢

### 简单例子

希望下下一版可以增加这个功能。目前系统默认红色，太显眼，和有些壁纸色系不搭配。希望可以修改。。多谢

**Comment by Sevtinge** [comment]
4b613fdd15dfb89fd7f4b1aa4f9d907538c3ccc2
