### ISSUE TITLE
增加对小米云服务的hook

### ISSUE THREAD

**Issue by lkx-0686** [ReChronoRain/HyperCeiler#89]
### 需求内容

![Screenshot_2023-11-24-10-33-02-898_com miui cloudservice](https://github.com/ReChronoRain/HyperCeiler/assets/67402737/3dd979ea-f154-4cc2-9bc8-20a83f42d1e5)
增加对小米云服务的hook，以便在手机端使用云服务同步小米创作

### 实现思路&截图

![Screenshot_2023-11-24-10-33-02-898_com miui cloudservice](https://github.com/ReChronoRain/HyperCeiler/assets/67402737/d9fd734e-c359-43c5-9b3e-f2f013d549a4)

### 简单例子

增加对小米云服务的hook，以便在手机端使用云服务同步小米创作

**Comment by HChenX** [comment]
不做

**Comment by HChenX** [comment]
另一位大佬写了
