### ISSUE TITLE
🐛 [BUG] 开启抽屉模糊会导致桌面异常重载

### ISSUE THREAD

**Issue by OnismIS** [ReChronoRain/HyperCeiler#90]
### 问题描述

开启抽屉模糊后，在应用抽屉内打开应用然后上滑返回桌面，必定导致桌面重载，100%复现

### 模块日志

[LSPosed_2023-11-24T12_56_05.975493.zip](https://github.com/ReChronoRain/HyperCeiler/files/13455286/LSPosed_2023-11-24T12_56_05.975493.zip)

### 复现步骤

```bash
1. 打开“抽屉模糊”
2. 自“应用抽屉”打开任一应用
3. 使用上滑手势返回桌面

出现桌面重载
```

### 问题截图

无

### 机型

HOUJI

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231123_ca91a429 | canary

**Comment by HChenX** [comment]
重复提交的bug

**Comment by OnismIS** [comment]
> 重复提交的bug

在open的issue内未找到相关bug
