### ISSUE TITLE
🐛 [BUG] <系统更新 移除OTA验证功能无效>

### ISSUE THREAD

**Issue by kxkl2077** [ReChronoRain/HyperCeiler#915]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

无论是重启系统更新，重启系统都没用，

### 模块日志

----part 1 start----
[ 2024-10-26T09:16:44.452     1000:  2291:  2291 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~EXHnekzf5bNzobdlshgFFw==/com.sevtinge.hyperceiler-8kWMojvnCDedSQOSKw2cEg==/base.apk
[ 2024-10-26T09:16:44.472     1000:  2291:  2291 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T09:16:44.723     1000:  2291:  2291 I/LSPosed-Bridge  ] Loading legacy module com.coderstory.toolkit from /data/app/~~HEniSAKGl5LQhwzyS7Up2g==/com.coderstory.toolkit-Ujs3rnjuBbZXYCAxnbk8iQ==/base.apk
[ 2024-10-26T09:16:44.725     1000:  2291:  2291 I/LSPosed-Bridge  ]   Loading class toolkit.coderstory.MainHook
[ 2024-10-26T09:16:45.689     1000:  2291:  2291 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T09:16:50.035     1000:  2291:  2291 I/LSPosed-Bridge  ] [HyperCeiler][E][getAppsUsingInputMethod]: have e: java.lang.IllegalStateException: IInputMethodManager is not available
[ 2024-10-26T09:23:50.263    10318: 25659: 25659 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~EXHnekzf5bNzobdlshgFFw==/com.sevtinge.hyperceiler-8kWMojvnCDedSQOSKw2cEg==/base.apk
[ 2024-10-26T09:23:50.286    10318: 25659: 25659 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T09:23:50.412    10318: 25659: 25659 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T09:25:49.110    10318: 29058: 29058 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~GKlct-FMO863UrHn7njU2A==/com.sevtinge.hyperceiler-70c7ZVY3K_S0QzzWYYkiFQ==/base.apk
[ 2024-10-26T09:25:49.122    10318: 29058: 29058 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T09:25:49.221    10318: 29058: 29058 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T09:26:08.566    10318: 29584: 29584 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~GKlct-FMO863UrHn7njU2A==/com.sevtinge.hyperceiler-70c7ZVY3K_S0QzzWYYkiFQ==/base.apk
[ 2024-10-26T09:26:08.580    10318: 29584: 29584 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T09:26:08.710    10318: 29584: 29584 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T09:37:48.332    10318: 13436: 13436 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~GKlct-FMO863UrHn7njU2A==/com.sevtinge.hyperceiler-70c7ZVY3K_S0QzzWYYkiFQ==/base.apk
[ 2024-10-26T09:37:48.354    10318: 13436: 13436 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T09:37:48.487    10318: 13436: 13436 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T10:02:05.949    10303: 14841: 14841 I/LSPosed-Bridge  ] Loading legacy module com.coderstory.toolkit from /data/app/~~HEniSAKGl5LQhwzyS7Up2g==/com.coderstory.toolkit-Ujs3rnjuBbZXYCAxnbk8iQ==/base.apk
[ 2024-10-26T10:02:05.950    10303: 14841: 14841 I/LSPosed-Bridge  ]   Loading class toolkit.coderstory.MainHook
[ 2024-10-26T10:02:48.173    10318: 15491: 15491 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~GKlct-FMO863UrHn7njU2A==/com.sevtinge.hyperceiler-70c7ZVY3K_S0QzzWYYkiFQ==/base.apk
[ 2024-10-26T10:02:48.189    10318: 15491: 15491 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T10:02:48.318    10318: 15491: 15491 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn
[ 2024-10-26T10:03:35.891    10318: 16792: 16792 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~GKlct-FMO863UrHn7njU2A==/com.sevtinge.hyperceiler-70c7ZVY3K_S0QzzWYYkiFQ==/base.apk
[ 2024-10-26T10:03:35.903    10318: 16792: 16792 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-10-26T10:03:36.019    10318: 16792: 16792 I/LSPosed-Bridge  ] [HyperCeiler][I]: Log level is Warn

### 复现步骤

```bash
1. 前往 'HyperCeiler'
2. 点击 '系统更新'
3. 点击 '移除VAB验证'
4. 点击 '右上角重启系统更新'
5. 前往 '系统更新'
6. 点击 '手动选择更新包'
7. 过一会提示 'ROM包处于内测中，请确认已经登录有内测权限的小米账户&
测权限的小米账户
....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2024-10-26-09-28-05-664_com android updater](https://github.com/user-attachments/assets/e65e1f55-8471-4d49-bd44-9370a3bf92c3)
![Screenshot_2024-10-26-09-58-14-345_com sevtinge hyperceiler](https://github.com/user-attachments/assets/5c659cb0-326b-4927-82f6-2ac66731283b)

### HyperCeiler 设备信息

![图片注释](图片链接)
Debug Info by HyperCeiler

VersionName = 2.5.150_20240927
VersionCode = 150
BuildTime = (UTC+0:00) 2024-09-27 03:32:12
BuildType = release
GitHash = 05db6422e
GitCode = 3387
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Redmi Note 12 Turbo
DeviceName = marble
Model = 23049RAD8C
Brand = Redmi
Manufacture = Xiaomi
Board = marble
Soc = SM7475
ModDevice = marble
Characteristics = nosdcard
Pad = false
FingerPrint = Redmi/marble/marble:14/UKQ1.230804.001/V816.0.7.0.UMRCNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = dc53f62ac1643a34
DeviceToken = b5ef255d59b6bcf7151278772f4cdd07162da93e5530fcad9282023326045acb

AndroidSdkVersion = 34
MiuiVersion = 816.0
HyperOsVersion = 1.0
SystemVersion = OS1.0.7.0.UMRCNXM
InternationalBuild = false
BaseOs = Redmi/marble/marble:14/UKQ1.230804.001/V816.0.6.0.UMRCNXM:user/release-keys
Host = pangu-build-component-system-191250-2lw5c-9zd86-178kh
BuildDate = Fri Sep  6 02:21:49 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
WhoAmI = root
LoggerStatus = false, NO_SUCH_LOG

**Comment by kxkl2077** [comment]
[LSPosed_2024-10-26T10_05_01.131717.zip](https://github.com/user-attachments/files/17528698/LSPosed_2024-10-26T10_05_01.131717.zip)

**Comment by Sevtinge** [comment]
日志等级开到info或debug。重新抓一下

**Comment by kxkl2077** [comment]
没事了
