### ISSUE TITLE
🐛 [BUG] 优化打断动画bug

### ISSUE THREAD

**Issue by LHX090126** [ReChronoRain/HyperCeiler#94]
### 问题描述

打开设置后马上任意打开一个二级菜单 马上打断 连续打断就会卡出拉伸的图标

### 模块日志

[LSPosed_2023-11-26T20_58_55.763133.zip](https://github.com/ReChronoRain/HyperCeiler/files/13466852/LSPosed_2023-11-26T20_58_55.763133.zip)

### 复现步骤

```bash
1打开设置 
2瞬间打开任意二级菜单
3打断
4连续打断
```

### 问题截图

https://github.com/ReChronoRain/HyperCeiler/assets/99321020/2e06faed-5674-4fe8-aaed-da80af4dd6bf

### 机型

Redmi K60

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231123

**Comment by HChenX** [comment]
小米自己的bug
