### ISSUE TITLE
💡 [需求] 添加AOD模糊背景选项

### ISSUE THREAD

**Issue by qioiyuiwtroabc** [ReChronoRain/HyperCeiler#976]
### 需求内容

能不能在进入AOD的过程中加入模糊过渡效果，从而实现iOS live壁纸的效果！！

### 实现思路&截图

灵感来源 https://b23.tv/msAAoMq

### 简单例子

使系统界面更加现代化和美观

**Comment by Hvsenjan** [comment]
用MIUI Extra 可以实现
地址：https://github.com/Art-Chen/MIUI-Extra-YukiAPI/releases

**Comment by qioiyuiwtroabc** [comment]
> 使用MIUI Extra可以实现 地址：https://github.com/Art-Chen/MIUI-Extra-YukiAPI/releases

可以讲明一下具体怎么操作的吗🧐

**Comment by Hvsenjan** [comment]
> > 使用MIUI Extra可以实现 地址：https://github.com/Art-Chen/MIUI-Extra-YukiAPI/releases
> 
> 可以讲明一下具体怎么操作的吗🧐

安装模块重启激活后点进去就可以设置，打开开关后再重启一遍手机就可以了
![Screenshot_2024-11-17-19-16-50-934_moe chenxy miuiextra-edit](https://github.com/user-attachments/assets/6db0b67b-5812-45f5-8037-c75b7e27dd87)

**Comment by qioiyuiwtroabc** [comment]
> > > 使用MIUI Extra可以实现 地址：https://github.com/Art-Chen/MIUI-Extra-YukiAPI/releases
> > 
> > 
> > 可以讲明一下具体怎么操作的吗🧐
> 
> 安装模块重启激活后点进去就可以设置，打开开关后再重启一遍手机就可以了 ![Screenshot_2024-11-17-19-16-50-934_moe chenxy miuiextra-edit](https://private-user-images.githubusercontent.com/48145442/386948932-6db0b67b-5812-45f5-8037-c75b7e27dd87.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDI3MzQsIm5iZiI6MTczMTg0MjQzNCwicGF0aCI6Ii80ODE0NTQ0Mi8zODY5NDg5MzItNmRiMGI2N2ItNTgxMi00NWY1LTgwMzctYzc1YjdlMjdkZDg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDExMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjIyMzJhMDA4NzkwMzQyY2FiNDhkMWMwMGY3YTRiZjA0M2I0NzhkNTE4MWQ0NzYxMmY3NDkzMWE4ZWFjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._tYSKlkaqG4zNo7ziKAPrulIoqKQmc7e--S1EgtX9g0)

明白了，感谢大佬指点！☺️
