### ISSUE TITLE
🐛 [BUG] <频繁请求root>

### ISSUE THREAD

**Issue by sherkent** [ReChronoRain/HyperCeiler#98]
### 问题描述

一打开桌面文件夹，cemiuiler就请求root（面具弹窗cemiuiler已被授予root权限），cemiuiler中没有修改任何东西也是这样

### 模块日志

[LSPosed_2023-11-27T22_55_33.171645.zip](https://github.com/ReChronoRain/HyperCeiler/files/13476621/LSPosed_2023-11-27T22_55_33.171645.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

redmi note12turbo

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

1.3.130_20231101

**Comment by HChenX** [comment]
未知，可以尝试关闭magisk的toast弹窗
